camunda/connectors

bundle-templates.sh

Ensures we publish templates with a `-$version` qualifier.
Example: If `slack-connector.json` has a `.version` field _THEN_ we rename it to `slack-connector-$version.json`.
Gracefully handles missing version (does not rename).
Gracefully handles templates packed as arrays (we should get rid of these).
Related to https://github.com/camunda/team-connectors/issues/170

chore: publish templates with `-version` qualifier

---

README.md
bundle/Dockerfile
bundle/README.md
bundle/bundle-templates.sh
runtime/README.md

Bumps to SDK `0.3.0` and related Connectors.
related to https://github.com/camunda/team-connectors/issues/203

chore: bump to SDK `0.3.0` and related Connectors

---

.github/workflows/ADD_TO_PROJECT.yml

Generalize `actions/add-to-project` version.
This will reduce noise in the release changelog.

ci: generalize `actions/add-to-project` version

---

.github/workflows/RELEASE.yaml
bundle/bundle-templates.sh
licenses/third-party.ftl

* Handle pre-release versions automatically (mark as pre-release in GitHub, skip uploading images with latest tag)
* Clean up `bundle-templates.sh`
* Remove extra input flags: `release-runtime`, `release-bundle`, `push-latest`
* Handle missing license URLs in THIRD_PARTY_NOTICES
related to #37

fix: release workflow

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/TASK.md

Adjusting the issue templates' labels to fit the new labels.
related to https://github.com/camunda/team-connectors/issues/243

docs: adjust labels in issue templates

---

.github/workflows/RELEASE.yaml

Add the version to the run name of the release workflow.
n/a

ci: add version to release run name

---

.github/workflows/RELEASE.yaml

Deactivate Dockerhub readme updates, as login does not work yet (cannot reuse docker/login action).
n/a

ci: deactivate dockerhub readme updates

---

README.md
bundle/mvn/camunda-saas-bundle/src/main/resources/application.properties
bundle/mvn/default-bundle/pom.xml
bundle/mvn/default-bundle/src/test/resources/application.properties
bundle/mvn/pom.xml

Add prometheus support via Spring Boot Actuator, so that Metrics can be scraped in Prometheus format under http://localhost:8080/actuator/prometheus or http://localhost:9080/actuator/prometheus depending on the port configured

Prometheus

---

bundle/mvn/pom.xml

https://github.com/camunda/team-connectors/issues/272

chore: bump spring-zeebe version to 8.1.11

---

.github/workflows/THIRD_PARTY_NOTICE.yaml

Don't set the `assignee` in the TPL PR that is created. This fails for `renovate[bot]` for example and is not necessary either.
n/a

ci: don't set assignee in TPL PR

---

bundle/mvn/pom.xml

Spring Zeebe version 8.1.13 is necessary for the new patch release.

chore: bump spring-zeebe version to 8.1.13

---

.github/workflows/RELEASE.yaml

Push READMEs for Bundle and Bundle SaaS to Docker Hub as repository descriptions.
closes #89

ci: push readmes to dockerhub

---

.github/workflows/RELEASE.yaml

The issue with access token was fixed, see [test run logs](https://github.com/camunda/connectors-bundle/actions/runs/3757915468/jobs/6385645709)

Enable pushing README on release

---

connectors/aws-lambda/pom.xml
connectors/google-drive/pom.xml
connectors/http-json/pom.xml
connectors/kafka/pom.xml
connectors/microsoft-teams/pom.xml
connectors/pom.xml
connectors/rabbitmq/pom.xml
connectors/sendgrid/pom.xml
connectors/slack/pom.xml
connectors/sns/pom.xml
connectors/sqs/pom.xml

Maven Shade plugin config is missing in most connectors, which leads to failures during classpath bundling (without Maven)
related to https://github.com/camunda/team-connectors/issues/258

chore(build): add maven shade plugin where missing

---

connector-archetype-internal/pom.xml
connectors/pom.xml

* Disables Maven Central release for connector archetype
* Fixes maven shade plugin config (disabled for `connector-function-parent`, enabled for children artifacts)

Fix release build

---

pom.xml

Previous module order caused an interesting bug that resulted in artifacts not being uploaded to Maven Central.
The plugin that performs Central deployment defers the actual upload, so all artifacts that were created during the build are uploaded during the build of the last artifact.
In our case, `connector-archetype-internal` is the last module in the build order, so building it is supposed to also trigger the upload of all previously built artifacts. But we disabled the Maven Central upload for this specific module, so everything got skipped instead of just the archetype module.

fix(build): fix module order to re-enable central upload

---

pom.xml

deps: bump SDK to 0.6.0-SNAPSHOT
Depends on:
- https://github.com/camunda/connector-sdk/pull/335

deps: bump SDK to 0.6.0-SNAPSHOT

---

connectors/sqs/src/main/java/io/camunda/connector/SqsConnectorFunction.java
connectors/sqs/src/main/java/io/camunda/connector/model/QueueRequestData.java
connectors/sqs/src/test/java/io/camunda/connector/BaseTest.java
connectors/sqs/src/test/java/io/camunda/connector/SqsConnectorFunctionParametrizedTest.java
connectors/sqs/src/test/java/io/camunda/connector/SqsConnectorFunctionTest.java
connectors/sqs/src/test/java/io/camunda/connector/SqsConnectorRequestTest.java

Point to be confirmed: backward compatibility.
Pass JSONs instead of key-value's in payload.
- Related to https://jira.camunda.com/browse/SUPPORT-15656
closes # TBD

fix(sqs): pass JSONs instead of key-value's in payload

---

connectors/aws-lambda/element-templates/aws-lambda-connector.json
connectors/google-drive/element-templates/google-drive-connector.json
connectors/http-json/element-templates/http-json-connector.json
connectors/kafka/element-templates/kafka-connector.json
connectors/microsoft-teams/element-templates/microsoft-teams-connector.json
connectors/rabbitmq/element-templates/rabbitmq-connector.json
connectors/slack/element-templates/slack-connector.json
connectors/sns/element-templates/aws-sns-connector.json
connectors/sqs/element-templates/aws-sqs-connector.json

chore(docs, element templates): add documentation references to Result Mapping
- https://github.com/camunda/connectors-bundle/issues/158

chore(docs, element templates): add documentation references to Result Mapping

---

bundle/mvn/default-bundle/Dockerfile
bundle/mvn/default-bundle/start.sh

chore: moved java execution to start.sh
The Docker `ENTRYPOINT` in exec-mode does not allow to pass environment variables thus reworked it to enter from shell while preserving entripoint in exec-mode.
Preserving exec mode is required, since we wish to allow docker to manage zeebe and operate IP addresses.
- https://github.com/camunda/camunda-platform/pull/82
closes #108

chore: moved java execution to start.sh

---

connectors/google-drive/element-templates/google-drive-connector.json

Forced parent folder ID as optional.
- https://forum.camunda.io/t/google-drive-connector/42163

fix(gdrive): forced parent folder ID as optional

---

.github/workflows/DEPLOY.yaml
.github/workflows/RELEASE.yaml
.github/workflows/TEST.yml
.github/workflows/THIRD_PARTY_NOTICE.yaml

Use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml
closes https://github.com/camunda/team-connectors/issues/327

chore(ci): use CI Nexus as a mirror

---

pom.xml

Bump SDK version to 0.6.0 and Spring Zeebe version to 8.1.17
https://github.com/camunda/team-connectors/issues/330
closes #

deps: bump SDK version to 0.6.0 and Spring Zeebe version to 8.1.17

---

.github/workflows/DEPLOY.yaml
.github/workflows/RELEASE.yaml

Enables multiplatform build for amd64 and arm64 platforms by using QEMU emulator.
Already tested and [published under  `SNAPSHOT` tag](https://hub.docker.com/r/camunda/connectors-bundle-saas/tags) - feel free to check it out!
References:
- https://github.com/camunda/docker-camunda-bpm-platform/pull/237
- https://blog.thesparktree.com/docker-multi-arch-github-actions
closes #308

feat(docker): add multiplatform build

---

connectors/github/element-templates/github-webhook-connector.json
connectors/webhook-connector/element-templates/webhook-connector.json

This PR explicitly defines `elementType` in our inbound webhook connector templates.
closes #335

fix(inbound): add element type to inbound connector templates

---

connectors/github/element-templates/github-webhook-connector.json
connectors/webhook-connector/element-templates/webhook-connector.json

Webhook type was renamed from `webhook` to `io.camunda:webhook:1` to match the pattern we have for outbound.

chore(webhook): rename webhook template type

---

.github/workflows/RELEASE.yaml
bundle/mvn/camunda-saas-bundle/pom.xml
bundle/mvn/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/security/AudienceValidator.java
bundle/mvn/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/security/SecurityConfiguration.java
bundle/mvn/camunda-saas-bundle/src/main/resources/application.properties
pom.xml

Protects the new Connectors endpoint with M2M authentication.
related to https://github.com/camunda/team-connectors/issues/356

feat(bundle-saas): support m2m authentication in SaaS

---

.github/workflows/RELEASE.yaml

Allows to build changelog from a specified tag. Previously we couldn't generate a correct changelog when there were pre-releases in between the 'normal' releases.

feat(release): add fromTag for changelog generation

---

connectors/openai/element-templates/openai-connector.json
connectors/operate/element-templates/operate-connector.json

Fixed minor issues in Operate and OpenAI connector templates:
- Missing connector group (operate)
- Missing documentation ref (operate)
- Wrong connector ID pattern (operate)
- Missing sample result expression (openai)

Small fixes to Operate and OpenAI element templates

---

connectors/connectors-common-library/src/main/java/io/camunda/connector/common/model/CommonRequest.java
connectors/graphql/src/test/java/io/camunda/connector/graphql/GraphQLFunctionInputValidationTest.java
connectors/http-json/src/test/java/io/camunda/connector/http/BaseTest.java
connectors/http-json/src/test/java/io/camunda/connector/http/HttpJsonFunctionInputValidationTest.java
connectors/http-json/src/test/java/io/camunda/connector/http/HttpJsonFunctionSecretsTest.java
connectors/http-json/src/test/resources/requests/success-cases-replace-secrets.json

fix(rest): relax regex check for URL to allow placeholders.
closes #411
Given secret: `export HTTP_BIN_URL_FULL=https://httpbin.org/anything/anything`
---

fix(rest): relax regex check for URL to allow placeholders

---

connectors/power-automate/element-templates/power-automate-connector.json

Remove all ending dots in `description` property values to improve language consistency
Removed all ending dots as there were other places (beside the `Flow session ID`) where the `description` property ended with a dot (`.`)
closes #405

Remove all ending dots in `description` property values

---

connectors/sqs/element-templates/aws-sqs-connector.json

The `queue.messageGroupId` is now required for FIFO queues.
closes camunda/team-connectors/issues/368

fix(docs): Property `queue.messageGroupId` is required for FIFO queues.

---

connectors/connectors-common-library/src/main/java/io/camunda/connector/common/services/HTTPProxyService.java
connectors/connectors-common-library/src/main/java/io/camunda/connector/common/services/HTTPService.java
connectors/graphql/element-templates/graphql-connector.json
connectors/graphql/src/main/java/io/camunda/connector/graphql/GraphQLFunction.java
connectors/graphql/src/test/java/io/camunda/connector/graphql/GraphQLFunctionTest.java
connectors/graphql/src/test/resources/requests/success-test-cases.json

Enhance the GraphQL connector by adding the option to define custom http headers from the modeler and add them to the http request
closes https://github.com/camunda/connectors-bundle/issues/477

allows predefined headers for graphql connector

---

bundle/default-bundle/pom.xml
bundle/default-bundle/src/main/java/io/camunda/connector/bundle/ConnectorRuntimeApplication.java
bundle/default-bundle/src/main/resources/application.properties
bundle/default-bundle/src/test/resources/application.properties
spring-boot-starter-camunda-connectors/README.md
spring-boot-starter-camunda-connectors/pom.xml
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ConnectorsAutoConfiguration.java
spring-boot-starter-camunda-connectors/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-starter-camunda-connectors/src/main/resources/application.properties

Minor adjustments to support the new auto-configuration registration pattern defined in Spring Boot 3 (see [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration)). The auto-configuration needs to be defined in a different file now. I also kept the old file to keep it potentially compatible with spring boot 2.

fix: use spring-boot-3-style autoconfiguration

---

connectors/webhook-connector/element-templates/webhook-connector-intermediate.json
connectors/webhook-connector/element-templates/webhook-connector.json

Added 2 correlation key fields to the `Activation` group:
related to https://github.com/camunda/product-hub/issues/817

feat: webhook intermediate event template

---

spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/outbound/jobhandling/SpringConnectorJobHandler.java

Adds the connector output variable setter call (was lost during the runtime migration).

fix: connector result not propagated to process variables

---

connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/common/model/RabbitMqAuthentication.java

Removes sensitive data from `toString`.
closes #557

557: fix(rabbitmq): remove auth data from tostring

---

connectors/github/element-templates/github-webhook-connector-intermediate.json
connectors/github/element-templates/github-webhook-connector-start-event.json
connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json
connectors/kafka/element-templates/kafka-inbound-connector.json
connectors/rabbitmq/element-templates/rabbitmq-start-event-connector.json
connectors/webhook-connector/element-templates/webhook-connector-intermediate.json
connectors/webhook-connector/element-templates/webhook-connector-start-event.json

* Migrates webhook element template to the new result handling fields (`resultVariable`/`resultExpression` instead of a legacy `variableMapping` field)
* Fixes a copy-paste error in the kafka element templates
closes #559

fix: minor element template adjustments

---

pom.xml
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/ActiveInboundConnectorResponse.java
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorRestController.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManagerTest.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestControllerTest.java

Adds `elementId` to the API endpoint to enable filtering in the web modeler.
⚠️ Depends on https://github.com/camunda/connector-sdk/pull/466
related to https://github.com/camunda/connectors-bundle/issues/591

feat(runtime): add element id to inbound connector properties

---

spring-boot-starter-camunda-connectors/src/main/resources/application.properties

If you use the starter in your project and define a custom YAML config, these default properties will override your custom config.
See discussion https://github.com/camunda-community-hub/spring-zeebe/issues/429#issuecomment-1549336734

fix(config): remove default properties in the starter

---

connectors/automation-anywhere/element-templates/automation-anywhere-connector.json
connectors/blue-prism/element-templates/blue-prism-connector.json
connectors/connectors-common-library/src/main/java/io/camunda/connector/common/model/CommonRequest.java
connectors/easy-post/element-templates/easy-post-connector.json
connectors/github/element-templates/github-outbound.json
connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
connectors/graphql/element-templates/graphql-connector.json
connectors/graphql/src/test/resources/requests/fail-cases-connection-timeout-validation.json
connectors/http-json/element-templates/http-json-connector.json
connectors/http-json/src/test/resources/requests/fail-cases-connection-timeout-validation.json
connectors/openai/element-templates/openai-connector.json
connectors/operate/element-templates/operate-connector.json
connectors/power-automate/element-templates/power-automate-connector.json
connectors/twilio/element-templates/twilio-connector.json
connectors/uipath/element-templates/uipath-connector.json

This PR:
- improves the regex used to validate connection timeout, both in the template and in the Java code
- enables optional FEEL for the connection timeout property
related to #587

fix: adjust connection timeout regex

---

spring-boot-starter-camunda-connectors/README.md
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ConnectorsAutoConfiguration.java
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorLifecycleConfiguration.java
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/outbound/jobhandling/SpringConnectorJobHandler.java
spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManagerTest.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/CustomSecretProviderAggregatorTest.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/SPISecretProviderTest.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/SpringSecretProviderTest.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/providers/BarSpringSecretProvider.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/providers/FooSpringSecretProvider.java
spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/providers/SpiSecretProvider.java
spring-boot-starter-camunda-connectors/src/test/resources/META-INF/services/io.camunda.connector.api.secret.SecretProvider

This PR adds support for the new multiple secret providers features from the Connector SDK.
It is based on the following ideas:
- Secret Providers can be defined as Spring beans
- Secret Providers can also be defined using the ServiceLoader pattern
- Strategy to select the secret provider can be customized by implementing `SecretProviderAggregator`. It can also be defined as a Spring bean, overriding the default simple implementation.
see also: [previous PR in the SDK](https://github.com/camunda/connector-sdk/pull/472)
closes https://github.com/camunda/connector-sdk/issues/425

feat: support multiple secret providers

---

connectors/sns/element-templates/aws-sns-inbound-start-event.json
connectors/sns/src/main/java/io/camunda/connector/sns/inbound/SnsWebhookExecutable.java
connectors/sns/src/main/java/io/camunda/connector/sns/inbound/model/SnsWebhookConnectorProperties.java
connectors/sns/src/main/java/io/camunda/connector/sns/inbound/model/SnsWebhookProcessingResult.java
connectors/sns/src/main/java/io/camunda/connector/sns/inbound/model/SubscriptionAllowListFlag.java
connectors/sns/src/main/java/io/camunda/connector/sns/outbound/SnsConnectorFunction.java
connectors/sns/src/main/java/io/camunda/connector/sns/outbound/model/SnsAuthenticationRequestData.java
connectors/sns/src/main/java/io/camunda/connector/sns/outbound/model/SnsConnectorRequest.java
connectors/sns/src/main/java/io/camunda/connector/sns/outbound/model/SnsConnectorResult.java
connectors/sns/src/main/java/io/camunda/connector/sns/outbound/model/SnsMessageAttribute.java
connectors/sns/src/main/java/io/camunda/connector/sns/outbound/model/TopicRequestData.java
connectors/sns/src/main/java/io/camunda/connector/sns/suppliers/ObjectMapperSupplier.java
connectors/sns/src/main/java/io/camunda/connector/sns/suppliers/SnsClientSupplier.java
connectors/sns/src/main/java/io/camunda/connector/sns/suppliers/SnsGsonComponentSupplier.java
connectors/sns/src/main/resources/META-INF/services/io.camunda.connector.api.inbound.InboundConnectorExecutable
connectors/sns/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
connectors/sns/src/test/java/io/camunda/connector/sns/inbound/SnsWebhookExecutableTest.java
connectors/sns/src/test/java/io/camunda/connector/sns/outbound/BaseTest.java
connectors/sns/src/test/java/io/camunda/connector/sns/outbound/SnsConnectorFunctionParametrizedTest.java
connectors/sns/src/test/java/io/camunda/connector/sns/outbound/SnsConnectorFunctionTest.java
connectors/sns/src/test/java/io/camunda/connector/sns/outbound/SnsConnectorRequestTest.java

Implements SNS inbound connector.
Closes #574 
The webhook functionality has been refactored via [PR](https://github.com/camunda/connectors-bundle/pull/603).
Leaving message below for historical purposes.
This is a 'typical' implementation of a custom webhook that has to be refactored. This PR is for demonstration purposes for the upcoming design review meeting.
Data and template: https://github.com/camunda/connectors-bundle/pull/573
Diagram source:
```
@startuml
'https://plantuml.com/sequence-diagram
'autonumber
actor user
participant runtime
participant connector
== Init runtime ==
runtime -> runtime: start
== Init connector ==
connector -> connector: init
connector -> runtime: <SPI> register path
== Webhook flow ==
user -> runtime: <REST> trigger webhook
runtime -> runtime: <??> check …
```

feat(sns-inbound): added sns inbound

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManagerTest.java

Refine the contract of the webhook result handling. A failed activation should not lead to an http error.
closes #642

feat(webhook): Refine webhook contract.

---

bundle/default-bundle/src/main/resources/application.properties
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImportConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorLifecycleConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/MeteredInboundCorrelationHandler.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/metrics/ConnectorMetrics.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/jobhandling/SpringConnectorJobHandler.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManagerTest.java
pom.xml

In this PR I added new metrics for inbound connectors and slightly refined the existing metrics.
- Count inbound activations, deactivations, triggers as well as trigger outcomes, plus imported process definitions.
- The semantics of inbound metrics were changes:
- Previously `activated` metric related to connector trigger events.
- Now it is related to connector instance activations/deactivations, and triggers are recorded separately.
⚠️ Depends on https://github.com/camunda-community-hub/spring-zeebe/pull/440
Grafana dashboard will follow in another PR.
closes https://github.com/camunda/team-connectors/issues/290

feat: inbound metrics

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java

We get NPE from `Collectors::toMap` when entry value is `null`.

fix(rabbitmq): NPE during properties deserialization

---

connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java

fix(slack,inbound): forbid headers for commands

fix(slack,inbound): forbid headers for commands

---

connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/AMQPPropertyUtil.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/model/RabbitMqInboundResult.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/model/RabbitMqMessageProperties.java
connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/AMQPPropertyUtilTest.java
connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumerTest.java
connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/integration/RabbitMqIntegrationTest.java

1. Adds a custom DTO for RabbitMQ message properties to handle header deserialization properly (byte arrays should be handled as strings)
1. Also handles the potential NPE in `RabbitMqConsumer` when correlation result is null
closes #709

709 parse amqp headers as strings

---

bundle/default-bundle/Dockerfile
bundle/default-bundle/Dockerfile-focal
bundle/default-bundle/start.sh

Restored the `start.sh` file that was removed in the previous PR. The expectation was that we can reuse the `start.sh` from `connector-runtime/connector-runtime-application`, but this causes troubles: docker build context needs to be set to the root dir, and other paths need to be adjusted accordingly (`target` folder with build results).
Note: the drawback of the chosen solution is that we will have 2 identical `build.sh` files. We can think how to resolve this iteratively.
closes #

fix docker build context

---

connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/AwsUtils.java
connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/LambdaConnectorFunction.java
connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/model/FunctionRequestData.java
connectors/aws/aws-sns/element-templates/aws-sns-connector.json
connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/outbound/SnsConnectorFunction.java
connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/outbound/model/TopicRequestData.java
connectors/aws/aws-sns/src/test/resources/requests/fail-test-cases.json
connectors/aws/aws-sns/src/test/resources/requests/success-test-cases.json
connectors/aws/aws-sqs/element-templates/aws-sqs-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/model/SqsInboundQueueProperties.java
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/outbound/SqsConnectorFunction.java
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/outbound/model/QueueRequestData.java
connectors/aws/aws-sqs/src/test/resources/requests/inbound/success-test-cases.json
connectors/aws/aws-sqs/src/test/resources/requests/outbound/fail-test-cases.json
connectors/aws/aws-sqs/src/test/resources/requests/outbound/success-test-cases.json

Introduce a backwards compatible layer for the previously used connector request config that maps to the new AWSBaseRequest based config.
https://github.com/camunda/connectors-bundle/issues/673

feat(aws): standardize region input property

---

bundle/default-bundle/README.md
bundle/default-bundle/src/test/java/io/camunda/coonnector/runtime/app/LocalConnectorRuntime.java
connectors/README.md

Adds an alternative simple way to run the runtime locally, as previously used main class was deleted.
closes #

fix: restore local connector runtime in the default bundle

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java

During the latest refactoring, this small regression was introduced. When we scanned elements to create connector instances, we failed to detect that an element is in fact not a connector, and attempted to create a connector from it, which resulted in a downstream exception.

fix(inbound): silently skip elements that are not connectors

---

connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java

Fixes this behavior when serializing `Optional`:
closes #

fix(webhook): enable correct optional type serialization

---

connectors/connectors-common-library/pom.xml
connectors/connectors-common-library/src/main/java/io/camunda/connector/common/services/HTTPProxyService.java

Sending a request with an empty body via REST connector results in the following body received by webhook.site:
This is due to a missing Jackson Scala module: FEEL expression gets deserialized as some kind of special Scala map implementation that can't be handled properly by default in Jackson. This is only reproducible when running with a proxy function.
closes #

fix(rest): add necessary jackson modules to http proxy service

---

connectors/rabbitmq/element-templates/rabbitmq-outbound-connector.json

We force this field to be a FEEL expression, but provide the default value without `=`. Web modeler does not implicitly add an equals sign, and we can't deserialize the properties into an object because it arrives to us as a string.
closes #

fix(rabbitmq): edit default properties value to start from '='

---

connectors/kafka/pom.xml
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunction.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/integration/KafkaIntegrationTest.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunctionTest.java

Bug was found in Kafka serialization, which had to be fixed.  Now it converts FEEL expression (which represented as a scala Map) properly to json.

fix kafka value serialization; change group id property to include elementId and processDefinitionKey

---

connectors/connectors-common-library/pom.xml
connectors/google/google-base/pom.xml
connectors/kafka/pom.xml
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunction.java
connectors/microsoft-teams/pom.xml
connectors/microsoft-teams/src/main/java/io/camunda/connector/suppliers/ObjectMapperSupplier.java
connectors/microsoft-teams/src/test/java/io/camunda/connector/model/request/chat/GetChatTest.java
connectors/pom.xml
connectors/rabbitmq/pom.xml
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/common/model/RabbitMqMessage.java
connectors/slack/src/main/java/io/camunda/connector/slack/inbound/suppliers/ObjectMapperSupplier.java
connectors/webhook/src/main/java/io/camunda/connector/inbound/utils/ObjectMapperSupplier.java

With the recent issues we encountered in several connectors due to missing modules, it makes sense to have the same object mapper config everywhere.
closes #

Standardize jackson configuration

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java

Sometimes we threw a `java.lang.IllegalStateException: Sanity check failed: IntermediateCatchEvent` unnecessary which caused issues.
In the fix we filter the elements to only check those elements which actually have an inbound template applied.

fix: filter inbound eligible elements before performing 'sanity check'

---

connectors/webhook/src/main/java/io/camunda/connector/inbound/authorization/WebhookAuthChecker.java
connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java

GitHub connector or old webhook connectors can fail if there is no auth.

fix: add default value for auth to prevent errors with old deployments

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/app/TestWebhookConnector.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/inbound/SnsWebhookExecutable.java
connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/inbound/model/SnsWebhookProcessingResult.java
connectors/slack/README.md
connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java
connectors/slack/src/main/java/io/camunda/connector/slack/inbound/model/SlackWebhookProcessingResult.java
connectors/slack/src/test/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutableTest.java
connectors/webhook/element-templates/webhook-connector-intermediate.json
connectors/webhook/element-templates/webhook-connector-start-event.json
connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java
connectors/webhook/src/main/java/io/camunda/connector/inbound/authorization/WebhookAuthChecker.java
connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java
connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookProcessingResultImpl.java
connectors/webhook/src/test/java/io/camunda/connector/inbound/HttpWebhookExecutableTest.java
connectors/webhook/src/test/java/io/camunda/connector/inbound/authorization/JWTIntegrationTest.java
connectors/webhook/src/test/java/io/camunda/connector/inbound/signature/HMACTwilioSignatureTest.java

feat: introduce request body expression
Changes from previous PR:
- exposed post-processing function
- now, if response body expression not defined, returning nothing
- to return correlation data, user has to use `correlation` variable: `=if ... then correlation else ...` or `=if ... then {correlationResult: correlation} else ...`
- Failing due to expected changes https://github.com/camunda/connector-sdk/pull/531 are not there yet.
- https://github.com/camunda/connectors-bundle/pull/902 is still compatible
`responseBodyExpression=<none>`
```
curl -X GET "http://localhost:8080/inbound/test00?hub.mode=subscribe&hub.challenge=12345" -vvv
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET …
```

feat: introduce request body expression

---

connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java

fix(webhook): backwards compatibility support of method
This fix ensures backwards compatibility with old connector element templates.

fix(webhook): backwards compatibility support of method

---

bundle/camunda-saas-bundle/pom.xml
bundle/pom.xml
connector-runtime/connector-runtime-core/pom.xml
connector-runtime/connector-runtime-spring/pom.xml
connector-runtime/spring-boot-starter-camunda-connectors/pom.xml
parent/pom.xml

There was a logging dependency conflict after the SDK merge that resulted in no logs being displayed in the runtime bundle. The root cause was introduced by overriding the `slf4j` version in the parent pom which conflicted with the version from spring boot bom.
closes #

fix: resolve logging dependency conflicts

---

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorProperties.java

Add the `@FEEL` annotation to Kafka additional properties to handle JSON and FEEL mappings.
related to #983

fix: support FEEL for Kafka additional properties

---

.github/workflows/RELEASE.yaml

Adjust the version bump step to take the new project structure into account (parent is now not in the root dir)

fix(build): adjust project version bump step in the release pipeline

---

bundle/camunda-saas-bundle/src/main/resources/application.properties
connector-runtime/connector-runtime-application/src/main/resources/application.properties
connector-runtime/spring-boot-starter-camunda-connectors/README.md
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/InboundConnectorsAutoConfiguration.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/resources/application.properties
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/OperateClientAvailabilityTest.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/resources/application.properties

This is somewhat messy, but does the job.
[`OperateClientAutoConfiguration`](https://github.com/camunda-community-hub/spring-zeebe/blob/main/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/OperateClientProdAutoConfiguration.java) defined in Spring Zeebe is actually not an auto configuration, it's just a regular configuration, despite its name. It has a `@ConditionalOnProperty` on `operate.client.enabled`. We can't just change this behavior in spring-boot-starter-camunda (I expect that many people rely on it), so we have to override it manually.
closes #918

chore: configure operate client to be always enabled

---

connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/InboundConnectorsAutoConfiguration.java

Turns out `OperateClientProdAutoConfiguration` is actually not an auto configuration in Spring Zeebe (despite the name), so the ordering annotations didn't work properly.

Operate client fix

---

connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java
connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java

Avoid exposing scala maps outside of `FeelEngineWrapper`.

fix: sanitize scala map output

---

connectors/whatsapp/element-templates/whatsapp-connector.json

Support WhatsApp message templates.

feat(whatsapp): update element template to support message templates

---

connector-sdk/element-template-generator/pom.xml
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/BooleanProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/BpmnType.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/DropdownProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/ElementTemplateCategory.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/ElementTemplateSchema.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/HiddenProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplate.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplateBuilder.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/Property.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyBinding.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyBuilder.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyCondition.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyConstraints.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyGroup.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/StringProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/TargetElementType.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/TextProperty.java
connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/dsl/OutboundElementTemplateSerializationTest.java
connector-sdk/element-template-generator/src/test/resources/test-element-template.json
pom.xml

DSL for element template generation.
This common base code will be used to provide element template generation based on Java annotations and/or OpenAPI definitions.
closes https://github.com/camunda/team-connectors/issues/444

feat: define element template generator DSL

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorDefinitionImpl.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/InboundConnectorDefinitionImplTest.java

Because `rawProperties` were included into `toString`, sensitive data is potentially leaked (for example, when connector properties contains credentials).

fix: sanitize toString and json for inbound connector def impl

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java

Issue:
We query operate in the chunks of 20, and only process these 20 process definitions. Processing means activating any inbound connector in it. If you have more then 20 versions of a certain process definition, the application might activate an inbound connector which is not part of the latest version but a previous one. Even if we will override this (deactivate the old one and activate the new one) later, there is still a brief moment when we have the old version as an activated inbound connector, which may lead to unexpected behavior.
We first collect all the process definitions (not just 20), and only start extracting inbound connectors afterwards. This will result in only processing the latest process definitions as expected.
There is no related issue.
closes #

fix: collect all process definitions before extracting inbound connectors

---

connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/annotation/ElementTemplate.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/annotation/TemplateDiscriminatorProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/annotation/TemplateProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/OutboundElementTemplateGenerator.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/util/TemplatePropertiesUtil.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/DropdownProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/ElementTemplateCategory.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplate.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyBinding.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyCondition.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyGroup.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/StringProperty.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/TextProperty.java
connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/example/MyConnectorInput.java
connector-sdk/element-template-generator/src/test/resources/test-element-template-simplified.json
connector-sdk/element-template-generator/src/test/resources/test-element-template.json
connectors/http/http-base/pom.xml
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/Authentication.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/BasicAuthentication.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/BearerAuthentication.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/CustomAuthentication.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/NoAuthentication.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/OAuthAuthentication.java
connectors/http/rest/pom.xml
connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java
parent/pom.xml

Element template generator improvements based on testing with REST Connector.
- Support for custom nested path (using combination of disabling the `addNestedPath` param of `TemplateProperty`
- Improvements to how sealed hierarchies are recognized; now it's not necessary to add the `@TemplateSubType` annotation any more as sealed hierarchies are detected automatically.
- Refactoring of `@TemplateSubType`, a part of it related to discriminator was extracted to `@TemplateDiscriminatorProperty`, an optional annotation that can be placed on the hierarchy root.
- Visual / functional improvements of the generated template
- Set FEEL to optional by default
- Reorder property groups, handle a case where no custom groups were defined.
**Outcome**: the generator is able to provide a fully generated …

feat: template generator improvements

---

connectors/http/graphql/src/main/java/io/camunda/connector/http/graphql/GraphQLFunction.java
connectors/http/graphql/src/main/java/io/camunda/connector/http/graphql/utils/GraphQLRequestMapper.java
connectors/http/graphql/src/test/java/io/camunda/connector/http/graphql/BaseTest.java
connectors/http/graphql/src/test/java/io/camunda/connector/http/graphql/GraphQLFunctionInputValidationTest.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/constants/Constants.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpMethod.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpRequestBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/AuthenticationService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpInteractionService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpProxyService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpRequestMapper.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpService.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/BaseTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionInputValidationTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionProxyTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionSecretsTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpRequestMapperTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpServiceTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/auth/OAuthAuthenticationTest.java

Dont sent body for HTTP methods that dont support it (or are not supported by the underlying clients).
closes #1087

fix: Dont send body for GET requests

---

connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/ConnectorsObjectMapperSupplier.java
connectors/http/graphql/src/main/java/io/camunda/connector/http/graphql/GraphQLFunction.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpMethod.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpRequestBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/AuthenticationService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpProxyService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpRequestMapper.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/BaseTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionProxyTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpRequestMapperTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpServiceTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/auth/OAuthAuthenticationTest.java

Use upper case enums for http method consistency.

---

connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java
connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/OutboundTemplateGeneratorTest.java

As FEEL is set to "Optional" by default for all generated properties, it was automatically enabled for the result variable property too. But result variable is a Zeebe task header, so FEEL expressions are not evaluated there, and neither would it be evaluated in Connector Runtime. So it will be correct to disable FEEL for result variable.

fix(generator): disable feel for result variable

---

.github/workflows/RELEASE.yaml

Adjusts the release notes generation step:
- If pre-release, release notes should contain the difference between the current state and the previous tag, including other pre-releases. While releasing e.g. 0.23.0-alpha3, the diff will contain commits between 0.23.0-alpha2 and 0.23.0-alpha3.
- It not a pre-release, only the difference between the current state and the latest "normal" version is taken into account. For example, while releasing 0.23.0, the difference will contain the whole changelog between 0.22.1 and 0.23.0, no matter how many alpha/rc releases are in the middle.
closes #568

chore(build): improve release notes generation

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspectorUtilTests.java
connector-runtime/connector-runtime-spring/src/test/resources/bpmn/single-webhook-boundary.bpmn
connectors/aws/aws-sns/element-templates/aws-sns-inbound-boundary.json
connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
connectors/github/element-templates/github-webhook-connector-boundary.json
connectors/kafka/element-templates/kafka-inbound-connector-boundary.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-boundary.json
connectors/webhook/element-templates/webhook-connector-boundary.json

feat(connectors): add boundary events support
Tested the following:
- Kafka
- REST
- SQS

feat(connectors): add boundary events support

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspectorUtilTests.java
connector-runtime/connector-runtime-spring/src/test/resources/bpmn/single-kafka-consumer-subprocess.bpmn
connector-runtime/connector-runtime-spring/src/test/resources/bpmn/single-webhook-subprocess.bpmn

feat(connectors): added subprocess support

feat(connectors): added subprocess support

---

bundle/camunda-saas-bundle/Dockerfile
bundle/default-bundle/Dockerfile
bundle/default-bundle/Dockerfile-focal
bundle/default-bundle/start.sh

feat(bundle): add user-managed folder for mounting
Related to https://github.com/camunda/team-connectors/issues/496.
Pay attention at the argument `-v $PWD/connector-template-0.1.0-SNAPSHOT-with-dependencies.jar:/opt/additionalLibs/connector.jar`
```
~/W/t/custom-connector $ tree
.
└── connector-template-0.1.0-SNAPSHOT-with-dependencies.jar
1 directory, 1 file
~/W/t/custom-connector $ docker run --rm --name=HybridConnector -v $PWD/connector-template-0.1.0-SNAPSHOT-with-dependencies.jar:/opt/additionalLibs/connector.jar -e ZEEBE_CLIENT_SECURITY_PLAINTEXT=false -e ZEEBE_CLIENT_CLOUD_CLUSTER-ID='[REDACTED]' -e ZEEBE_CLIENT_CLOUD_CLIENT-ID='[REDACTED]' -e ZEEBE_CLIENT_CLOUD_CLIENT-SECRET='[REDACTED]' -e ZEEBE_CLIENT_CLOUD_REGION='bru-2' -e CAMUNDA_OPERATE_CLIENT_URL='[REDACTED]' -e …
```

feat(bundle): add user-managed folder for mounting

---

connectors/kafka/pom.xml

Bumps avro version, as `jackson-dataformat-avro` uses an outdated one with vulnerabilities.

fix(deps): bump avro version

---

connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/OutboundElementTemplateGenerator.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java
connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyBinding.java
connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/OutboundTemplateGeneratorTest.java

Adds retry properties to the template generator.
related to #1007

feat(generator): add retry properties to generated templates

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java

Due to this error, process definition upgrades were handled incorrectly: old version was not removed from the local storage and deletion handling was duplicated.

fix(importer): upgraded process definitions are not removed

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandlerTest.java

Correct arguments for `resolveMessageId` method in `InboundCorrelationHandler`
Added tests
https://github.com/camunda/team-connectors/issues/509

fix(InboundCorrelationHandler): fix resolveMessageId method

---

.github/workflows/CREATE_RELEASE_BRANCH.yml
.github/workflows/DEPLOY_SNAPSHOTS.yaml
.github/workflows/RELEASE.yaml
.github/workflows/TEST_FEATURE_BRANCH.yml

1. Disable tests on snapshot build, re-enable during release build
2. Run `mvn test` instead of `mvn verify` to speed up feature branch builds. This should save about 4 minutes on each feature branch build.
3. Adjust the release branch creation workflow to create a PR instead of pushing to main directly. This is needed to enforce proper branch protection for main (allow PRs only). Example PR (next snapshot version): https://github.com/camunda/connectors/pull/1254
4. Experimental: custom cache configuration to speed up workflow runs, using the [`restore-keys`](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) feature of the `cache` action. This should try to restore cache from other runs if the exact match is not found. This …

Release improvements

---

.github/workflows/RELEASE.yaml

Exclude `deps` commits from the changelog generated by our release action.

build: exclude deps from changelog

---

.github/workflows/CREATE_RELEASE_BRANCH.yml

When we create a release branch, we also want to update the version on main. However when we open a PR directly from the release branch, it is very easy to accidentally delete it after merging the PR. It is more convenient to open a PR from a temporary branch

build: create a version bump PR from a temporary branch

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/env/SpringEnvironmentSecretProvider.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/env/SpringEnvironmentSecretProviderTest.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ConnectorProperties.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/SpringEnvironmentSecretProviderTest.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/resources/application.properties

The Spring Environment Secret Provider has been adjusted to accept a prefix. This allows for easily narrowing down the environment that is accessible through the secret provider.
closes #1290

Allow configurable prefix for environment secret provider

---

connector-runtime/README.md

point to new Dockerfile example instead of archived repository
closes # 
https://github.com/camunda/connectors/issues/1307

Make README.md point to new Dockerfile example

---

connector-runtime/README.md

The configuration of Operate client was a bit misleading as users were trying to use the existing operate-client-id which has not access to operate-api read:* configured by default.
closes #

made operate client configuration clearer

---

.github/workflows/DEPLOY_SNAPSHOTS.yaml

Enable publishing SNAPSHOT images from feature branches.
Test run: https://github.com/camunda/connectors/actions/runs/6665221851

build: enable docker push for snapshot images on feature branches

---

element-template-generator/connectorgen-cli/pom.xml
element-template-generator/connectorgen-cli/src/main/java/io/camunda/connector/generator/cli/GeneratorServiceLoader.java
element-template-generator/connectorgen-cli/src/main/java/io/camunda/connector/generator/cli/command/ConnectorGen.java
element-template-generator/connectorgen-cli/src/main/java/io/camunda/connector/generator/cli/command/Generate.java
element-template-generator/connectorgen-cli/src/main/java/io/camunda/connector/generator/cli/command/Scan.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/api/CliCompatibleTemplateGenerator.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/api/GeneratorConfiguration.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGenerator.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundTemplateGeneratorTest.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilder.java
element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ElementTemplateGeneratorMojo.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiGenerationSource.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OperationParseResult.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OperationUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/ParameterUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/SecurityUtil.java
element-template-generator/openapi-parser/src/main/resources/META-INF/services/io.camunda.connector.generator.api.CliCompatibleTemplateGenerator
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ExampleTest.java
pom.xml

Introduces the element template generator CLI tool `connectorgen`
Features:
- Can work with any template generator that implements `CliCompatibleTemplateGenerator` interface (basically an extended version of `Element Template Generator`)
- Generators can be bundled with the tool via Java ServiceLoader
- Able to can the generation source to dry run the generation and list the supported operations, detailed reason is provided for each non-supported operation
- Configurable template name, id, version, hybrid support
Example usage:
1. `connectorgen scan openapi-outbound https://petstore3.swagger.io/api/v3/openapi.json`
Here, `openapi-outbound` is the generator name, followed by a source link
2. `connectorgen generate openapi-outbound https://petstore3.swagger.io/api/v3/openapi.json …

Template Generator CLI tool

---

connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/Health.java

Could not previously set details map on a unknown/down instance
closes #

Fix for not being able to set details on an UNKNOWN/DOWN Health instance

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplate.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplateBuilder.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyBuilder.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGenerator.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/ElementTemplate.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/OutboundElementTemplateSerializationTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/MyConnectorFunction.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/MyConnectorInput.java
element-template-generator/http/src/main/java/io/camunda/connector/generator/http/HttpOutboundElementTemplateBuilder.java

1 bug fix and 1 improvement for the element template generator API.
- Allow custom `elementType` and `appliesTo` for element templates on the DSL level and in the `@ElementTemplate` annotation.
- Support defining properties whose input binding name is not equal to property id. This is particularly useful for sealed hierarchies where there might be properties with the same name in different subtypes.
related to https://github.com/camunda/connectors/issues/1342

fix(generator): allow configuring template in/out types, support different property id and binding

---

bundle/README.md
bundle/camunda-saas-bundle/Dockerfile
bundle/camunda-saas-bundle/src/main/resources/banner.txt
bundle/default-bundle/Dockerfile
bundle/default-bundle/src/main/resources/banner.txt

- Added banner: addresses an issue to show current running version of connectors
- Added a volume, which is related to https://github.com/camunda/team-connectors/issues/525
- https://github.com/camunda/team-connectors/issues/525

chore: added banners and /tmp volume

---

parent/pom.xml

Upgrade `commons-text` dependency which require a new additional dependency as classes were relocated.
Relates to https://github.com/camunda/connectors/pull/1339

Upgrade commons-text including transitive dependency

---

README.md

Adds element template generator to the list of modules licensed under Apache 2.0.

docs: add template generator to the license list

---

.github/workflows/BACKPORT_PR.yml
README.md

This PR adds [backport-action](https://github.com/korthout/backport-action) to the repo. This should work as is, I'll give it a try after merging!
closes https://github.com/camunda/team-connectors/issues/540

build: add backport action

---

connectors/aws/aws-lambda/element-templates/aws-lambda-connector.json

fix(lambda): enforce payload to be mandatory
closes https://github.com/camunda/team-connectors/issues/533

fix(lambda): enforce payload to be mandatory

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorRestController.java
connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/InboundConnectorContext.java
connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java

The /inbound returned 500 error, because of class cast exception. This fix eliminates this error by using the more generic InboundConnectorExecutable instead of the InboundConnectorContextImpl.
closes #
https://github.com/camunda/connectors/issues/1364

fix(inbound): fix health report on /inbound endpoint

---

.github/workflows/RELEASE.yaml

This PR fixes a strange error I caught while running the release pipeline. The previous tag history was missing in the local repo although `actions/checkout` is configured with `fetch-depth=0` which should fetch everything.
The bullet-proof solution is to do `git pull --tags` right before using the tag history.
Also moved it further up in the pipeline to simplify debugging.
closes #

build: fix tag not found on release

---

element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOperation.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOperationBuilder.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpPathFeelBuilder.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java
element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilderTest.java
element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpPathFeelBuilderTest.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OperationUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/ParameterUtil.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ParameterUtilTest.java

This PR fixes several issues discovered while testing the OpenAPI generator.
| Issue description | Fix description |
|---|---|
| Request body could not be parsed when it was provided as a reference to the `Components` object  | Fetch body from components if ref is provided, see `OperationUtil::extractBodyExample`  |
| Inconsistent operation naming (sometimes method + path, sometimes description) | Use only method + path naming schema, as descriptions are inconsistent among different API providers |
| Examples for string parameters are falsely enclosed in quotes  | Fixed in `OperationUtil::extractBodyExample` |
| If path param contains a dash, it is treated by the FEEL engine as a minus sign  | Replace all dashes in path parameters with underscores, see `OperationUtil::extractPath` |
| …

fix(generator): various OpenAPI generator bugfixes

---

bundle/camunda-saas-bundle/Dockerfile
bundle/default-bundle/Dockerfile
connector-runtime/connector-runtime-application/Dockerfile

Using a non-numeric user and group ID in Dockerfile makes it harder to configure in K8s since it's not possible to detect if it's a root or non-root.
So we need to make that change to remove explicit config related to the user and group ID. 
**Please note that:**
- This change should be part of 8.4 and not part of 8.3.x release.
- I've also changed the GID to be the same as the UID (no particular need to have them different).
Related to: https://github.com/camunda/distribution/issues/122

refactor: change dockerfile uid and gid

---

element-template-generator/congen-cli/README.md
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/ReturnCodes.java
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/ConGen.java
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/Generate.java
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/ListGenerators.java
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/Scan.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/api/CliCompatibleTemplateGenerator.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplateBuilder.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpFeelBuilder.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOperation.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOperationBuilder.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOperationProperty.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java
element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpFeelBuilderTest.java
element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilderTest.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiGenerationSource.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/BodyUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/OperationUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/ParameterUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/SecurityUtil.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/BodyUtilTest.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ExampleTest.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ParameterUtilTest.java

- Adds `list` CLI command to output the available generators and their usage information (because it is not visible in the help page)
- Fix body example corner cases that caused the body example to remain undetected
- New body parsing mode that breaks down the body into individual fields (enabled by default for simple body objects or primitives, can be disabled with a CLI option)
- Support schemas without operation IDs (we generate our own ID in that case)
closes https://github.com/camunda/team-connectors/issues/549

feat: openapi generator improvements

---

element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiGenerationSource.java

Deploying snapshots from the main branch fails due to invalid javadoc comments.

build: broken javadoc for OpenApiGenerationSource

---

connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/model/request/auth/Authentication.java
connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/model/request/operation/OperationData.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/Authentication.java
element-template-generator/core/README.md
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/BooleanProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/DropdownProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/HiddenProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyBuilder.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/StringProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/TextProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/NestedProperties.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/DiscriminatorPropertyBuilder.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/MyConnectorInput.java

This PR introduces enhanced nested properties features for the annotation-based element template generator.
Previously it was impossible to wrap sealed hierarchies into sealed hierarchy subtypes. The new solution changes the way discriminator property IDs are treated by the generator: 
`@TemplateProperty` annotation was previously used to configure the `addNestedPath` feature (deciding whether path would be prefixed for nested properties). This was semantically incorrect: nested property containers are technically not properties, besides it was confusing that all the other fields of `@TemplateProperty`, like `id` or `label`, didn't cause any effects on the generated template.
The new approach utilizes a special annotation called `NestedProperties` that allows to configure only those …

feat(generator): Enhanced nested properties support

---

element-template-generator/congen-cli/README.md
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/Main.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpFeelBuilder.java
element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpFeelBuilderTest.java
element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilderTest.java
element-template-generator/openapi-parser/README.md
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/BodyUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/OperationUtil.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/BodyUtilTest.java

- `congen` was not configured to pass the unmatched properties to the generator
- `HttpFeelBuilder` did not support FEEL context expressions properly (only strings, which didn't work for complex body examples)

fix: openapi generator bugfixes + feel builder refactoring

---

element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/ParameterUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/SecurityUtil.java

This came up while checking our OpenAPI generator against Tasklist API.
- Multiple security schemes per security requirements were considered invalid (for no reason)
- Array json schemas were ignored if provided in `components` rather than directly inside parent schema.
- Authentication condition was invalid for parent authentication applied to the whole API

fix: support multiple security schemas in openapi security requirements

---

connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/model/request/auth/Authentication.java
connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/model/request/operation/OperationData.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/Authentication.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/DiscriminatorPropertyBuilder.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java

[Recent change](https://github.com/camunda/connectors/pull/1561) removed auto-prefixing of discriminator properties in generated element templates.
After discussing with @jonathanlukas we discovered it makes JSON mapping much less convenient (as connectors devs now need to add the nested path manually), so we agreed this functionality should be restored.

fix(generator): restore prefixes for template discriminator properties

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java

Handle null values when there are no processes found (previously it returned an empty list and we didn't have this issue)

fix(operate): deal with nulls from process definition search

---

connectors/google/google-sheets/element-templates/google-sheets-connector.json

Remove all length constraints on Google Sheets connector template fields.
The previous limits of 200 and 100 characters on `Value` and `Enter values` fields were preventing some otherwise valid FEEL queries from being used with this template.
The initial length constraints were added early in the Element Templates development process. Now, the team feels that (in general) templates should only apply length constraints when the API itself requires it. This is because:
- We can't always determine limits imposed by 3rd party systems
- 3rd party systems could change limits at any time
- We don't want to unnecessarily limit our customers where those limits aren't strictly needed
Although Camunda has a [4MB process instance payload size …

fix: remove length constraints on Google Sheets element template fields

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/operate/OperateClientAdapterImpl.java

After the Operate client upgrade, the calls can return nulls and we need to handle those explicitly.

fix(operate): handle nulls in process instance importing

---

bundle/camunda-saas-bundle/Dockerfile
bundle/default-bundle/Dockerfile
connector-runtime/connector-runtime-application/Dockerfile

Zeebe client occasionally tries to write the credentials cache file and fails resulting in errors in the logs. This started failing after we switched to running our containers as non-root.
More context in #1613 
closes #1613

fix(docker): set a custom location for zeebe credentials cache

---

.ci/preview-environments/argo/c8sm.yml
.ci/preview-environments/charts/c8sm/Chart.yaml
.ci/preview-environments/charts/c8sm/templates/_helpers.tpl
.ci/preview-environments/charts/c8sm/templates/certificate.yml
.ci/preview-environments/charts/c8sm/templates/ingress.yml
.ci/preview-environments/charts/c8sm/templates/ns.yml
.ci/preview-environments/charts/c8sm/templates/secrets.yml
.ci/preview-environments/charts/c8sm/templates/service.yml
.ci/preview-environments/charts/c8sm/values.yaml
.github/workflows/PREVIEW-ENV-CLEAN.yml
.github/workflows/PREVIEW-ENV-DEPLOY.yml
.github/workflows/PREVIEW-ENV-TEARDOWN.yml
.github/workflows/TEST_FEATURE_BRANCH.yml

Related to https://github.com/camunda/team-infrastructure/issues/510
This introduces a SelfManaged-like preview environment for Connectors that can be enabled on any PR by adding the `deploy-preview` label, and disabled by removing it.
Deployment manifests for the preview environment are defined in a Helm Chart, fully configurable via the [values.yml](https://github.com/camunda/connectors/blob/infra-gh-510-preview-environments/.ci/preview-environments/charts/c8sm/values.yaml) file. This Helm Chart leverages the [Camunda Platform Helm Chart](https://github.com/camunda/camunda-platform-helm), as well as the [infra-preview-environments-ingress Helm Chart](https://github.com/camunda/infra-preview-environments-ingress), maintained by infra, to enable an Okta-based authentication overlay on top …

chore: Add Preview Environments to Connectors

---

.ci/preview-environments/charts/c8sm/Chart.yaml

As of 10.01.2023 there has been a new release for the [preview-environments-ingress](https://github.com/camunda/infra-preview-environments-ingress?tab=readme-ov-file) helmchart. The version release is 1.4.0 and it is adding some changes which will allow displaying linking the argo cd preview environment and the specific harbor project url
https://github.com/camunda/team-infrastructure/issues/532

chore(ingress-chart): Update ingress chart version

---

README.md

The link was wrapped in a code block and wasn't rendered properly.

Fix broken link formatting in README

---

connector-runtime/connector-runtime-spring/pom.xml
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/metrics/ContextAwareLogbackMetrics.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ContextAwareLogbackMetricsAutoConfiguration.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/resources/META-INF/spring.factories
connector-runtime/spring-boot-starter-camunda-connectors/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

Replaces the default `LogbackMetrics` that come from `micrometer-core` with our custom copy. The only difference is that our custom implementation also provides logger name as a tag.
This will make the log counters filterable by logger name (which is almost always the class name).
Unfortunately most of the internal implementation of `LogbackMetrics` is package-private, so it turned out to be impossible to make use of the inheritance in a proper way. The only purpose of the inheritance in this case is to replace a bean in the spring context.
closes https://github.com/camunda/team-connectors/issues/589

feat(metrics): add logger-aware logback metrics

---

element-template-generator/congen-cli/README.md
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/Generate.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/OperationUtil.java

1. Added a "target" prefix to all property IDs so they look like `operationId_body_propertyName` or `operationId_headers_propertyName`. Sometimes properties in body (derived from the JSON schema) can have the same name as parameters.
2. Fixed an issue with `scan` command where unsupported operations were never displayed
3. Changed the `generate` command output so it returns a single JSON object when only one template was generated, instead of an array of element template JSON objects.
4. Adjusted the README: removed the invalid example, added a note about unsupported operations.
See https://camunda.slack.com/archives/C0350959WG1/p1705053321728369

fix(generator): OpenAPI generator issues with Petstore example

---

connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java
connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/AbstractFeelDeserializer.java
connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelDeserializer.java
connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializer.java
connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelSupplierDeserializer.java
connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelDeserializerTest.java
connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java
connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelSupplierDeserializerTest.java

This PR replaces the temporary hotfix we had in place to fix the broken FEEL context aware deserialization.
To recap, the issue was that we are calling Jackson deserialization not only on `ObjectMapper`, but also on `ObjectReader` in case of the polling connector where we need to inject process variables into FEEL expression evaluation. We previously fetched the `ObjectMapper` instance from the deserialization context, but it turned out that Jackson doesn't necessarily return an `ObjectMapper`, but actually whatever was used to call the deserialization initially.
The proposed solution is to partially switch to lower-level APIs (such as `deserializationContext.readValue(...)`.
- The important part was to make sure that custom modules registered with the original object reader / mapper and …

fix(jackson): replace ObjectMapper with lower-level APIs in FEEL deserializers

---

.ci/preview-environments/argo/c8sm.yml
.ci/preview-environments/charts/c8sm/templates/certificate.yml
.ci/preview-environments/charts/c8sm/templates/ingress.yml

Related to https://github.com/camunda/team-infrastructure/issues/510
This PR introduces the use of a static name for the secret containing the TLS certificate of the preview environment.
Reasons:
- Using a dynamic name implies using a`*` in the ArgoCD `ignoreDifferences` configuration, which does not seem to be well supported as ArgoCD sometimes synchronizes the TLS secret (`tls.crt`, `tls.key`), whereas differences should be ignored
- When this happens, the TLS certificate of the preview environment is (removed) no longer exposed. Instead, a self-signed certifcat is temporarily used.

chore(preview-env): Use a static name for the TLS secret

---

connectors/automation-anywhere/element-templates/automation-anywhere-outbound-connector.json
connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/AutomationAnywhereConnector.java
connectors/http/rest/element-templates/http-json-connector-hybrid.json
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java

Version bumps for the generated connector templates due to significant changes:
- Switch to the new `taskDefinition` binding
- Added `retryCount`property

chore: bump versions of the auto-generated element templates

---

element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/ConGen.java
element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/Generate.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpFeelBuilder.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilder.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/OperationUtil.java

- Improved help command output for configuration parameters
- Fixed a couple newly discovered bugs found while experimenting with generating multiple templates at once for different element types:
- non-idempotent `FeelContextBuilder.build()`
- unformatted output when only one element template is returned
- extra call to `appliesTo()` with the hard-coded value`bpmn:Task`, not needed anymore since we set this value in a different place now.

fix(generator): ConGen - improve help, fix multi-template bugs

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java

There was a bug in the webhook connector registration code: we attempted to deregister a webhook connector that was not registered due to a conflicting webhook endpoint path.
Consider the scenario:
- A process (`P1`) is deployed containing a webhook connector with path `myPath`. It is successfully registered with `WebhookConnectorRegistry`.
- We attempt to deploy another process (`P2`) that contains a webhook connector with the same path, `myPath`.
- This results in an error during registration, because this path is already used. This is checked in `webhookConnectorRegistry::register`.
- We make a change to `P2` and try to deploy a newer version
- Process definition for the previous version of `P2` is registered
- We know it contained a webhook connector, so we try to deactivate it
- In …

fix(webhook): inconsistent webhook de-registration

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/NestedProperties.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/MyConnectorInput.java

2 improvements to the java-based element template generator:
1. Support defining groups for nested properties, which comes in handy when the whole nested input should be part of the same group.
2. Support overriding property binidng name. By default, field name is used, but we allow overriding the name. Implemented as a nested annotation in case we decide to allow overriding the binding type too at some point (but it doesn't make sense to allow this as of now).

feat(generator): support group definition for nested properties and binding name override

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java
connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java

Added a general health report logic, which reports the webhook connector health as UP, if it is still in unknown state. This happens after the activate method call, so we can be sure that at this point the connector must be up unless the status is set to DOWN.
Also added an error logging for Feel exceptions to show those on the FE. This way users have a feedback about the error happened.
closes #
https://github.com/camunda/connectors/issues/1799

fix(health report): add general health report and feel exception logging for webhooks

---

parent/pom.xml

Bump spring-zeebe version to 8.4.1-rc2 (includes OIDC support).

chore(deps) bump spring zeebe to 8.4.1-rc2

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorValidationUtil.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerLogTest.java

Update webhook deprecated path warning tag to "Warning" instead of "Warn".
After discussion with @YanaSegal , we felt this would be the better tag name. Further UX suggestions we discussed would require `web-modeler` changes and a separate issue.
[[Bug](https://github.com/camunda/connectors/issues/1238)

fix(webhook): update tag from Warn to Warning

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java

Backports #1774 to 8.3 (bug with duplicate webhook ID deactivation)
I had to cherry pick this one manually due to conflicts.

Backport 1774 to release/8.3

---

bundle/default-bundle/src/test/resources/application.properties
connector-runtime/README.md
connector-runtime/connector-runtime-application/src/main/resources/application.properties

- Removed operate auth properties from the `connector-runtime-application` module (this affected the docker image)
- Updated README with an example of new Identity config
- Added config for `LocalConnectorRuntime`

chore(identity): switch to new identity config

---

connectors/webhook/element-templates/webhook-connector-boundary.json
connectors/webhook/element-templates/webhook-connector-intermediate.json
connectors/webhook/element-templates/webhook-connector-start-event.json
connectors/webhook/element-templates/webhook-connector-start-message.json

Use more concise error message in webhook element templates.
Previous message was much longer than other template error messages.
Follow up from https://github.com/camunda/team-connectors/issues/599

fix(webhook): user shorter webhook ID validation message

---

connectors/slack/element-templates/slack-connector.json
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ChatPostMessageData.java
connectors/slack/src/test/java/io/camunda/connector/slack/outbound/model/ChatPostMessageDataTest.java
connectors/slack/src/test/resources/requests/test-cases/validate-fields-fail.json

feat(slack): add block content message support
closes https://github.com/camunda/team-connectors/issues/584

feat(slack): add block content message support

---

.github/workflows/RELEASE.yaml

- We have recently discovered that CI tests on release branches sometimes show inconsistent results compared to main / other feature branches
- It is likely that the issues were caused by version mismatches, when different pom files in the project have different versions, which can be caused by backporting (i.e. cherry-picking commits from the main branch where the version already differs from the release branch).
- Such mismatches can be hard to detect because they don't affect the following releases (release workflow sets the version on its own), but tend to complicate things for the release manager.
- This PR adds a step to our release workflow to update the release branch and set the new version. This should help prevent such mismatches in the future, as the version in the release …

build(release): add a step to update version in the release branch

---

connector-sdk/core/pom.xml
connector-sdk/feel-wrapper/pom.xml
connector-sdk/jackson-datatype-feel/pom.xml
connector-sdk/pom.xml
connector-sdk/test/pom.xml
connector-sdk/validation/pom.xml
parent/pom.xml
pom.xml

This PR re-introduces Java 17 support for the Connector SDK modules.
closes #1936

chore: support Java 17 for Connector SDK

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/MyConnectorInput.java

Property type override was not applied to composite/container types. This lead to classes such as `Date` being always interpreted as container types no matter which property type is specified by the user in `@TemplateProperty(type=...)`.
Also:
- `LocalDate` and other Java 8 date/time types are implicitly mapped to `String` properties
- Improved handling of StackOverflowError for misconfigured container types
- Format changes for better readability
closes #1948

fix(generator): property type override via annotation

---

element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java

Tests were failing on my local windows machine, because of path issues. I refactored the tests so now they can run on windows as well.

chore: refactor connector template generator tests to make it compatible with windows

---

connectors/webhook/pom.xml
parent/pom.xml

We have to update [nimbus-jose-jwt](https://mvnrepository.com/artifact/com.nimbusds/nimbus-jose-jwt) version because of security reasons.

chore: update nimbus-jose-jwt version

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java
connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java
connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapperUtil.java
connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java
connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperUtilTest.java

Right now, the job context is wrapped to the response context, leading to the jobs' retries being available as `response.job.retries` which is not valid.
This PR fixes this (documented and tested) so that only the FIRST element of the varArgs for an evaluation is considered to be the response and wrapped into a response context.
nothing to close

FeelEngineWrapper: only wrap the actual response to the response context

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/MyConnectorInput.java

Adds a way to define property constraints in `@TemplateProperty` instead of using Java bean validation API annotations.
Context: https://camunda.slack.com/archives/C0350959WG1/p1708515841961049

feat(generator): support constraints in @TemplateProperty

---

parent/pom.xml

Configures maven-enforcer-plugin to check for snapshot dependencies during release builds (only when `sonatype-oss-release` profile is active)
closes #1968

build: enforce no snapshots on release

---

renovate.json

We should exclude our own (same repository) artifacts from renovate:
https://github.com/camunda/connectors/pull/1941
https://github.com/camunda/connectors/pull/1940

Exclude version updates of own artifacts

---

connectors/http/polling/src/main/java/io/camunda/connector/http/polling/task/HttpRequestTask.java

Added an activity log with error severity when property binding fails.
https://github.com/camunda/team-connectors/issues/587
closes https://github.com/camunda/team-connectors/issues/587

feat(polling): add activity log in case of binding exception in polling connector

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java

An addition to #1956, one more exception should be handled as invalid connector definition
closes #1955

fix(importer): handle missing required properties as invalid connector definition exception

---

connectors-e2e-test/connectors-e2e-test-kafka/pom.xml
connectors/soap/src/test/java/io/camunda/connectors/soap/xml/XmlToJsonMapperTest.java
connectors/webhook/pom.xml
parent/pom.xml

Specified the version of commons-compress and nimbus-jose-jwt dependencies as a fix for CWE-835 and CWE-770. The consequence of this was that I had to specify the commons-codec version for kafka e2e test. 
Also slightly modified soap connector test, because it was failing on my machine. I changed the comparison of xmls to ignore the CR chars. This might be a windows related issue, and has no impact on the test quality and coverage.

Fix CWE 770 and CWE 835

---

connectors-e2e-test/connectors-e2e-test-kafka/pom.xml
connectors/webhook/pom.xml
parent/pom.xml

* chore(dependency): specify commons-compress and nimbus-jose-jwt version
* fix: add missing commons-codec dependency
(cherry picked from commit 81369e034d630dbae513c5a79387ae35721f0f4e)

Fix CWE 770 and CWE 835 (#2029)

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/components/HttpTransportComponentSupplier.java

The HttpTransport of the HttpBase has been configured to use `SO_KEEPALIVE`.
The desired effect is that a long-running http call will not idle and eventually be closed by a gateway.
Reference: https://aws.amazon.com/blogs/networking-and-content-delivery/implementing-long-running-tcp-connections-within-vpc-networking/
closes #2049
>Special wish: I would like this to be backported to 8.4 to unblock progress of a project

http connector: use tcp socket timeout

---

connectors/openai/element-templates/openai-connector.json

This PR updates our **openai** connector:
- New `temperature` field
- with a validation, the value must be between 0 and 2 (floats are ok) according to their [documentation](https://platform.openai.com/docs/api-reference/chat/create#chat-create-temperature)
- New **Custom** entry in the models dropdown.
- When **Custom** is selected a new TextField appears, any value can be typed there
https://github.com/camunda/connectors/assets/1797846/b6cd2db8-c22b-47f2-a33c-c9b30652ed5b
closes #1959

feat(openai): Add a temperature input, Add the possibility to use a custom OpenAI model

---

connectors/webhook/element-templates/webhook-connector-boundary.json
connectors/webhook/element-templates/webhook-connector-intermediate.json
connectors/webhook/element-templates/webhook-connector-start-event.json
connectors/webhook/element-templates/webhook-connector-start-message.json
connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java

Fixes an error with the incorrect binding name (was `inbound.inbound.context` due to nested path resolution).

fix: incorrect context binding in wh element template

---

connectors/openai/element-templates/openai-connector.json

Fixes a bug where using an OpenAI Custom model would allow empty model values.
**Solution**
Added a new **notEmpty** constraint when this textfield is displayed.
Initial ticket is #1959 
Initial PR [here](https://github.com/camunda/connectors/pull/2053)

fix(openai): Add a NotEmpty constraint when using OpenAI Custom model

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java
connectors-e2e-test/connectors-e2e-test-automation-anywhere/src/test/java/io/camunda/connector/e2e/BaseAutomationAnywhereTest.java
connectors-e2e-test/connectors-e2e-test-aws/connectors-e2e-test-aws-base/src/test/java/io/camunda/connector/e2e/BaseAwsTest.java
connectors-e2e-test/connectors-e2e-test-easy-post/src/test/java/io/camunda/connector/e2e/BaseEasyPostTest.java
connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java
connectors-e2e-test/connectors-e2e-test-kafka/src/test/java/io/camunda/connector/e2e/BaseKafkaTest.java
connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/BaseRabbitMqTest.java
connectors-e2e-test/connectors-e2e-test-soap/src/test/java/io/camunda/connector/e2e/soap/SoapConnectorBaseTest.java

We need to filter out older process definitions versions at an earlier stage to prevent storing all process definitions in a list which may lead to an OOM error when there are too many processes deployed.
closes https://github.com/camunda/team-connectors/issues/647

fix(importer): prevent OOM by filtering out older process versions early on

---

.github/workflows/RELEASE.yaml

correct release run name;
should looks like before :

chore(workflow): update release run name

---

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java

Allow parsing properly unescaped control characters, to prevent parsing failures.
closes https://github.com/camunda/connectors/issues/1236

fix(kafka): fix deserialization of escaped characters

---

connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java

After backporting https://github.com/camunda/connectors/pull/2091 a test was failing. This commit fixes that test.

chore(kafka): fix broken kafka test after backport

---

connectors/webhook/element-templates/webhook-connector-boundary.json
connectors/webhook/element-templates/webhook-connector-intermediate.json
connectors/webhook/element-templates/webhook-connector-start-event.json
connectors/webhook/element-templates/webhook-connector-start-message.json
connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookAuthorization.java

Default value and constraint were missing after migrating to the auto-generated template.
Found during QA: https://github.com/camunda/team-connectors/issues/655

fix(webhook): missing default and constraint for the api key locator field

---

connectors/webhook/element-templates/webhook-connector-boundary.json
connectors/webhook/element-templates/webhook-connector-intermediate.json
connectors/webhook/element-templates/webhook-connector-start-message.json
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyGroup.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedTemplateGenerator.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/InboundClassBasedTemplateGeneratorTest.java

Fixes the issues found while testing the generated templates for boundary and message start events.
Also reorders property structure for generated inbound templates.
QA ticket: https://github.com/camunda/team-connectors/issues/655

fix(generator): reorder inbound correlation properties

---

connectors/http/rest/README.md

Add a remark that proxy mode is only supported in SaaS.
The actual support for SM installations should become available as part of https://github.com/camunda/connectors/issues/810

docs: mark proxy mode as only supported in saas

---

connectors/easy-post/element-templates/easy-post-connector.json

v5 was never released to customers.
v5 will not work with runtimes before 8.5.0.
We don't yet have a mechanism to inform customers which runtimes a template is supported by.
Because this template was only cleaning up technical debt and not introducing new features, we believe the best option is to not release a new version for now.
[See the discussion here](https://github.com/camunda/connectors/issues/1970#issuecomment-1997022685) for more details.
https://github.com/camunda/connectors/issues/1970

fix: revert to v4 EasyPost template

---

connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/model/SqsInboundQueueProperties.java

Increases the default polling wait time for SQS inbound connector, as we observed high CPU usage with small values of this parameter.

fix(sqs): increase polling wait time default to reduce cpu usage

---

connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java
connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java
connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java
connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java

Previously we [failed](https://github.com/camunda/connectors/blob/main/connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java#L102) when a variable was not convertible to a Map.
Instead of failing, we will now silently ignore variables that are not convertible. 
This will allow the connectors to return primitives, and the result is added to the [response](https://github.com/camunda/connectors/blob/5c1577352bf5c043dade881ecadae4d20e0e783c/connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapperUtil.java#L23) object.
closes #2098

fix(feel-wrapper): Handle primitive types in FEEL expressions

---

connectors/github/element-templates/github-connector.json

* Implements #2158
* Additionally fixes a small validation issue with the "SHA" field of the `References > Create a reference` operation where FEEL expressions were always marked as invalid.
* Changes the type of `prBody` from `String` to `Text` (see https://github.com/camunda/connectors/pull/2186/commits/8ae7f81418b48845e31280baa0154e2ebbec076e)
closes #2158

feat(github): get repository content

---

connectors/gitlab/element-templates/gitlab-connector.json

closes #2159, closes #2160, closes #2161, closes #2162

Outbound GitLab Connector enhancements

---

connectors/webhook/element-templates/webhook-connector-boundary.json
connectors/webhook/element-templates/webhook-connector-intermediate.json
connectors/webhook/element-templates/webhook-connector-start-event.json
connectors/webhook/element-templates/webhook-connector-start-message.json
connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java

Changes the property IDs of the webhook element templates that deviated from the original values after migrating to the template generator. This does not change the runtime behavior since binding names don't change, i.e. IDs are simply brought in accordance with bindings for clarity.

fix(webhook): adjust property IDs in the element templates

---

connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/model/impl/AwsBaseConfiguration.java
connectors/aws/aws-dynamodb/element-templates/aws-dynamodb-outbound-connector.json
connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-outbound-connector.json
connectors/aws/aws-lambda/element-templates/aws-lambda-outbound-connector.json
connectors/aws/aws-sns/element-templates/aws-sns-outbound-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-outbound-connector.json

chore(aws): force region as mandatory field in templates

chore(aws): force region as mandatory field in templates

---

.github/workflows/DEPLOY_SNAPSHOTS.yaml
.github/workflows/INTEGRATION_TEST.yml

- Removes run ID from the deployment identifier (it is added automatically for non-persistent runs)
- Adds a dependency between two parts of the snapshot workflow

ci: fix integration test GHA

---

element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ElementTemplateGeneratorMojo.java

On windows machines the generator used CRLF line endings instead of LF, so the generated files were all different. In this PR we specify the line endings explicitly, so it will be the same on Windows as well.

fix(generator): standardize line endings in generated element templates

---

connectors/slack/element-templates/slack-inbound-boundary.json
connectors/slack/element-templates/slack-inbound-intermediate.json
connectors/slack/element-templates/slack-inbound-message-start.json
connectors/slack/element-templates/slack-inbound-start-event.json
connectors/slack/pom.xml
connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java
connectors/slack/src/main/java/io/camunda/connector/slack/inbound/model/SlackWebhookProperties.java

chore(slack): migrate slack inbound to generator

chore(slack): migrate slack inbound to generator

---

connectors/rabbitmq/element-templates/hybrid/rabbitmq-outbound-connector-hybrid.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-boundary.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-intermediate.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-message-start.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-start-event.json
connectors/rabbitmq/element-templates/rabbitmq-outbound-connector.json
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/common/model/UriAuthentication.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/outbound/RabbitMqFunction.java

fix(rabbitmq): fix auth regex
Also related to https://github.com/camunda/web-modeler/pull/8943

fix(rabbitmq): fix auth regex

---

bundle/camunda-saas-bundle/Dockerfile

We had to update because of security concerns. 
https://jira.camunda.com/browse/SEC-983

chore(java-version): update java version in dockerfile

---

connectors/jdbc/pom.xml

Version was bumped globally in #2304 but there was a time gap between PR creation and merging where the JDBC connector merge has happened, so it was not included in that PR.

deps(jdbc): Bump connector snapshot version

---

connectors/microsoft/README.md
connectors/microsoft/azure-open-ai/element-templates/azure-open-ai-connector.json

feat(azure,openai): introduced Azure OpenAI prompt connector

feat(azure,openai): introduced Azure OpenAI prompt connector

---

connectors/sendgrid/pom.xml
connectors/soap/pom.xml
parent/pom.xml

Update org.bouncycastle dependency to v1.78 to fix [CVE-2024-30172](https://www.cve.org/CVERecord?id=CVE-2024-30172) vulnerability.

chore(deps): update org.bouncycastle dependency to v1.78

---

connectors/sendgrid/pom.xml
parent/pom.xml

Backport of https://github.com/camunda/connectors/pull/2317 to release/8.4.

[Backport release/8.4] chore(deps): update org.bouncycastle dependency to v1.78

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java

Fix for the incorrect comparison during webhook connector deactivation that resulted in webhooks never being properly deactivated.

fix(webhook): incorrect deactivation handling

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableRegistryImpl.java
connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/Health.java

Restores compatibility with web modeler's Problems tab by always returning an error object along with the health response. Additionally, the constructors that allow creating Health objects without an Error were removed.

fix(inbound): always return health objects with error set

---

bundle/default-bundle/src/test/resources/application.properties
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/PublishMessageCommandDummy.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/InboundConnectorsAutoConfiguration.java
parent/pom.xml

Changes to support Spring Zeebe 8.5.x, including the config property format.
Replaces the previous PR: https://github.com/camunda/connectors/pull/2344
closes #2313 #2343 #2346

chore: migrate to spring zeebe 8.5.1

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSOperateClientFactory.java
bundle/camunda-saas-bundle/src/main/resources/application.properties
bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/TestSpringContextStartup.java

Applies the necessary changes to run Connectors in SaaS with the latest Spring Zeebe version.
closes https://github.com/camunda/team-connectors/issues/751

fix(saas): apply new operate config

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundConnectorRestController.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundEndpointTest.java

The type check was invalid and didn't account for subclasses, which lead to missing `data.path` in the `/inbound` endpoint response for webhook connectors.

fix(webhook): incorrect type check resulting in missing return data

---

connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundEndpointTest.java

Previous constructor signature was only available in main with [configurable TTL](https://github.com/camunda/connectors/pull/2341), which will not be part of release/8.6.
closes #

test: fix test compilation errors on release/8.6

---

connectors/jdbc/pom.xml
connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/SupportedDatabase.java
connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionHelper.java
connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelper.java
connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionStringHelper.java
connectors/jdbc/src/test/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelperTest.java

We can't use GPL license, so we needed to replace the MySQL connector with the compatible MariaDb connector.
This won't change anything for our end users, and to accomplish that we needed to handle the compatibility part for them.
Thus we are adding the `permitMysqlScheme` at the end of the connection string.
Note that we still need the MySQL connector for our tests, as _testcontainers_ is looking for this driver to start a MySQL server.

feat(jdbc): Remove MySQL ConnectorJ and use MariaDb instead

---

connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelper.java

Test file is not accessible from source code. This causes the RC build to fail.

fix(jdbc): Fix invalid Javadoc comment

---

connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionHelper.java
connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelper.java
connectors/jdbc/src/test/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelperTest.java

Previously I used a `URI` to get some specific part of the provided database URL.
But:
- it didn't provide anything as the scheme (jdbc:xxx) is not properly detected, so we can't get the query parameters anyway
- it cause an issue when a URL parameter contains a hash (#) it ignores what is after this hash

feat(jdbc): Don't use URI as it breaks when using the hash char

---

.github/workflows/INTEGRATION_TEST.yml
.github/workflows/RELEASE.yaml

target_commitish only exists when tag doesn't exist already when the release is created.
While this is often useful, there are times when the tag already exists.
For example, if someone edits an existing release instead of creates a new one. Or if the GitHub release needs to be re-created for some reason.
To help clarify that this will not publish the artifact directly to the public - an additional step is needed as documented internally.
This is more complicated than expected. We will address this in a separate issue and PR.
closes #

ci(release): support existing tag, clarify Maven staging

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java
connector-sdk/core/src/main/java/io/camunda/connector/api/error/ConnectorException.java
connector-sdk/core/src/main/java/io/camunda/connector/api/error/ConnectorExceptionBuilder.java

Add a possibility to pass custom variables when throwing a `ConnectorException`.
This is possible using the `ConnectorExceptionBuilder`.
This comes in the form of a `Map<String,Object>`.
closes https://github.com/camunda/team-connectors/issues/676

task(connector-exception): Add a possibility to pass custom variables to the ConnectorException

---

connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
connectors/aws/aws-sqs/pom.xml
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-boundary-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-intermediate-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-event-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-message-hybrid.json
connectors/kafka/element-templates/kafka-inbound-connector-boundary.json
connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json
connectors/kafka/element-templates/kafka-inbound-connector-start-event.json
connectors/kafka/element-templates/kafka-inbound-connector-start-message.json
connectors/kafka/pom.xml

This PR will enable acknowledgment config feature for SQS and Kafka connectors (already supported by the BE implementation of both connectors as part of #2333)
related to #2134

feat(sqs, kafka): enable acknowledgment config

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/BatchExecutableProcessor.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableRegistryImpl.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/state/ProcessStateStoreImpl.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorValidationUtil.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableRegistryTest.java

This PR will fix the following issues from 8.6.0-alpha1:
- Webhook connector not being able to recover from duplicate context path (see linked issue). Root cause was incorrect deactivation in `BatchExecutableProcessor:111`
- Unhandled exception in `WebhookConnectorValidationUtil:36` when webhook path is missing (rare find but still possible with an invalid / old element template)
- Unhandled exception when trying to delete a process that contains no inbound connectors, `ProcessStateStoreImpl:134`. Discovered in one of our alerts.
I also added a couple of tests for batch activation cases that check the correct batch activation / error handling logic.
related to https://github.com/camunda/connectors/issues/2565

fix(inbound-state-management): inbound state management bug fixes

---

.github/workflows/RELEASE.yaml

This PR will adjust branch detection script to account for (new?) output format of the git command we're running.
Previously we received only one string as an output of this `git branch` command, e.g. `release/8.6`.
Now the output looks like this:
```
(HEAD detached at 8.6.0-alpha2-rc1)
release/8.6
```
(i.e. head detached message was added)
Not sure where this change comes from but this should fix our release pipeline.

ci: adjust branch detection

---

.github/workflows/INTEGRATION_TEST.yml
.github/workflows/helm-git-refs.json

Follow up on https://github.com/camunda/connectors/pull/2530.
Previously, INTEGRATION_TEST.md would always pass in the default values. This works well for SNAPSHOT's.
However, for patches on minor versions (especially 8.3), the Helm integration tests need to be passed in dependencies that correspond to the that minor version.
This PR will:
- determine the correct connectors version to use based on the maven project version (if not provided)
- determine the correct Helm chart to use (i.e. Helm chart repository git ref)
- call the integration-test-template.yml with these inputs
ℹ️ Compared to the PR from @ev-codes (#2530), this approach should be simpler because it assumes that we don't need to provide the whole values file in `extraValues` when calling a custom Helm charts branch.
closes …

Helm integration tests for release branches

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/FieldProcessor.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/JakartaValidationFieldProcessor.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorInput.java

On template generation, there seems to be no way to have `constraints.notEmpty` being set to true.
However, this is currently required to achieve a field that has a regex for validation but may remain empty.
This PR enables this behaviour for template property fields and jakarta validation annotations on processing.
https://github.com/camunda/camunda-modeler/issues/4314#issuecomment-2134494119
closes #

Element Template generation: set notEmpty: false explicitly

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/FieldProcessor.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/JakartaValidationFieldProcessor.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorInput.java

* set notEmpty: false explicitly
* added tests
(cherry picked from commit 69eb232fa1bb51d005ce9462145f9e5c03a73bad)
#	element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/FieldProcessor.java #	element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java #	element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorInput.java
closes #

Element Template generation: set notEmpty: false explicitly (#2675)

---

connector-sdk/core/src/main/java/io/camunda/connector/api/document/BasicDocument.java
connector-sdk/core/src/main/java/io/camunda/connector/api/document/Document.java
connector-sdk/core/src/main/java/io/camunda/connector/api/document/DocumentContent.java
connector-sdk/core/src/main/java/io/camunda/connector/api/document/DocumentSource.java
connector-sdk/jackson-datatype-document/pom.xml
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/DocumentDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/DocumentSerializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/JacksonModuleDocument.java
connector-sdk/pom.xml

This is the first iteration of the document concept in the Connector SDK.
Changelist:
- `Document` class with content and metadata, content represented as byte array or base64 string
- Jackson serializer and deserializer for moving these documents through the FEEL engine
related to https://github.com/camunda/team-connectors/issues/784

feat(sdk): first iteration of document support

---

connectors/aws/aws-sagemaker/element-templates/aws-sagemaker-outbound-connector.json
connectors/aws/aws-sagemaker/element-templates/hybrid/aws-sagemaker-outbound-connector-hybrid.json
connectors/aws/aws-sagemaker/src/main/java/io/camunda/connector/sagemaker/SagemakerConnectorFunction.java

The documentation link is broken in the element template.
It's: https://docs.camunda.io/docs/next/components/connectors/out-of-the-box-connectors/aws-sagemaker/
It should be: https://docs.camunda.io/docs/next/components/connectors/out-of-the-box-connectors/amazon-sagemaker/
closes https://github.com/camunda/team-connectors/issues/800

fix(docs): Fix wrong documentation link

---

.github/workflows/INTEGRATION_TEST.yml
.github/workflows/helm-git-refs.json

The Helm integration test workflow we rely on ([`test-integration-template.yaml`](https://github.com/camunda/camunda-platform-helm/blob/main/.github/workflows/test-integration-template.yaml)) and camunda-platform-helm as a whole was recently refactored to rely on directories instead of branches for chart versions. [See issue for more context](https://github.com/camunda/team-connectors/issues/804)
This PR passes in the new required arguments. It also updates variable names and documentation to reflect the new directory system.
To help reviewers understand the changes, here's a [test run of this workflow that @ev-codes ran against Connectors v8.3.11](https://github.com/camunda/connectors/actions/runs/9416057521/job/25938368512)
closes https://github.com/camunda/team-connectors/issues/804

ci(integration): use new args for re-usable Helm integration test

---

.github/workflows/INTEGRATION_TEST.yml
.github/workflows/helm-git-refs.json

Backporting `INTEGRATION_TEST.yml` and `helm-git-refs.json` as they were after merge of https://github.com/camunda/connectors/pull/2728
Old arguments passed into test-integration-template will not work in a few weeks.
https://github.com/camunda/team-connectors/issues/804

ci(integration): use new Helm integration test arguments

---

connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/ObjectMapperSerializationTest.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/model/RabbitMqMessageProperties.java
parent/pom.xml

Bump spring-zeebe to 8.5.4
https://github.com/camunda/connectors/issues/2648

fix(deps): Bump spring-zeebe to 8.5.4

---

parent/pom.xml

To fix this issue: https://github.com/camunda-community-hub/spring-zeebe/issues/835

deps(spring-zeebe): Bump spring zeebe to 8.5.5

---

connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java
connectors/http/rest/src/test/resources/requests/fail-cases-connection-timeout-validation.json
connectors/http/rest/src/test/resources/requests/success-test-cases.json

Bump the REST Connector element template version.
Removes `writeTimeoutInSeconds` as it's not supported anymore by the connector.
https://github.com/camunda/connectors/issues/1069

chore(rest): Bump element template version

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java
connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java

Backport #2038 to release/8.3
related: https://github.com/camunda/team-connectors/issues/647

fix(importer): prevent OOM by filtering out older process versions eerly on

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json

- Add regex to validate timeouts, only numbers are allowed there.
closes https://github.com/camunda/team-connectors/issues/813

chore(rest): Add regex to allow integers only for timeouts

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/ProxyConfiguration.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java

- Add support for proxy using an env var containing the proxy URL (host+port).
We might add authentication later.
closes https://github.com/camunda/team-connectors/issues/699

feat(rest): Add proxy support

---

connector-runtime/README.md
secret-providers/gcp-secret-provider/README.md

Shells don't support hyphens or dashes in environment variables and will fail to export them. There are ways around this, but I'd not advertise those.
Kubernetes can deal with it but depends on the application within whether it can properly load those.
My origin of the change stems from the [manual setup](https://docs.camunda.io/docs/next/self-managed/setup/deploy/local/manual/) where one is typically running some form of shell and based on that the advertised conversion from `cluster-id` to `CLUSTER-ID` doesn't work.
Additionally, Spring boot has [relaxed binding rules](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#environment-variables) where hyphens are also ignored. Probably stems from shells typically not supporting those out of the box.
I'm not sure whether …

chore(readme): remove wrong env var hyphen usage

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentials.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentialsCache.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentialsCacheTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java

Adds a cache for the Cloud Function proxy credentials.
The current implementation allows for one cache per HttpService instance. The following connectors use this service:
- REST Connector
- GraphQL Connector
- Automation Anywhere Connector
- Polling Connector
closes https://github.com/camunda/connectors/issues/645

perf:(rest): Add cache for the Cloud Function proxy credentials

---

connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-boundary-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-intermediate-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-event-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-message-hybrid.json
connectors/kafka/element-templates/kafka-inbound-connector-boundary.json
connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json
connectors/kafka/element-templates/kafka-inbound-connector-start-event.json
connectors/kafka/element-templates/kafka-inbound-connector-start-message.json
connectors/rabbitmq/element-templates/hybrid/rabbitmq-inbound-connector-boundary-hybrid.json
connectors/rabbitmq/element-templates/hybrid/rabbitmq-inbound-connector-intermediate-hybrid.json
connectors/rabbitmq/element-templates/hybrid/rabbitmq-inbound-connector-message-start-hybrid.json
connectors/rabbitmq/element-templates/hybrid/rabbitmq-inbound-connector-start-event-hybrid.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-boundary.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-intermediate.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-message-start.json
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-start-event.json
connectors/webhook/element-templates/hybrid/webhook-connector-boundary-hybrid.json
connectors/webhook/element-templates/hybrid/webhook-connector-intermediate-hybrid.json
connectors/webhook/element-templates/hybrid/webhook-connector-start-event-hybrid.json
connectors/webhook/element-templates/hybrid/webhook-connector-start-message-hybrid.json
connectors/webhook/element-templates/webhook-connector-boundary.json
connectors/webhook/element-templates/webhook-connector-intermediate.json
connectors/webhook/element-templates/webhook-connector-start-event.json
connectors/webhook/element-templates/webhook-connector-start-message.json
connectors/webhook/pom.xml
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java

This PR changes the default setting of the acknowledgment configuration to "Acknowledge unmatched events by default" to restore the previous default behavior.
Also this feature is now enabled for the webhook connector.
closes https://github.com/camunda/connectors/issues/2596

fix(inbound): flip the acknowledgment config checkbox, enable it for webhook

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentials.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentialsCache.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentialsCacheTest.java

We can't get the Credentials for our Google Cloud Function.
This is due to a missing call to `refreshIfExpired`, as the credentials are not initialized by default.
Also added some refactoring, as we don't need these Optionals.
closes https://github.com/camunda/team-connectors/issues/816

fix(rest): Fix Cloud Function credentials initialization

---

connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json
connectors/slack/element-templates/slack-outbound-connector.json
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ChatPostMessageData.java
connectors/slack/src/test/java/io/camunda/connector/slack/BaseTest.java
connectors/slack/src/test/java/io/camunda/connector/slack/outbound/model/ChatPostMessageDataTest.java
connectors/slack/src/test/resources/requests/test-cases/execute-function-with-channel-name.json
connectors/slack/src/test/resources/requests/test-cases/execute-function-with-email.json
connectors/slack/src/test/resources/requests/test-cases/execute-function-with-username.json
connectors/slack/src/test/resources/requests/test-cases/replace-secrets.json
connectors/slack/src/test/resources/requests/test-cases/validate-fields-fail.json
connectors/slack/src/test/resources/requests/test-cases/with-wrong-method.json

Users were not able to create a new thread from an existing message or add a message to an existing thread. this solves the issues.
I added a new optional field to the slack outbound connector `thread` which takes the id of a message to start a thread from.
This id has to be gotten from the output mapping `message.ts` which contains the id of the posted message
There might be an issue in the future when an user wants to add messages (using camunda) inside a thread that has been create by a normal user (human), as I don't know how to retrieve the id.
closes https://github.com/camunda/team-connectors/issues/653

653 fr slack connector post message add option to post to an existing thread

---

.github/workflows/RELEASE.yaml

Backport release workflow changes
Previously, I thought the release workflow was always run from the release workflow on `main`.
However, it's now clear after this release that we need to backport this call into each release branch.
https://github.com/camunda/team-connectors/issues/764

ci(release): call Helm integration test from release workflow

---

.github/workflows/RELEASE.yaml

Backport release workflow changes
Previously, I thought the release workflow was always run from the release workflow on `main`.
However, it's now clear after the first July 2024 patches that we need to backport this call into each release branch.
https://github.com/camunda/team-connectors/issues/764

ci(release): call Helm integration test

---

connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookAuthorization.java

This PR defines the list of permitted subclasses of the webhook authentication interface explicitly. Previously it has been derived implicitly because subclasses were in the same file, but in the byte code the order was not fixed, which lead to flaky template generation results and auth option reordering in the element templates.

fix(webhook): specify permitted auth subclasses explicitly to stabilize template generation

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java

- Fix NPE with `readTimeoutInSeconds`
- Fix issue when we have multiple headers with the same name (Set Cookie for instance) => we'll keep only the first occurence.
closes https://github.com/camunda/team-connectors/issues/820

fix(rest): Fix NPE with readTimeoutInSeconds + Duplicate headers

---

connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/outbound/SnsConnectorFunction.java
connectors/aws/aws-sns/src/test/java/io/camunda/connector/sns/outbound/BaseTest.java
connectors/aws/aws-sns/src/test/java/io/camunda/connector/sns/outbound/SnsConnectorFunctionTest.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunction.java
connectors/kafka/src/test/resources/requests/success-test-cases.json
connectors/microsoft-teams/src/main/java/io/camunda/connector/operation/channel/SendMessageToChannelOperation.java
connectors/microsoft-teams/src/main/java/io/camunda/connector/operation/chat/SendMessageInChatChatOperation.java
connectors/microsoft-teams/src/test/java/io/camunda/connector/model/request/chat/SendMessageInChatTest.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/outbound/MessageUtil.java
connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/outbound/RabbitMqMessageTest.java
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ChatPostMessageData.java

When passing a JSON object as body for the rabbitMQ outbound connector, it is converted either to a `Map` or a `String`. 
When a `Map` was wrote as a Json, it was then unescaped.
This PR removes this feature.
We have to be sure it does not cause any weird side effect to remove this feature
closes https://github.com/camunda/connectors/issues/2730

feature-2730 fix the escaping feature for rabbitMQ outbound connector

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java

- When creating the Cloud Function request we didn't set any timeout, so we defaulted to HttpCommonRequest#DEFAULT_VALUE (20). We need to have an infinite timeout when calling the Cloud Function, as this is the function that will timeout.

Fix read timeout with cloud function

---

.ci/preview-environments/charts/c8sm/templates/secrets.yml
.ci/preview-environments/charts/c8sm/values.yaml

Related to https://github.com/camunda/team-infrastructure/issues/575
This PR introduces  pull secrets (`imagePullSecrets`) with a dedicated DockerHub account (credentials from Camunda's paid subscription) to ensure not to be affected by DockerHub rate limit when pulling images from DockerHub for preview environments.

chore(preview-env): add dockerhub pull secret

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestHeadersBuilder.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java

- Add support for `null` Content-Type.
closes #2813

fix(rest): Properly handle null Content-Type header

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestHeadersBuilder.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
connectors/twilio/element-templates/twilio-connector.json

We were looking for a `Content-Type` header in different places, but only with this specific case.
We now ignore the case.
closes #2820

fix(twilio): Fix content-type header issue when the case is inconsistent + fix element template

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestUriBuilder.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java

- Use the URI constructor that escapes the necessary parts
- Check for null values in form-encoded body before calling `String.valueOf`
closes https://github.com/camunda/team-connectors/issues/840

fix(rest): Fix missing path encoding in URLs

---

connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionTest.java
connectors/http/rest/src/test/resources/requests/fail-test-cases.json
connectors/http/rest/src/test/resources/requests/success-cases-connection-timeout-validation.json
connectors/http/rest/src/test/resources/requests/success-test-cases-api-key-headers.json
connectors/http/rest/src/test/resources/requests/success-test-cases-api-key-query.json
connectors/http/rest/src/test/resources/requests/success-test-cases-oauth.json
connectors/http/rest/src/test/resources/requests/success-test-cases.json

Simple modification to be able to run all TU in parallel.
full test can be ran in 1m50 instead of 16m
You can run test using `mvn clean install -T100`
Does not close anything, but allow big performance gains

refactor(test performance): modify test to be able to run them in parallel

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java

This ticket was pretty tricky cause those particular behavior are needed:
- `/inbound/*` `GET` `POST` `PUT` `DELETE` must not have any authentication system, and should not even read the authorization header
- `/inbound/*` `OPTIONS` `PATCH` `HEAD` must have an authentication system, and return 401 if the bearer is incorrect.
A new SecurityWebFilter had to be added as explained in this issue on spring-security repository https://github.com/spring-projects/spring-security/issues/14120
closes https://github.com/camunda/team-connectors/issues/642

642 fix spring security config

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestUriBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoder.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java

- Decode the URL before encoding it, to avoid double encoding if the provided URL was already encoded (that's a lot of encoding/decoding)
- Fix some potential issues with contentType headers cases (multipart, and formencoded).
closes https://github.com/camunda/team-connectors/issues/840

fix(rest): Ensure proper URL encoding + fix case issues with content type headers

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretApiClient.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/secret/ConsoleSecretProviderTest.java
parent/pom.xml

Bump version to 8.5.7
closes https://github.com/camunda/team-connectors/issues/815

chore(spring-zeebe) bump version of spring zeebe to 8.5.7

---

connectors-e2e-test/connectors-e2e-test-soap/src/test/java/io/camunda/connector/e2e/soap/SoapConnectorBaseTest.java
connectors-e2e-test/connectors-e2e-test-soap/src/test/java/io/camunda/connector/e2e/soap/SoapConnectorTests.java
connectors/soap/src/main/java/io/camunda/connectors/soap/SoapConnector.java

- Send the response body in case of a Fault 
- Some tests improvements
The body is accessible using this kind of `errorExpression`:
`if error.code="SOAP_FAULT_RECEIVED" then bpmnError("Code", "The code", error.variables) else null`
closes #2743

chore(soap): Send response body when a Fault is received

---

connectors/github/element-templates/github-connector.json

- Wrap `issueNumber` into a string 
closes https://github.com/camunda/team-connectors/issues/827

fix(github-connector): Issue number can now be either a String or an Int

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/JobHandlerContextTest.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/classexample/TestClass.java

Give a reliable error message to the user in case a json mapping throws an error
before was:
```
2024-06-24T01:51:43.958Z ERROR 1 --- [pool-2-thread-1] i.c.c.r.c.outbound.ConnectorJobHandler : Exception while processing job: 4503599627704641 for tenant:
io.camunda.connector.api.error.ConnectorException: Error during json mapping.
```
now it looks like
```
2024-07-05T16:38:09.648+02:00 ERROR 56519 --- [pool-1-thread-1] i.c.c.r.core.outbound.JobHandlerContext  : Could not resolve type id 'chat' as a subtype of `io.camunda.connector.slack.outbound.model.SlackRequestData`: known type ids = [chat.postMessage, conversations.create, conversations.invite] (for POJO property 'data')
```
closes https://github.com/camunda/connectors/issues/2805

fix(json-mapping): Json mapping now gives a reliable error message

---

bundle/default-bundle/src/test/resources/application.properties

add application.properties to be able to run connectors locally with docker compose (using docker-compose.core.yaml).

chore(config): add slim application.properties file to default-bundle

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java

Handle exceptions in imported process definitions explicitly to avoid setting the variable `ready` to false (in case of an exception in the handleImportedDefinitions), which indicates that connectors component is unhealthy.

fix(process-import): handle exceptions in imported process definitions explicitly

---

connectors/kafka/pom.xml
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
parent/pom.xml

Adds retries to the Kafka connector consumer loop.
Previously, when the consumer threw an exception, it just stopped processing until the process is redeployed. The new default is to retry this as long as the connector is active, with a backoff of 30 seconds.
closes #2750

Kafka connector loop retry

---

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/integration/KafkaIntegrationTest.java

This PR will fix the Kafka Integration test that has been failing since #2792 was merged.
- The test itself was adjusted to provide a custom retry policy, also a couple small errors were fixed in other test cases
- The consumer code now rethrows the exception when the retry loop fails (this shouldn't affect normal execution in production, as the retry loop is infinite there)
The test itself is marked as disabled, to be discussed whether we want to run it always.
closes https://github.com/camunda/team-connectors/issues/858

build: fix kafka connector integration test

---

connectors/google/google-sheets/element-templates/google-sheets-outbound-connector.json
connectors/google/google-sheets/element-templates/hybrid/google-sheets-outbound-connector-hybrid.json
connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/model/request/input/CreateRow.java

Fix a small issue found by @slolatte 
Now the row index field is restricted to either a FEEL expression, a number or empty String

other(google-sheets): add a constraint on row index

---

bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/LocalConnectorRuntime.java
bundle/default-bundle/src/test/resources/application-docker-core.properties
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/OffsetUpdateRequiredListener.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/integration/KafkaIntegrationTest.java

- Fix the way we handle consumerGroups
- The `assign` method that we used was overriding Kafka's consumer group mechanism (silently). We now use `subscribe` instead.
- Update the way we handle manual offsets.
- Update UTs.
closes #2846

fix(kafka): Handle consumerGroup properly + update the offset override part

---

connectors/kafka/pom.xml
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
parent/pom.xml

* fix(kafka): retry the main consumer loop with 30 seconds backoff
* reduce test wait duration
* lint
* switch to failsafe
* set number of retries to -1 (unlimited)
* use constant for retry number
* try fixing the integration test
* try fixing the integration test
* try fixing the integration test
* try fixing the integration test
* try fixing the integration test
* formatting
(cherry picked from commit 807071e2ae74a81e73d2689505a131e1cdd8bb7e)
closes #

fix(kafka): kafka connector loop retry (#2792)

---

.github/workflows/PREVIEW-ENV-DEPLOY.yml
.github/workflows/PREVIEW-ENV-TEARDOWN.yml

We integrated the "Deployment Summary" functionality into the preview-env deployments/teardowns.
Read more about it [here](https://github.com/camunda/infra-global-github-actions/tree/main/preview-env/comment)
* https://github.com/camunda/team-infrastructure/issues/459
* https://github.com/camunda/infra-global-github-actions/pull/228
closes https://github.com/camunda/team-infrastructure/issues/459

ci(preview-env): add deployment summary

---

connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json
connectors/slack/element-templates/slack-outbound-connector.json
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ConversationsInviteData.java
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/utils/DataLookupService.java
connectors/slack/src/test/java/io/camunda/connector/slack/outbound/model/ConversationsInviteDataTest.java

@sbuettner Should I implement the same choice for `postMessage` feature ?
add the option to use channel Id for inviting people inside a slack channel
https://github.com/camunda/connectors/issues/2695

feat(slack-connector) we can now use the channel Id for inviting people

---

connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/JdbiJdbcClientIntegrationTest.java

Tests were being flaky due to deprecated method being used
Not urgent, but some tests were becoming flaky in jdbc due to usage of deprecated method
None

fix(jdbc-tests): tests were being flaky due to deprecated method being used

---

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java

This PR will fix the issue with the Kafka connector retry loop. Previously, we didn't close the consumer properly before retrying, which resulted in longer waiting time before the new consumer could connect to the topic (it had to wait until the old consumer is killed by timeout).
related: #2750, #2792

fix(kafka): close consumer before retrying on failures

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/state/ProcessDefinitionInspector.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspectorUtilTests.java
connector-runtime/connector-runtime-spring/src/test/resources/bpmn/multi-webhook-start-message-duplicate-property.bpmn

a log (warning) is printed when a duplicate key is found inside a BPMN process, The duplicate value is ignored
closes https://github.com/camunda/connectors/issues/2939

other(bpmn-import): log warning when duplicate name is found inside process definition

---

connectors/aws/aws-sns/element-templates/aws-sns-inbound-start-event.json
connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/inbound/SnsWebhookExecutable.java
connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
connectors/kafka/element-templates/kafka-inbound-connector-start-event.json
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java
connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-start-event.json
connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java

We don't have a way to signal the et-generator plugin we want to deprecate a specific type of connector.
None start event will not be generated anymore for connectors:
- AWS SQS
- AWS SNS
- Kafka
- RabbitMQ
They will also be deleted from the web modeler.
I might need help from @sbuettner to remove them from the marketplace.
I noticed that AWS SNS implement `webhookconnectorExecutable`.  Should we still delete it as well?
closes https://github.com/camunda/team-connectors/issues/857

refactor(element-template): None start event are now deprecated

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java
connectors-e2e-test/connectors-e2e-test-http/src/test/resources/webhook_connector.bpmn

removing the value parameter in annotation.
Tested for message start and intermediate catch event successfully.
closes https://github.com/camunda/team-connectors/issues/876

fix(core) rest connector inbound was not working with query params

---

.github/workflows/BRANCH_NAME_CHECK_ON_PR.yml
.github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml

closes https://github.com/camunda/connectors/issues/3036

chore(ci): check on branch name

---

.github/workflows/PREVIEW-ENV-DEPLOY.yml
.github/workflows/check-pr-conflicts.yml

When pipelines/workflows don't run due to merge conflicts with the base branch, it's not always that obvious.
The newly introduced workflow will check for merge conflicts in PRs labeled `deploy-preview`.
Furthermore, we'll introduce a quick-cleanup in the `preview-env-deploy.yml` workflow, which will get rid of the comment as soon as the merge conflict got resolved.
* https://github.com/camunda/team-infrastructure/issues/566

chore(ci): introduce merge conflict comments

---

connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java
connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumerTest.java

This PR removes unnecessary unescaping from the RabbitMQ inbound connector.
closes #2730 
related PR: https://github.com/camunda/connectors/pull/2778
(fixed in 8.6 but not backported)

fix(rabbitmq): unnecessary unescaping in inbound connector

---

connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumerTest.java

This PR adds a test for the unnecessary unescaping scenario with RabbitMQ inbound connector. This test is already provided in #3135 for older release branches, but we also need to add it to main and 8.6.
closes #2730

test(rabbitmq): add test for unnecessary unescaping in inbound connector

---

parent/pom.xml

The release/8.3 branch was mistakenly upgraded Spring Boot to 3.2.9 instead of 3.3.3 [here](https://github.com/camunda/connectors/commit/9da000fbfb31efdd43a5399cc8a41e2aea6d2fd3), this PR will fix the issue.

fix(deps): upgrade spring boot to 3.3.3

---

bundle/default-bundle/src/test/resources/application-docker-core.properties

By default, we enabled multiple Runtime instances by setting the server port to a random value determined at Runtime.
This is not practical for different reasons:
- It's not often that we need multiple instances to test some feature
- APIs like /inbound are broken as one doesn't know the port soon enough
We will keep the previous value for this port (8080), and one can still uncomment this line if multiple instances are required.

chore(config): Disable multiple Runtime instance as the default

---

.github/workflows/INTEGRATION_TEST.yml
.github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml

Before this change, only the last-run Helm integration test would be allowed to finish.
The new commit types I added to [PULL_REQUEST_NAME_CHECK_ON_PR.yml](https://github.com/camunda/connectors/pull/3189/files#diff-92c7a74338bece2a9437a03beecb6a9cf913f4aa45e008aca0503a95237818fe) are currently recognized by our [release workflow](https://github.com/camunda/connectors/blob/main/.github/workflows/RELEASE.yaml#L244). So I think they should be allowed in our PR's.
closes https://github.com/camunda/connectors/issues/3188

ci(integration): use unique id to allow parallel Helm test runs, accept more commit types

---

.github/workflows/INTEGRATION_TEST.yml

Before this change, only the last-run Helm integration test would be allowed to finish.
related https://github.com/camunda/connectors/pull/3189

ci(integration): use unique id for parallel runs

---

connectors/aws/aws-textract/element-templates/aws-textract-outbound-connector.json
connectors/aws/aws-textract/element-templates/hybrid/aws-textract-outbound-connector-hybrid.json
connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/model/TextractRequestData.java

remove unnecessary fields which are displayed in modeler
[issue](https://github.com/camunda/connectors/issues/3196)

fix(textract): Textract unexpected modular fields

---

connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/serializer/DocumentSerializer.java
connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/DocumentSerializationTest.java

This PR fixes a bug because of which document references from the connector context were not serialized correctly.

fix(document): handle SDK document reference correctly in the serializer

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/model/HttpCommonRequestTest.java

- ReadTimeout doesn't exist in HttpCommonRequest before 8.5
- this causes issues with older REST Connectors in Saas, as the Cloud Function will try deserialize `readTimeoutInSeconds`, find nothing, and default to 20s.
- Before the REST connector rework, this value was copied from `connectionTimeout`
=> We are adding this behavior back, by default to:
- First: the `connectionTimeoutInSeconds` if provided 
- Second: 20s otherwise

fix(rest): Fix readTimeout for old runtimes before 8.5

---

connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/caller/PollingTextractCalller.java
connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/model/TextractTask.java
connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/caller/PollingTextractCalllerTest.java

Textract polling execution should assembly blocks into array
[issue](https://github.com/camunda/connectors/issues/3200)

fix(textract): polling exec should assembly block array

---

connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/model/SqsInboundQueueProperties.java

It prevents the user to enter a 0 polling time value.
That's a solution I can propose to resolve this issue https://github.com/camunda/team-connectors/issues/831
@sbuettner @chillleader What do you think?
closes https://github.com/camunda/team-connectors/issues/831 potentially

fix(sqs): Minor fix to prevent user from entering a 0 polling time which would result to CPU throtling.

---

element-template-generator/openapi-parser/pom.xml
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiGenerationSource.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ExampleTest.java
element-template-generator/openapi-parser/src/test/resources/example.yaml
element-template-generator/postman-collections-parser/pom.xml
element-template-generator/postman-collections-parser/src/main/java/io/camunda/connector/generator/postman/PostmanCollectionsGenerationSource.java
element-template-generator/postman-collections-parser/src/test/java/io/camunda/connector/generator/postman/PostmanCollectionsGeneratorDryRunExampleTest.java
element-template-generator/postman-collections-parser/src/test/resources/example.yaml

Added a check if the provided content is a valid yaml, and specific handling for that case. Did it for both openapi, and postman parser.
closes https://github.com/camunda/connectors/issues/3241

feat(element-template-generator): accept yaml content as parameter in template generator

---

bundle/camunda-saas-bundle/pom.xml
bundle/camunda-saas-bundle/src/main/resources/application.properties
bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java
bundle/default-bundle/src/test/resources/application.properties

Modify our provided `application.properties` files in the bundle.
Test changes:
- @ZeebeSpringTest and its dependency are needed for the `SecurityConfigurationTest` to consistently finish in CI. 
- I added 60s timeouts because if connection or read takes longer than this, the test should fail instead of waiting indefinitely.
closes https://github.com/camunda/connectors/issues/2844

feat(zeebe): enable job push by default in bundle

---

element-template-generator/core/pom.xml

We use the element template generator in web-modeler as a dependency. In web-modeler we do a license check.
[jcip-annotations](https://mvnrepository.com/artifact/net.jcip/jcip-annotations/1.0) doesn't have any valid license which causes issues in web-modeler.
Because we do not actually use this dependency I excluded it.
Added the 8.6.0 milestone because it is a small change without any impact, so we can include it in the next stable version, which would be beneficial for the web-modeler.

chore(deps): exclude jcip-annotations from podam dependency

---

parent/pom.xml

Increase the version of Identity SDK that comes from spring-zeebe transitively.

chore(deps): bump identity SDK to 8.5.5

---

connectors/kafka/element-templates/hybrid/kafka-inbound-connector-boundary-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-intermediate-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-message-hybrid.json
connectors/kafka/element-templates/hybrid/kafka-outbound-connector-hybrid.json
connectors/kafka/element-templates/kafka-inbound-connector-boundary.json
connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json
connectors/kafka/element-templates/kafka-inbound-connector-start-message.json
connectors/kafka/element-templates/kafka-outbound-connector.json
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorProperties.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/model/schema/AbstractSchemaRegistryStrategy.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunction.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/model/KafkaConnectorRequest.java

Some variables were not mapped because of the naming.
Related to:  https://github.com/camunda/team-connectors/issues/646

feat(schema-registry): Fix template variables names

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java

Set the `ready` property to true by default, so the health check passes when the container starts. This would avoid issues when loading definitions is super long.
closes https://github.com/camunda/team-connectors/issues/912

chore(inbound): Set the readiness to True when starting

---

renovate.json

Without this label, all Renovate PR's will fail PR check.
Dependency upgrades (especially ones handled by Renovate) clutter the release milestones more than clarifying them.
None

other(renovate): add no milestone label, include release 8.6

---

.github/workflows/RELEASE.yaml

We cannot add GitHub Action as an app that can force push to protected branches.
We would like to add more protections to release branches.
Our release workflow currently depends on the ability to force push.

ci(release): enable force push to protected release branches

---

element-template-generator/postman-collections-parser/src/main/java/io/camunda/connector/generator/postman/utils/PostmanPathUtil.java

Introduced a check on a null path, in that case return an empty collection so that the extractPathFromUrl method can succeed.
https://github.com/camunda/connectors/issues/3322
This PR is a replacement for https://github.com/camunda/connectors/pull/3323
closes #3322

fix(postman): replacement pr for 3322_NPE_when_empty_path_in_postman_collection 

---

CODEOWNERS

This allows Renovate to automatically merge upgrades that pass status checks.
As discussed in PR comments, it is not currently possible to add the `renovate-approve` bot (or any GitHub App) as a codeowner.

other(codeowners): exclude files Renovate often updates

---

.tool-versions
README.md

Updating these manually because Renovate will not do this automatically.
Java 17 is still used in the Connector SDK. I edited the README to reflect this since nested `asdf` tool-version files are not supported.
follow-up from https://github.com/camunda/team-connectors/issues/921

chore(tool-versions): use current Java, Maven versions

---

.github/workflows/RELEASE.yaml

Prevents commit loss when commits are added to the release branch while an RC is being created.

ci(release): use force-with-lease when pushing

---

CODEOWNERS

2nd backport of https://github.com/camunda/connectors/pull/3325
Original backport was overwritten by retrying releasing 8.6.0-rc3.

other(codeowners): exclude files Renovate often updates (#3325)

---

connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/model/SqsInboundQueueProperties.java
connectors/http/rest/README.md

These changes allow old SQS element templates to be used with the latest Connectors runtime
related https://github.com/camunda/team-connectors/issues/922

fix(sqs): remove pattern validation in runtime, add override description to template

---

.github/workflows/BACKPORT_PR.yml

PR's created with the GitHub Actions bot do not automatically trigger required status checks.
It's possible to trigger the checks manually, but this workflow should prevent the need to do that.
[More details on why this works](https://stackoverflow.com/a/69169858)

ci(backport-pr): use protected branch PAT

---

.github/workflows/RELEASE.yaml

Since we're only pushing a tag, this shouldn't delete commits
Even if someone adds commits in the meantime, we still want to move the release tag to the commit we have just pushed.
Without this change, we'll see a "rejected stale info" error in CI

ci(release): revert to force pushing release tag

---

parent/pom.xml

Our release workflow creates a commit that increments the version in each POM file. This commit also makes changes to README.md files that then cause Spotless checks to fail.
[Example](https://github.com/camunda/connectors/commit/9d97dc8d0a0ec1fcfb4e39fed98476da07571879#diff-e18079e36bc2ab8d1876469f92bab9b92065e0cdc94da9e0b9a91b3ef2c8a7aa)
Since the primary purpose of the Spotless checks is to make our code style more consistent, I think this change is worthwhile.
closes https://github.com/camunda/team-connectors/issues/930

chore(spotless): remove .md spotless checks

---

parent/pom.xml

Backport of #3384 to `release/8.4`.

[Backport release/8.4] chore(spotless): remove .md spotless checks

---

parent/pom.xml

Backport of #3384 to `release/8.3`.

[Backport release/8.3] chore(spotless): remove .md spotless checks

---

parent/pom.xml

Backport of #3384 to `release/8.5`.

[Backport release/8.5] chore(spotless): remove .md spotless checks

---

parent/pom.xml

Backport of #3384 to `release/8.6`.

[Backport release/8.6] chore(spotless): remove .md spotless checks

---

.github/workflows/RELEASE.yaml

Backport of #3380 to `release/8.6`.

[Backport release/8.6] ci(release): revert to force pushing release tag

---

.github/workflows/RELEASE.yaml

Manual backport of #3380 to `release/8.5`.

ci(release): force push release tag

---

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/JakartaEmailActionExecutor.java

Quick fix, the send email action will always fails if the mail cannot be sent
closes #

fix(email-connector): send emails will always make the process fail

---

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/JakartaEmailActionExecutor.java

Backport of #3394 to `release/8.6`.

[Backport release/8.6] fix(email-connector): send emails will always make the process fail

---

connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java

This PR adds a check on the SQS inbound connector startup to handle cases when the queue doesn't exist.
related #3405

fix(sqs): fail fast when queue does not exist

---

connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java

fix(sqs): fail fast when queue does not exist (#3415)

---

connectors/asana/element-templates/asana-connector.json
connectors/aws/aws-base/README.md
connectors/blue-prism/element-templates/blue-prism-connector.json
connectors/github/element-templates/github-connector.json
connectors/gitlab/element-templates/gitlab-connector.json
connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
connectors/hugging-face/element-templates/hugging-face-connector.json
connectors/openai/element-templates/openai-connector.json
connectors/operate/element-templates/operate-connector.json
connectors/salesforce/element-templates/salesforce-connector.json

Replace old deprecated binding by the new version of it.
Related to:  https://github.com/camunda/team-connectors/issues/927

chore(element-templates): Replace deprecated Zeebe binding by the new version

---

connectors/asana/element-templates/asana-connector.json
connectors/aws/aws-base/README.md
connectors/blue-prism/element-templates/blue-prism-connector.json
connectors/github/element-templates/github-connector.json
connectors/gitlab/element-templates/gitlab-connector.json
connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
connectors/hugging-face/element-templates/hugging-face-connector.json
connectors/openai/element-templates/openai-connector.json
connectors/operate/element-templates/operate-connector.json
connectors/salesforce/element-templates/salesforce-connector.json

Backport of #3416 to `release/8.6`.

[Backport release/8.6] chore(element-templates): Replace deprecated Zeebe binding by the new version

---

.github/workflows/BACKPORT_PR.yml

Backport fail comments often contain the text "/backport" as part of the branch name in suggested Git commands
closes https://github.com/camunda/team-connectors/issues/939

ci(backport-pr): prevent loop on backport fail

---

.github/workflows/helm-git-refs.json

`camunda-platform-latest` is [no longer supported](https://github.com/camunda/camunda-platform-helm/blob/dc8877d419a456b2ff671e448165b5ba3af3ac99/charts/camunda-platform-latest/README.md).
We should use `camunda-platform-8.6` instead.
related https://github.com/camunda/team-connectors/issues/943

ci(helm-git-refs): use new refs after 8.6 release

---

.github/workflows/helm-git-refs.json

Backport of #3468 to `release/8.6`.

[Backport release/8.6] ci(helm-git-refs): use new refs after 8.6 release

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentialsCache.java

- Catch exception when refreshing the OAuth token for the Cloud Function
- Add retry
- Log exception
closes [#932](https://github.com/camunda/team-connectors/issues/932)

fix(rest): Add retries and synchronize OAuth credentials init for the Cloud Function

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentialsCache.java

Backport of #3474 to `release/8.6`.

[Backport release/8.6] fix(rest): Add retries and synchronize OAuth credentials init for the Cloud Function

---

.ci/preview-environments/charts/c8sm/templates/ingress.yml
.ci/preview-environments/charts/c8sm/templates/service.yml
.ci/preview-environments/charts/c8sm/values.yaml

fix(preview-environments): Adapt to C8 Helm chart v11
The preview environments code has recently been upgraded to use Helm charts v11 (https://github.com/camunda/connectors/pull/3476), but no corresponding follow-up adjustments have been done to the code to conform to it (breaking changes in [v10](https://docs.camunda.io/docs/8.5/self-managed/setup/upgrade/#update-your-configuration), [v11](https://docs.camunda.io/docs/self-managed/setup/upgrade/#helm-chart-1100))
- The separate Camunda-developed Identity subchart is not existent since v10 and has been integrated natively into the chart
- `identity.keycloak` became `identityKeycloak` ([ref](https://docs.camunda.io/docs/8.5/self-managed/setup/upgrade/#update-your-configuration))
- `elasticsearch.host` is now `elasticsearch.url.host`
- …

fix(preview-environments): Adapt to C8 Helm chart v11

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java
bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundConnectorRestController.java

- New endpoint: `POST /inbound/logs` that will log the registered Inbound Connectors 
- Only accessible from Localhost even if not critical
closes [#931](https://github.com/camunda/team-connectors/issues/931)

chore(logs): Add an endpoint to publish inbound logs

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/state/ProcessStateStoreImpl.java

Adding logs during the importation of process definitions
This PR add logs tracing what is happening during the importation of the process definition from Operate.
closes https://github.com/camunda/connectors/issues/3190

others(operate-importer): add more logs during the import of process definitions

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorInput.java

This PR will add the missing property in the template generator annotations to create a condition that references a boolean property.
This possibility already exists on the lower level in the classes that are mapped to element template JSON, but it has been missing in the annotation.
An enum is used because we need to have a null/missing value, as the annotation can lead to different behavior of the generator based on which property is set.

fix(generator): boolean conditions in template generator annotations

---

connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java

Use a random port for WireMock so that you can have something running on 8080 locally.

chore(tests): Random port for Wiremock

---

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/BedrockCaller.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/LlmModel.java

- Added ability to have different system prompts based on `modelId` input.
- Refactored the call to AWS Bedrock to include a `system` message conditionally only for LLMs that support it.
closes https://github.com/camunda/connectors/issues/3572

feat(idp-extraction-connector): added compatibility with llms lacking system message support

---

connectors/email/element-templates/email-outbound-connector.json
connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json
connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java

closes https://github.com/camunda/connectors/issues/3640

chore(email-connector-headers): correct typo on ET

---

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java

When a exception was raised at consumption, a cancel event was sent
closes https://github.com/camunda/connectors/issues/3656

fix(email-connector): removing cancellation event when a exception is raised during email consumption

---

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java

Backport of #3657 to `release/8.6`.

[Backport release/8.6] fix(email-connector): removing cancellation event when a exception is raised during email consumption

---

connector-runtime/connector-runtime-core/pom.xml
connector-runtime/connector-runtime-spring/pom.xml
connectors-e2e-test/connectors-e2e-test-base/pom.xml
connectors/webhook/pom.xml
parent/pom.xml

The spring zeebe version is bumped to 8.5.11
Slack thread: https://camunda.slack.com/archives/C02JLRNQQ05/p1732195841890249?thread_ts=1727872562.192379&cid=C02JLRNQQ05
closes #

fix: use more recent spring zeebe version

---

connector-sdk/validation/src/main/java/io/camunda/connector/validation/impl/DefaultValidationProvider.java
connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/BaseEmailTest.java
connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/InboundEmailTest.java
connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/OutboundEmailTests.java
connectors/email/element-templates/email-outbound-connector.json
connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json
connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java
connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java
connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/ContentType.java
connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java
connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/JakartaExecutorTest.java

Adding a Dropdown to set the content type of an email so that html templates can be used in this email outbound connector.
Also set the right content type in the smtp send mail

feat(mail-connector): Adding Dropdown for Outbound Connector to switch content type between plain text and html

---

connectors/kafka/pom.xml

Critical modify avro version 8.3 previous versions allows bad actors to execute arbitrary code. Users are recommended to upgrade to version 1.11.4, which fix this issue.

fix(cve): Critical modify avro version 8.3

---

connectors/kafka/pom.xml

Schema parsing in the Java SDK of Apache Avro 1.11.3 and previous versions allows bad actors to execute arbitrary code. Users are recommended to upgrade to version 1.11.4, which fix this issue.

fix(cve): Critical modify avro version 8.4

---

connectors/kafka/pom.xml

Schema parsing in the Java SDK of Apache Avro 1.11.3 and previous versions allows bad actors to execute arbitrary code. Users are recommended to upgrade to version 1.11.4, which fix this issue.

fix(cve): Critical modify avro version 8.5

---

.github/workflows/BUILD_FEATURE_BRANCH.yaml

Split feature branch testing and docker image build workflows. This will allow faster deployment of preview env as we won't have to wait 1h until tests are executed.
closes #

chore(build): split testing and snapshot image build

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java
connector-sdk/feel-wrapper/pom.xml
connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/CustomValueMapper.java
connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java
connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/JacksonSupport.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/serializer/DocumentSerializer.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java

Fix FEEL expression handling for documents

fix(document): Fix FEEL document serialization

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/webhook/WebhookResultContext.java
connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/webhook/WebhookTriggerResultContext.java
connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/AbstractFeelDeserializer.java
connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializer.java

- Replace DocumentReference with Document so that we have the right format that can be used by subsequent connectors;
- Add the right Jackson modules to the ObjectMapper used by the AbstractFeelDeserializer
https://github.com/camunda/team-connectors/issues/788

feat(webhook): Replace DocumentReference by Document

---

bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/InMemoryDocumentStoreConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
connector-sdk/document/src/main/java/io/camunda/document/CamundaDocument.java
connector-sdk/document/src/main/java/io/camunda/document/store/InMemoryDocumentStore.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/DocumentReferenceModel.java
connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/DocumentSerializationTest.java
connectors-e2e-test/connectors-e2e-test-base/src/main/java/io/camunda/connector/e2e/app/TestConnectorRuntimeApplication.java
connectors-e2e-test/connectors-e2e-test-base/src/main/resources/application.properties

Enable the Camunda document store by default
closes #

fix(document): enable Camunda document store

---

bundle/default-bundle/src/test/resources/application.properties

Fix some properties to be compatible with 8.7

chore(properties): fix applicaiton properties

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImplTest.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/InboundConnectorElementTest.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/console/ConsoleSecretApiClient.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java
connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java
connector-sdk/test/src/main/java/io/camunda/connector/test/outbound/OutboundConnectorContextBuilder.java
connectors-e2e-test/connectors-e2e-test-base/src/main/java/io/camunda/connector/e2e/app/TestConnectorRuntimeApplication.java
connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/RabbitMqInboundStartEventTests.java
connectors/http/graphql/src/test/java/io/camunda/connector/http/graphql/GraphQLFunctionTest.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/utils/JsonHelper.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandlerTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionResponseTransformer.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java
connectors/jdbc/src/test/java/io/camunda/connector/jdbc/BaseTest.java
connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/integration/KafkaIntegrationTest.java
connectors/webhook/src/main/java/io/camunda/connector/inbound/signature/strategy/URLAndBodyEncodingStrategy.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedDocsGenerator.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/ParameterUtil.java
secret-providers/gcp-secret-provider/src/main/java/io/camunda/connector/runtime/cloud/GcpSecretManagerSecretProvider.java

Done during the hacking session with the team

fix(document-handling): refactor the Objectmapper supplier and make it private so only copy can be created

---

connectors/aws/aws-base/pom.xml
parent/pom.xml

Role can now be assumed within an AWS EKS cluster using IRSA
`DefaultAWSCredentialsProviderChain` is already looking for web identity token 
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html
The error message was `WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path.`
This is corrected
closes https://github.com/camunda/connectors/issues/3754

feat(aws): Role can now be assumed within an AWS EKS cluster using IRSA

---

connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java
connector-sdk/test/src/main/java/io/camunda/connector/test/outbound/OutboundConnectorContextBuilder.java
connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/RabbitMqInboundStartEventTests.java

Call the `getCopy(DocumentFactory factory, DocumentModuleSettings settings)` instead of the old method

fix(document-handling): fixes after Simon comment

---

connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java
connectors/email/src/test/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmailTest.java

Cherry Pick the bugfix to validate htmlBody and textBody
closes #https://github.com/camunda/connectors/issues/3795

bugfix(mail-connector): Backport 3796 to release/8.6 smtp body validation

---

.github/workflows/helm-git-refs.json

“Latest" version no longer exists, it has to be 8.5 now.

chore(ci): Fix Helm chart version

---

.github/workflows/RELEASE.yaml

- The maven command is too verbose, flooding the github action worker disk. I used the `-q` option for maven to log only errors

chore(ci): fixed no disk space in github action

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/utils/DocumentHelper.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/utils/DocumentHelperTest.java

- Java's  `Collectors.toMap(` does not accept null value, hence producing a NPE when sending this kind of body:
```json
{
"myKey": null
}
```

fix(rest): fix sending null params in a body map

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/utils/DocumentHelper.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/utils/DocumentHelperTest.java

Backport of #3837 to `release/8.7`.

[Backport release/8.7] fix(rest): fix sending null params in a body map

---

.github/workflows/RELEASE.yaml

Backport of #3836 to `release/8.7`.

[Backport release/8.7] chore(ci): fixed no disk space in github action

---

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java

Log the exception when Kafka consumer cannot be started 
closes #https://github.com/camunda/team-connectors/issues/953

fix(kafka-inbound): log the exception when kafka throw on start

---

connector-runtime/connector-runtime-core/pom.xml
connector-runtime/connector-runtime-spring/pom.xml
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretApiClient.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/secret/ConsoleSecretProviderTest.java
connectors-e2e-test/connectors-e2e-test-base/pom.xml
parent/pom.xml

proposal: move to 8.5.16 of spring zeebe

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java

Set retries to zero, when ConnectorInputException is thrown.
closes #3806

feat(runtime): fail without retries on ConnectorInputException

---

connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
connector-sdk/core/src/test/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplierTest.java

This PR will enable the "accept single value as array" feature in Jackon globally.
closes #3849

feat(jackson): enable 'accept single value as array' globally

---

connectors/gitlab/element-templates/gitlab-connector.json
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestUriBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/rest/README.md
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java

- Added a skipEnding field to HttpCommonRequest
- Adjusted gitlab connector json to always set skipEncoding to true
- All github connectors now skip encoding
- in XML skip encoding can be set for rest connectors, defaults to false if not set
- Added a hint to the docs about this option, see PR here: https://github.com/camunda/camunda-docs/pull/4837
- not tested with the web modeller
- I adjusted the gitlab connector by editing the JSON directly
- should I add tests for the UrlEncoder?
- is it possible to add a test for the gitlab connector?
closes #3694

fix(rest connector): add skip decoding field for rest outbound connector

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/document/FileResponseHandler.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/exception/ConnectorExceptionMapper.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonResult.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandlerTest.java
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java

- Added a feature flag to enable getting multiple set cookie headers as a list
- if flag is not set to true behavior is not changed
- if flag is set to true set cookie headers are merged into a list
- other headers are not merged, as set cookie is the only header that is allowed to occure multiple times
- PR for documenting this feature is here: https://github.com/camunda/camunda-docs/pull/4875
closes #3812

feat(rest-connector): Add flag to get multiple set cookie headers as list

---

connectors/soap/src/main/java/io/camunda/connectors/soap/SoapConnector.java
connectors/soap/src/main/java/io/camunda/connectors/soap/client/LoggingInterceptor.java

Remove logs that could be showing sensitive data (request, response)
closes #https://github.com/camunda/team-connectors/issues/965

fix(soap): remove logging of soap request and response

---

connectors/aws/aws-textract/element-templates/aws-textract-outbound-connector.json
connectors/aws/aws-textract/element-templates/hybrid/aws-textract-outbound-connector-hybrid.json
connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/TextractConnectorFunction.java
connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/caller/SyncTextractCaller.java
connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/model/DocumentLocationType.java
connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/model/TextractRequestData.java
connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/caller/AsyncTextractCallerTest.java
connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/caller/SyncTextractCallerTest.java
connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/caller/TextractCallerTest.java
connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/util/TextractTestUtils.java

added documentation handling for textract connector 
[issue](https://github.com/camunda/team-connectors/issues/981)
[element template PR](https://github.com/camunda/web-modeler/pull/12429)
[documentation PR](https://github.com/camunda/camunda-docs/pull/4820)
https://github.com/user-attachments/assets/82738414-916f-48ba-9de8-7ec8a65e80ac

feat(textract doc handle): add documentation handling for textract

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/secret/SecretUtil.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/InboundConnectorDiscoveryTest.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/JobBuilder.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorDiscoveryTest.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/TestUtil.java
connector-sdk/document/src/main/java/io/camunda/document/reference/CamundaDocumentReferenceImpl.java
connector-sdk/document/src/main/java/io/camunda/document/reference/DocumentReference.java
connector-sdk/document/src/main/java/io/camunda/document/store/CamundaDocumentStoreImpl.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/DocumentReferenceModel.java

Use the new client request that includes the content hash when retrieving a document

fix(document-handling): Get document by reference including hash

---

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java

- Add proper exception logging
- Fix an issue where the `deactivate` could wait infinitely if there's an error in `prepareConsumer`
- Integration will come in a separate PR
https://jira.camunda.com/browse/SUPPORT-25217

fix(kafka): fix Kafka connector deactivate method

---

connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/BaseEmailTest.java
connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/OutboundEmailTests.java
connectors-e2e-test/connectors-e2e-test-mail/src/test/resources/email-outbound-connector-send-email-v1.bpmn
connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/ContentType.java
connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java

FIx the backcompatibility issue on between email connector runtime and older template version
closes https://github.com/camunda/connectors/issues/3874

fix(email-connector): now the runtime is backcompatible with all ET

---

element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ExampleTest.java
element-template-generator/openapi-parser/src/test/resources/example-without-server-description.yaml

Modified the template generator to use the server url as label if the description is null. This way we can avoid having choices without names, which would not be compatible with the template schema. 
closes https://github.com/camunda/connectors/issues/3886

fix(template-generator): use server url if description is not found

---

.github/workflows/TEST_FEATURE_BRANCH.yml

- Using `pull_request_target` lead to this behavior:
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks. Avoid using this event if you need to build or run code from the pull request.
Using the `main` branch context is not acceptable, as a failing test in your branch won't be detected.
For now we will use the previous configuration, and we'll deal with PRs from forks manually as it's not happening often.

other(ci): bring back the old test configuration

---

renovate.json

It seems like the manager value for `helm` might not be correct. Hence reverting it.

fix(ci): Remove helm manager from renovate config

---

.github/workflows/PREVIEW-ENV-TEARDOWN.yml

We are updating the `preview-env/destroy` composite action to not only deactivate a deployment during teardown but also to delete the deployment and the relative environment. 
This is to limit the proliferation of inactive deployments, making it very hard to understand what's active and what is not active.
- camunda/team-infrastructure#456

chore(preview-env): update the preview-env teardown workflow

---

.github/workflows/TEST_FEATURE_BRANCH.yml

Add -Dsurefire.skipAfterFailureCount=1 to TEST_FEATURE_BRANCH action.
closes https://github.com/camunda/team-connectors/issues/983

other(CI): Add skipAfterFailure flag to tests

---

connectors/github/element-templates/github-connector.json

Use the correct name of the "release name" property when creating or updating a release.
closes #3973

fix(github-connector): use correct name of 'release name' property

---

connectors/box/element-templates/box-outbound-connector.json
connectors/box/element-templates/hybrid/box-outbound-connector-hybrid.json
connectors/box/src/main/java/io/camunda/connector/box/BoxOperations.java
connectors/box/src/main/java/io/camunda/connector/box/BoxUtil.java
connectors/box/src/main/java/io/camunda/connector/box/model/BoxRequest.java
connectors/box/src/main/java/io/camunda/connector/box/model/BoxResult.java

Fixes the exception that happened after deleting a file or a folder when the Box client tried to refetch information from the now deleted object.
- [x ] PR has a **milestone** or the `no milestone` label.

fix(box-connector): Avoid refetching data of deleted items

---

README.md

We don't use make in this repo.
closes #

fix(docs): remove the mention of make on readme

---

connectors/sendgrid/element-templates/hybrid/sendgrid-outbound-connector-hybrid.json
connectors/sendgrid/element-templates/sendgrid-outbound-connector.json
connectors/sendgrid/src/main/java/io/camunda/connector/sendgrid/SendGridFunction.java
connectors/sendgrid/src/main/java/io/camunda/connector/sendgrid/model/SendGridRequest.java
connectors/sendgrid/src/test/java/io/camunda/connector/sendgrid/BaseTest.java
connectors/sendgrid/src/test/java/io/camunda/connector/sendgrid/SendGridFunctionTest.java
connectors/sendgrid/src/test/java/io/camunda/connector/sendgrid/SendGridRequestTest.java
connectors/sendgrid/src/test/resources/requests/send-mail-by-template-success-cases.json
connectors/sendgrid/src/test/resources/requests/validation/request-with-attachments-without-file-name.json

attachments support for sendgrid connector
element template [pr](https://github.com/camunda/web-modeler/pull/12776)
documentation [pr](https://github.com/camunda/camunda-docs/pull/4916)
https://github.com/user-attachments/assets/fc36eefc-3242-49fc-8d5b-b9ad457e323b

feat(sendgrid): attachment support

---

connectors/google/google-drive/element-templates/google-drive-outbound-connector.json
connectors/google/google-drive/element-templates/hybrid/google-drive-outbound-connector-hybrid.json
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveClient.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveFunction.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveService.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/LoggerProgressListener.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/mapper/DocumentMapper.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/MimeTypeUrl.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/DownloadData.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/Resource.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/Type.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/UploadData.java
connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/GoogleDriveFunctionTest.java
connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/GoogleDriveServiceTest.java
connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/mapper/DocumentMapperTest.java
connectors/google/google-drive/src/test/resources/requests/file-success-download.json
connectors/google/google-drive/src/test/resources/requests/file-success-upload.json
connectors/google/google-drive/src/test/resources/requests/request-fail-test-cases.json

Added the ability to download and upload files.
[issue](https://github.com/camunda/team-connectors/issues/990)
[element-template PR](https://github.com/camunda/web-modeler/pull/12706)
[doc PR](https://github.com/camunda/camunda-docs/pull/4899)
https://github.com/user-attachments/assets/11bc6f0d-1c4b-4e6d-9643-e9817ca60740

feat(drive): upload and download file

---

.ci/preview-environments/charts/c8sm/Chart.yaml
.github/workflows/RELEASE.yaml

This PR will fix the preview env deployment for 8.7 by upgrading to the latest alpha version of the Helm chart.
closes #

fix(deploy-preview): upgrade 8.7. helm chart to make deploy preview work

---

.github/workflows/RELEASE.yaml

This reverts commit 1e2da2dc73e94787a51cc574c164361e94834258.
Tests were temporarily disabled during the 8.7-alpha4 release to bypass the failing/flaky test that prevented the release.
closes #

Revert "chore: temporarily disable tests in release workflow"

---

connectors/jdbc/pom.xml
connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/client/JdbiJdbcClient.java
connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/client/JdbiJsonHelper.java
connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/IntegrationBaseTest.java
connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/IntegrationTestConfig.java
connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/JdbiJdbcClientIntegrationTest.java

Added JSON parsing for string columns.
Added Uni Tests for all sql specific json columns
closes #3895

feat(sql): Add JSON support

---

connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/ObjectMapperSerializationTest.java

The latest camunda-java-client snapshot has changed the name of the bean to `zeebeJsonMapper` to `camundaJsonMapper`
Additionally, I removed the `commonJsonMapper` which is useless since we separated the serializer and deserializer
- To create `CamundaDocumentStore` we use the `CamundaClient` containing the `JsonMapper` containing only the Serializer (The Basic one), the client does not need the deserializer anyways
- To create the  `DocumentFactory` we use the `CamundaDocumentStore` : no problems here
- To create OUR objectMapper for connectors, we use this `DocumentFactory` : no issues again
This simplifies everything and fixes the current issue
Fixing main tests

chore(tests): fix tests on main after camunda client changes

---

.github/workflows/RELEASE.yaml

There is no need to execute the `maven release` job when releasing an RC, this PR fixes this
I also added `git config core.filemode false` because I had this weird [commit](https://github.com/camunda/connectors/commit/c49cb7421cef5e67034243f95550e78402c046ca) while trying to release
closes #https://github.com/camunda/team-connectors/issues/933

other(CI): do not execute maven release job if it is an RC release

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/InboundConnectorContext.java
connector-sdk/core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java
connector-sdk/test/src/main/java/io/camunda/connector/test/outbound/OutboundConnectorContextBuilder.java
connectors/aws/aws-bedrock/element-templates/aws-bedrock-outbound-connector.json
connectors/aws/aws-bedrock/element-templates/hybrid/aws-bedrock-outbound-connector-hybrid.json
connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/BedrockConnectorFunction.java
connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/S3ConnectorFunction.java
connectors/box/src/main/java/io/camunda/connector/box/BoxOperations.java
connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java
connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/mapper/DocumentMapper.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/ExecutionEnvironment.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/HttpService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/document/FileResponseHandler.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/TestDocumentFactory.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionResponseTransformer.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java

- Fix the REST Connector issue when uploading documents in SaaS
- Make the Outbound/Inbound-ConnectorContexts great again: they now implement `DocumentFactory` as discussed in an architecture session.
closes https://github.com/camunda/team-connectors/issues/1015

fix(rest-connector): fix document upload in SaaS

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/ProxyHandler.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java

Due to a bug I needed to adjust the handling of proxy configs set via env vars.
~~Once approved i will backport this to 8.7 with cherry-pick here: https://github.com/camunda/connectors/pull/4002~~
As this PR got merged, I added the backport label and a new PR will be created.
related to: https://github.com/camunda/team-connectors/issues/989

feat(rest): Improve http proxy

---

.github/workflows/reopen_support_issues_without_version_label.yml

Adding a GHA check on issues that are closed that if it includes a "support" label. If it does, this script will check that if it has the version: -label included. If it does not, then the script will reopen the issue and comment on it that this label needs to be added before closure.
Support has had problems that some of the closed support related issues are not included in the support notification message, because the "version:" label is missing from the issues.
closes #

other(CI): Create reopen_support_issues_without_version_label.yml

---

.github/workflows/RELEASE.yaml

Backporting changes from `release/8.8` to `main`
related https://github.com/camunda/team-connectors/issues/933 & https://github.com/camunda/team-connectors/issues/991

chore(ci-release): Backport release changes from `release/8.8` to `main`

---

connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json
connectors/slack/element-templates/slack-outbound-connector.json
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/SlackFunction.java
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/caller/FileUploader.java
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/mapper/BlocksMapper.java
connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ChatPostMessageData.java
connectors/slack/src/test/java/io/camunda/connector/slack/outbound/caller/FileUploaderTest.java
connectors/slack/src/test/java/io/camunda/connector/slack/outbound/mapper/BlocksMapperTest.java
connectors/slack/src/test/java/io/camunda/connector/slack/outbound/model/ChatPostMessageDataTest.java

slack attachments feat
demo
https://github.com/user-attachments/assets/130079be-370f-4533-9dc7-17da85721725
documentation PR: https://github.com/camunda/camunda-docs/pull/5081
closes #

feat(slack): add attachments support

---

connectors/email/element-templates/email-outbound-connector.json
connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json
connectors/email/src/main/java/io/camunda/connector/email/authentication/SimpleAuthentication.java
connectors/email/src/main/java/io/camunda/connector/email/outbound/EmailConnectorFunction.java

Password can now be set using a feel expression
closes https://github.com/camunda/connectors/issues/4046
PR on web modeler: https://github.com/camunda/web-modeler/pull/13192

chore(mail-connector): password can be set with a feel expression

---

.github/workflows/RELEASE.yaml

We cannot deploy the cloud function because release candidate were not deployed anymore on camunda-nexus. This fixes it

fix(element-template-generato): publish to camunda-nexus for release candidate

---

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunction.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionResult.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunctionTest.java

Changes were made to the response from `ExtractionConnectorFunction`. The new method `buildResponseJsonIfPossible` ensures a specific structure based on the `taxonomyItems` input.
closes https://github.com/camunda/connectors/issues/4145

feat(idp-extraction-connector): idp connector should return response as key/value pair of extracted fields

---

element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedDocsGenerator.java

Disallow include in pebble engine in element template builder core. See [here](https://www.cve.org/CVERecord?id=CVE-2025-1686) and [here](https://camunda.slack.com/archives/C02JLRNQQ05/p1741089936227569)
Applied the suggested fix. Tested element template generation for email connector and openAPI specs. Works as expected. Pebble engine is not used in [8.5.](https://github.com/camunda/connectors/blob/release/8.5/element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedTemplateGenerator.java) so only needs backport to 8.7 and 8.6

fix(security): Disallow include in pebble engine

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java
bundle/camunda-saas-bundle/src/main/resources/application.properties

(cherry picked from commit 5533dea48a6f748396f2f9bcf50c49759f258dee)
- Fix tests by adding the possibility to disable `allowCredentials`. When set to `true` one cannot set the allowed origins to `*` anymore.

chore(cors): fix cors config for /inbound-instances subpaths

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java

- The `/inbound-instances` API changes and has now a sub path. Thus we need to authenticate all the requests for this path and its subpaths.
- Enable default cors to see if it stops the 401 when performing an OPTIONS request

chore(cors): fix authenticated path after API changes

---

bundle/camunda-saas-bundle/src/main/resources/application.properties
bundle/default-bundle/src/main/resources/application.properties
connector-runtime/connector-runtime-application/src/main/resources/application.properties

- Increase headers size to 1MB, this is useful when Console calls our API with a huge JWT which might happen

chore(api): increase allowed headers size to 1MB

---

bundle/camunda-saas-bundle/src/main/resources/application.properties
bundle/default-bundle/src/main/resources/application.properties
connector-runtime/connector-runtime-application/src/main/resources/application.properties

(cherry picked from commit 83a708b22d401e3e170d7d40e3e78bdad055df73)
Backport of https://github.com/camunda/connectors/pull/4223

chore(api): increase allowed headers size to 1MB (#4223)

---

parent/pom.xml

We currently have 1 critical and 1 high-severity CVE in release/8.5 and below.
- https://www.cve.org/CVERecord?id=CVE-2024-57699 coming from a JSON parser library transitively via `azure-identity`
- https://www.cve.org/CVERecord?id=CVE-2024-50379 coming from Tomcat transitively via Spring Boot
This PR will fix those vulnerabilities by upgrading to versions of those libraries that are patched.

fix(deps): bump dependencies to fix CVEs

---

renovate.json

During the last CVE review, we discovered that Renovate doesn't automatically apply minor version upgrades on feature branches.
Sometimes libraries release fixes for major issues in minor versions instead of patches, so I think it is beneficial if we get minor version upgrades as well.
On the other hand, this might introduce more instability, so I'm open to suggestions/critic regarding this change.

chore(deps): enable minor version upgrades on release branches

---

connectors/gitlab/element-templates/gitlab-connector.json
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestUriBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/rest/README.md
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java

(cherry picked from commit 0c341672729da9d4e59fc716ec38d47f1331648d)
Backport the skip encoding feature to 8.6. Feel free to test this will change nothing, if not explicitly updating the element template.

Add skipEndcoding flag for rest and gitlab connector (#3840)

---

connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java

- We need to clear system properties properly, not setting them to empty string as we now handle unset properties.

other(tests): fix proxy tests, clear properties properly

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionTest.java

add a boolean that allows to ignore null values
closes https://github.com/camunda/team-connectors/issues/948

feature(rest-connector): add a boolean that allows to ignore null values

---

parent/pom.xml

Backport of https://github.com/camunda/connectors/pull/4267 to 8.3
closes #

fix(deps): bump dependencies to fix CVEs (8.3)

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandlerTest.java
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json

Restore the default behavior of 8.5. Set cookie headers a always merged into an array. The flag for grouping is removed. This also means, if someone sets the group flag to false, this will be ignored after an update, but I think that is ok, as this is not really a helpful feature and I guess noone will do this. 
This will be documented [here](https://github.com/camunda/camunda-docs/pull/5137)
I did not document the "breaking change" in the last two lines of the table, because i consider this a bug fix and not a breaking change. Let me know if you disagree, then I will add it to the docs. (We could adjust the behavior so that if there is only one Set-Cookie header, it returns a simple string instead of an array. However, this approach is not ideal. For example, if an endpoint sometimes …

fix(rest-connector): Return always an array for set cookie headers

---

element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ConnectorConfig.java
element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ElementTemplateGeneratorMojo.java

Add a function to element template generation to create the meta-inf/service files automatically. I tested this with the email, graphql and other connectors and it created the same files as the existing ones. Some connectors do not have the plugin in the pom, so I suppose it is expected, these are not working.
Let me know if there are other use-cases than our connectors in `/connectors/` that need to be tested / keep working.
closes: https://github.com/camunda/team-connectors/issues/620

chore(element-template-generator): Automate meta-inf service generation

---

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/VertexCaller.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionResult.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunctionTest.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/VertexCallerTest.java

I added a rename of the `ExtractionResult` results map. I also added a small fix for gcp
closes https://github.com/camunda/connectors/issues/4355

chore(idp-extraction-connector): rename results map

---

.github/workflows/NIGHTLY_E2E.yml
connector-sdk/core/src/test/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplierTest.java
connector-sdk/test/src/main/java/io/camunda/connector/test/SlowTestCondition.java

This PR fixes the `SlowTest` condition - previously it never worked to run the tests if the flag is not present.
Additionally, I configured Slack notifications for test runs, and introduced a matrix to run e2e tests across all release branches too, not only main.

chore(ci): nightly e2e test slack notifications

---

connectors/aws/aws-s3/element-templates/aws-s3-outbound-connector.json
connectors/aws/aws-s3/element-templates/hybrid/aws-s3-outbound-connector-hybrid.json
connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/S3ConnectorFunction.java
connectors/box/element-templates/box-outbound-connector.json
connectors/box/element-templates/hybrid/box-outbound-connector-hybrid.json
connectors/box/src/main/java/io/camunda/connector/box/BoxFunction.java
connectors/google/google-gemini/element-templates/google-gemini-outbound-connector.json
connectors/google/google-gemini/element-templates/hybrid/google-gemini-outbound-connector-hybrid.json
connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/GeminiConnectorFunction.java

Added version to connectors links that are not available in 8.6.
Similar changes I did to web-modeler project here:  https://github.com/camunda/web-modeler/pull/13654
See related docs PR here: https://github.com/camunda/camunda-docs/pull/5090
Can I backport this or is backporting to 8.7 "closed"?

chore(element-templates): Adjust doc links

---

renovate.json

Fix the renovate.json file regex that filters out suggesting to update to SNAPSHOT dependencies.
closes #4311

fix(renovate.json): Fix SNAPSHOT filter

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/InvalidBackOffDuration.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/InvalidBackOffDurationException.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorExceptionHandler.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/secret/SecretUtil.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/JobHandlerContextTest.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/jobhandling/SpringConnectorJobHandler.java
connector-sdk/validation/src/main/java/io/camunda/connector/validation/impl/DefaultValidationProvider.java
connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/TextractConnectorFunctionTest.java
connectors/soap/element-templates/hybrid/soap-outbound-connector-hybrid.json
connectors/soap/element-templates/soap-outbound-connector.json

PR to hide secret from error  message sent to zeebe
- Secrets are being hidden from error message sent to zeebe
- The object mapper exception is way more precise
- Error from validation are more concise
closes https://github.com/camunda/connectors/issues/3221

feature(secrets): secrets are now hidden from the error message in operate, making error message more reliable

---

connectors/microsoft-teams/element-templates/hybrid/microsoft-teams-outbound-connector-hybrid.json
connectors/microsoft-teams/element-templates/microsoft-teams-outbound-connector.json
connectors/microsoft-teams/src/main/java/io/camunda/connector/MSTeamsFunction.java
connectors/microsoft-teams/src/main/java/io/camunda/connector/model/request/data/SendMessageToChannel.java
connectors/microsoft-teams/src/main/java/io/camunda/connector/operation/channel/DocumentHandler.java
connectors/microsoft-teams/src/main/java/io/camunda/connector/operation/channel/SendMessageToChannelOperation.java
connectors/microsoft-teams/src/test/java/io/camunda/connector/model/request/channel/SendMessageToChannelTest.java

Added document support when sending messages to channels
See example bpmn [here](https://modeler.ultrawombat.com/diagrams/fae5f90c-edc9-4c9e-81af-d3120555f1b8--teams?v=579,282,1)
Get your token [here](https://developer.microsoft.com/en-us/graph/graph-explorer) under "Access Token" tab
Documented here: https://github.com/camunda/camunda-docs/pull/5333
partially solves https://github.com/camunda/team-connectors/issues/1002
In a next PR the option to send documents in private messages is added, this is currently not possible, because of access restrictions in our MS Teams setup. We are hoping to get access to a Sandbox environment where we can test this. When sending documents in messages, the documents are uploaded to the SharePoint. When sending documents to a channel, they are uploaded to …

feat(ms-teams): Add document handling for sending message to channel

---

.ci/preview-environments/charts/c8sm/values.yaml
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/HttpService.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/HttpClient.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestAuthenticationBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/proxy/ProxyAwareHttpClient.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/proxy/ProxyHandler.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/proxy/ProxyRoutePlanner.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/proxy/ProxyRoutePlannerTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java
connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpServiceTest.java

This PR changes the previous behavior about how we configure a proxy (and non-proxy hosts).
- We can now set up a proxy for REST-like connectors **only** (REST, Github, etc). This is done using a specific set of **environment variables**: 
| Env. Var | Description | Default |
|--------|--------|--------|
| CONNECTOR_HTTP(S)_PROXY_SCHEME | The proxy **scheme** (`http`, or `https`). This allows the user to use https proxies which is not possible with other clients | `http` |
| CONNECTOR_HTTP(S)_PROXY_HOST | The **host** part of the proxy URL (do not include `http://`)  | |
| CONNECTOR_HTTP(S)_PROXY_PORT | The **port** part of the proxy URL | |
| CONNECTOR_HTTP(S)_PROXY_USER | If you need to authenticate, use this variable to set the **user** | |
| CONNECTOR_HTTP(S)_PROXY_PASSWORD | If you …

refactor(rest): refactor the proxy support for the REST Connector

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/DocumentAwareMultipartEntityBuilder.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionFilePart.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/utils/DocumentHelperTest.java

Uploading documents using the REST Connector and a `multipart/form-data` request is now working correctly in SaaS (it was working in SM).
- The cluster will convert the Documents to a new custom `CloudFunctionFilePart` type. This is required so that all the information (filename, content type) is serialized and sent to the CloudFunction.
- Previously only the Document content was sent, leading to the request payload not being identified as a file.

fix(rest): fix document upload in SaaS, using multipart requests

---

connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json

This PR adds a new field to our Office 365 connector that allows to send documents in an email.
Since this is an element-template-only connector, we can do this using an intrinsic function `base64`, but for this case it's actually enough to provide a document directly due to how the REST connector works.
Follow this guide: https://github.com/camunda/team-connectors/issues/1004
And another guide on how to get a user token: https://github.com/camunda/team-connectors/blob/main/how-to/OUTLOOK_APP_FOR_EMAIL_TESTING.md
closes https://github.com/camunda/team-connectors/issues/1004

feat(office-365): send documents via email

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/ExecutableId.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorElement.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/details/InboundConnectorDetails.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/InboundConnectorElementTest.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/ActiveInboundConnectorResponse.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundInstancesRestController.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/ActiveExecutableResponse.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/BatchExecutableProcessor.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableEvent.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableRegistryImpl.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableRegistryTest.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundEndpointTest.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundInstancesRestControllerTest.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/rest/element-templates/http-json-connector.json
connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json

- Executable IDs aren't UUIDs anymore. They're now built this way: `executableId = sha256(deduplicationId)` 
- This will ensure stable IDs across runtimes
- I changed the `deduplicationId` generation, and I am now using `processDefinitionKey` instead of `bpmnProcessId`. The idea is that we might have different executables for different process versions (when we fetch latest+active processes).

refactor(deduplicationId): change the executableIds from UUID to a hashed deduplicationId for stability across runtimes

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/metrics/ConnectorMetrics.java

The metric has been renamed by mistake.
closes #

fix(metric): proc def metric has incorrect name

---

connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json

Follow up for #4393 - use an intrinsic function instead of relying on implicit Jackson + HTTP connector functionality. This might be simpler to maintain.
closes #

refactor(office-365): use an intrinsic function for sending base64 documents

---

connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsQueueConsumerTest.java

The SQS test is potentially flaky. There is a do-while loop inside the consumer so it's guaranteed to run at least once, but if the consumer stop is delayed, `verify` calls might see more invocations than expected.
closes #

fix(test): sqs test potentially flaky

---

connectors/email/element-templates/email-inbound-connector-boundary.json
connectors/email/element-templates/email-inbound-connector-intermediate.json
connectors/email/element-templates/email-message-start-event-connector.json
connectors/email/element-templates/hybrid/email-inbound-connector-boundary-hybrid.json
connectors/email/element-templates/hybrid/email-inbound-connector-intermediate-hybrid.json
connectors/email/element-templates/hybrid/hybrid-email-message-start-event-connector-hybrid.json
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java

ETG has a filter now
It will not apply `Number` and `Boolean` to inbound connector template

fix(inbound-connector): do not apply number and boolean to inbound connector

---

connectors/microsoft-teams/pom.xml
parent/pom.xml

Removed the dependency. Feel free if the connector still works on mac locally.
closes https://github.com/camunda/team-connectors/issues/1013

chore(ms-teams): Remove netty-resolver-dns-native-macos

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConfiguration.java

`camunda.client.clusterId` is now deprecated. We should switch to `camunda.client.cloud.clusterId` in a failsafe way.
closes #

fix(config): failsafe cluster id prop in saas

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConfiguration.java

Revert the failsafe client id reference and use the new format. This was not a good idea.
closes #

fix(config): revert failsafe config for cluster id

---

renovate.json

Added some improvements to the renovate config.
`group:allNonMajor`
- one PR for all minor and patch updates instead of a separate PR for every one of them.
- Because of grouping i expect all the dependency updates blocked by rate limiting ([see dashboard](https://github.com/camunda/connectors/issues/72)), will now come now.
`schedule:earlyMondays` at monday 4am the PRs are created
`schedule:automergeNonOfficeHours` at non office hours the PRs are merged, so we do not get blocked because renovate fills our merge queue during working hours.
Timezone: Europe/Berlin
closes #4558

chore(renovate): Add grouping and schedule to renovate config

---

parent/pom.xml

Pin httpcore5-h2 dependency, as the Camunda client imports a different version that causes issues on our side when starting the Runtime. The runtime starts, but the httpclient thread dies, which means nothing can be done.

chore(deps): pin httpcore5-h2 due to an incompatibility in camunda client

---

.github/workflows/TEST_FEATURE_BRANCH.yml
.github/workflows/scripts/collect_all_element_template_docs_links.sh

As the docs PR is merged, this now points to main as expected/intended.
Adjusted the test feature branch workflow, so only the links from the current connectors repo state are checked

chore(ci): Adjust link in bump docs workflow

---

renovate.json

- add replacement to ignore patterns, needed because zeebe-client dependency was moved
- migrated `matchPackagePrefixes` matcher, that no longer exists
- improved readability of matchings

chore(renovate): Add ignore of replacement updates and migrate outdated rule

---

element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/core/GitCrawler.java
element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/dto/ElementTemplate.java
element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/dto/VersionValue.java

discussed with @sbuettner, uniquet should now use the engine from the element template, otherwise work as before

others(uniquet): modify the uniquet now uses engine from element-template

---

renovate.json

Increase the pr hourly limit to 10, so when renovate is running on Sunday night it can open up to 10 PRs and is not blocking itself until next week

chore(renovate): Increase pr hourly limit to 10

---

.fossa.yml
.github/workflows/CHECK_LICENSES.yml

Related to https://github.com/camunda/team-infrastructure/issues/751 and previous PR https://github.com/camunda/connectors/pull/4416.
This PR extends the FOSSA integration to include stable branches and tags in addition to the `main` branch. Like the previous PR, it only pushes data (dependency graph) to FOSSA and does not introduce any blocking checks.
Internally, if the commit has already been scanned by FOSSA (e.g., in the main branch), it will just refer to the existing scan (using the revision ID). If no scan exists (it might happen), a new scan will be triggered and performed by FOSSA (internally).
`${{ github.ref_name }}` retrieves the tag name, as for the branch. Tests with tags have been performed on a separate test repository.
closes #

chore(fossa): extend integration to stable branches and tags

---

bundle/default-bundle/src/main/resources/application.properties
connector-runtime/connector-runtime-application/src/main/resources/application.properties
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretProvider.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java

Remove default address properties because they break the bundle when Camunda is not running locally (e.g. in hybrid mode).
closes #

fix(config): remove default address property values on 8.7

---

bundle/default-bundle/src/main/resources/application.properties
connector-runtime/connector-runtime-application/src/main/resources/application.properties
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretProvider.java
connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java

Remove default address properties because they break the bundle when Camunda is not running locally (e.g. in hybrid mode).
closes #

fix(config): remove default address property values

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/DefaultProcessInstanceContext.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/ProcessInstanceClient.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/ProcessInstanceClientImpl.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClient.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientImpl.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/ProcessInstanceClientImplTest.java
connectors-e2e-test/connectors-e2e-test-base/src/main/java/io/camunda/connector/e2e/app/TestConnectorRuntimeApplication.java
connectors-e2e-test/connectors-e2e-test-base/src/main/resources/application.properties
connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java

Fix main after this [PR](https://github.com/camunda/camunda/pull/30738) from Camunda. 
I just don't understand why the latest is now `camunda/zeebe:SNAPSHOT` and not `camunda/camunda:SNAPSHOT` That is why I had to add `io.camunda.process.test.camundaDockerImageName=camunda/zeebe:SNAPSHOT`
closes #

chore(fix-main): fix main after deployment of new snapshot

---

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/StructuredExtractionResult.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java

We are adding a new map to the response of the idp structured extraction. We are sending the original extracted keys because they are needed in the WM ui. 
closes https://github.com/camunda/connectors/issues/4628

fix(idp-extraction-connector): add original keys as output to the structured extraction

---

connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequestData.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/util/ExtractionTestUtils.java

This PR adds a new input to the idp structured extraction. The logic goes like this: 
- For every key we genrate a "Zeebe-safe" variable 
- If the user wants to override any of them, he sends them back as input on this new "renameMappings" field.
- When running the extraction again, before we do the variable generation, we check if we have an override available.
closes https://github.com/camunda/connectors/issues/4627

fix(idp-extraction-connector): add renameMappings input

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/BatchExecutableProcessor.java
connectors/email/pom.xml
connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java
connectors/email/src/test/java/io/camunda/connector/email/integration/InboundEmailTest.java

Some IMAP servers do not permit folder creation:
- Infomaniak allows it.
- Gmail does not.
When the folder did not exist on Gmail, the scheduler malfunctioned due to an exception being thrown. To prevent this issue, we now mark the email as 'read' before attempting to move it, ensuring that it is not processed again, thereby improving the system's efficiency.
If an exception occurs because the folder could not be created, and we are reading only unseen emails, the connector is canceled with a RetryException. If we are reading all emails, the connector is canceled with a ConnectorException.
closes https://github.com/camunda/connectors/issues/4367

fix(email-connector): fix for inbound email connector when an email cant be moved

---

element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpAuthentication.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java
element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/SecurityUtil.java
element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/SecurityUtilTest.java

- Added the default auth section with all options if providing a openAPI spec with no security section.
- added some missing ids to avoid duplicated keys
closes #4296 
Here are some test files I used for testing:
[test.zip](https://github.com/user-attachments/files/19547782/test.zip)
I used nginx to verify the api keys worked properly with this endpoint config:
```
location /test-api-key {
default_type application/json;
add_header sendApiKeyHeader $http_keynameabc;
add_header sendApiKeyQuery $arg_keynameABC;
return 201;
}
```

feat(element-template-generator): Add all auth sections if no security scheme provided by openapi scheme

---

renovate.json

Added regex to match base release branches. Should we do this or should we do back to the list and not include 8.8? Do we want to run renovate on latest not yet released release branch?

chore(renovate): Match all release branches with regex

---

connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/instances/service/DefaultInstanceForwardingServiceIntegrationTest.java

Fix E2E tests: types changed I forgot about that.

other(tests): fix E2E test

---

connectors/kafka/pom.xml

Backport of #4673 to `release/8.6`.

[Backport release/8.6] chore(dependency): Upgrade classgraph dependency to fix CVE

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/http/DefaultInstancesUrlBuilder.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/http/DefaultInstancesUrlBuilderTest.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/http/InstanceForwardingHttpClientTest.java

Pods should be contacted using HTTP not HTTPS.

other(manage-and-run): fix pods URL using HTTP not HTTPS

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/ConnectorHelperTest.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/JacksonModuleDocumentDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/AbstractDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/ByteArrayDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/DeserializationUtil.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/DocumentDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/InputStreamDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/IntrinsicFunctionObjectResultDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/ObjectDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/StringDeserializer.java
connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/IntrinsicFunctionDeserializationTest.java

This PR will introduce basic guardrails for intrinsic functions:
- A limit on how many functions can be executed as part of one deserialization round (configurable via document module settings)
- A check when creating output variables to ensure intrinsic functions are not created dynamically as a result of connector execution (works both for inbound and outbound)
closes https://github.com/camunda/team-connectors/issues/1032

fix(intrinsic-functions): introduce guardrails for intrinsic functions

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/ConnectorHelperTest.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/JacksonModuleDocumentDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/AbstractDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/ByteArrayDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/DeserializationUtil.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/DocumentDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/InputStreamDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/IntrinsicFunctionObjectResultDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/ObjectDeserializer.java
connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/StringDeserializer.java
connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/IntrinsicFunctionDeserializationTest.java

Backport #4680 to release/8.7
Adjustments compared to the original:
- I decided to bring in the null check, not sure why it was missing
- I changed the ConnectorInputException to IllegalArgumentException because the former does not exist here
closes #

fix(intrinsix-functions): guardrails for intrinsic functions

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/BaseAgenticAiTest.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors.bpmn
connectors-e2e-test/connectors-e2e-test-base/src/main/java/io/camunda/connector/e2e/ZeebeTest.java

We've seen flakiness on the agentic AI e2e tests caused by 2 different issues:
Sometimes the broker is not ready yet for the deployment of the process and fails with:
```
io.camunda.client.api.command.ClientStatusException: Expected to execute command on partition 1, but either it does not exist, or the gateway is not yet aware of it
at io.camunda.client.impl.CamundaClientFutureImpl.transformExecutionException(CamundaClientFutureImpl.java:115)
at io.camunda.client.impl.CamundaClientFutureImpl.join(CamundaClientFutureImpl.java:53)
at io.camunda.connector.e2e.ZeebeTest.deploy(ZeebeTest.java:54)
at io.camunda.connector.e2e.agenticai.BaseAgenticAiTest.deployModel(BaseAgenticAiTest.java:63)
```
This is the same error message as referenced in https://github.com/camunda/camunda/pull/30231 - I …

test(agentic-ai): fix e2e test flakiness

---

.github/workflows/helm-git-refs.json

In the Helm repo, we now release all charts, even alpha, so there is no need for a special alpha dir.
Hence, I renamed the chart dir from alpha to 8.8.
Related to: https://github.com/camunda/team-distribution/issues/499

ci(helm): rename chart dir from alpha to 8.8

---

connector-runtime/spring-boot-starter-camunda-connectors/pom.xml
parent/pom.xml

This release adds back identity autoconfigure that was used transitively before.
Slack thread: https://camunda.slack.com/archives/C05K4TAEPDW/p1745937249457359?thread_ts=1745846035.461319&cid=C05K4TAEPDW
closes #

fix: added back identity autoconfigure

---

bundle/default-bundle/src/test/resources/application.properties

As discussed in the meeting.
I just tested, this seems not to be necessary for 8.7 release branch.

chore(fix-main): Quick fix for failing LocalConnectorsRuntime on main

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors.bpmn
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolver.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolverTest.java
connectors/agentic-ai/src/test/resources/ad-hoc-tools.bpmn

The current agentic AI tool resolving logic resolves all "root" elements (no incoming flows) within an ad-hoc subprocess as tools, which also applies to boundary events. With this change, boundary events are explicitly excluded from being resolved as tools.
based on #4721 
closes #4713

fix(agentic-ai): do not resolve boundary events in ad-hoc subprocess as tools

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoder.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoderTest.java

Use the correct functions for en- and decoding.
See from [Java docs](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html): 
> Note, the URI class does perform escaping of its component fields in certain circumstances. The recommended way to manage the encoding and decoding of URLs is to use URI, and to convert between these two classes using toURI() and URI.toURL().
> 
>   The URLEncoder and URLDecoder classes can also be used, but only for HTML form encoding, which is not the same as the encoding scheme defined in RFC2396.
And the [URL Encoder docs:](https://docs.oracle.com/javase/8/docs/api/java/net/URLDecoder.html)
> The plus sign "+" is converted into a space character "   " .
Fr Refernce also see: [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986)
closes #4676 …

fix(rest-connector): Fix url encoding to handle edge cases correctly

---

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java
connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/PollingManagerTest.java
connectors/email/src/test/java/io/camunda/connector/email/integration/BaseEmailTest.java
connectors/email/src/test/java/io/camunda/connector/email/integration/InboundEmailTest.java

Fix:
- CorrelationResult is now properly managed.
- MessageId is not stripped from its brackets
closes https://github.com/camunda/connectors/issues/4740

fix(email-connector): add correlation result management and and stop removing the brackets from messageID

---

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/PollingManagerTest.java

others(backport): Backport email fix 8.6

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/AiAgentTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/BaseAgenticAiTest.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors.bpmn
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/DefaultAiAgentRequestHandler.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java

- Make configuration of tools, memory settings and limits optional & do not fail if the request object is null
- Add e2e tests verifying that the connector still works when none of these settings is set and that the max model calls limit falls back to a default value of 10

fix(agentic-ai): resilient optional configuration (tools, memory, limits) handling

---

connectors-e2e-test/connectors-e2e-email/pom.xml
connectors-e2e-test/connectors-e2e-email/src/test/java/io/camunda/connector/e2e/BaseEmailTest.java
connectors-e2e-test/connectors-e2e-email/src/test/java/io/camunda/connector/e2e/InboundEmailTests.java
connectors-e2e-test/connectors-e2e-email/src/test/resources/email-intermediate-event.bpmn
connectors-e2e-test/pom.xml
connectors/email/src/test/java/io/camunda/connector/email/integration/BaseEmailTest.java
connectors/email/src/test/java/io/camunda/connector/email/integration/InboundEmailTest.java

Add tests for email inbound connector, e2e and unit tests
closes https://github.com/camunda/connectors/issues/4740

others(test): add e2e tests for email inbound connector, and verify email is not consumed when activation is not matching

---

connectors/agentic-ai/element-templates/agenticai-adhoctoolsschema-outbound-connector.json
connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-adhoctoolsschema-outbound-connector-hybrid.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-with-tools.bpmn
connectors/agentic-ai/examples/fraud-detection/fraud-detection-process.bpmn
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/AdHocToolsSchemaFunction.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/model/AdHocToolsSchemaRequest.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/AdHocToolsSchemaResolver.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CachingAdHocToolsSchemaResolver.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolver.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CachingAdHocToolsSchemaResolverTest.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolverTest.java

Uses a consistent naming of `ad-hoc sub-process` (text, API specs) and `AdHocSubProcess` (code) throughout the codebase - no behavioral changes, only renames.
Background: https://github.com/camunda/documentation-team/issues/460
Related Camunda issue for ad-hoc sub-process APIs: https://github.com/camunda/camunda/pull/31839

refactor(agentic-ai): update ad-hoc sub-process naming to match the new double-hyphen definition

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors.bpmn
connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
connectors/agentic-ai/examples/ad-hoc-tools-schema/ad-hoc-tools-schema-resolver.bpmn
connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-human-send-email-request.form
connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-initial-request.form
connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-user-feedback.form
connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-with-tools.bpmn
connectors/agentic-ai/examples/fraud-detection/fraud-detection-process-enter-tax-form.form
connectors/agentic-ai/examples/fraud-detection/fraud-detection-process-send-email.form
connectors/agentic-ai/examples/fraud-detection/fraud-detection-process-view-tax-details.form
connectors/agentic-ai/examples/fraud-detection/fraud-detection-process.bpmn
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/AiAgentFunction.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/DefaultAiAgentRequestHandler.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfiguration.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/provider/ChatModelFactory.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/provider/ChatModelFactoryTest.java

Initially we used a common set of model parameters (e.g. max output tokens, topP) for all providers, but the provider APIs differ in which parameters are actually supported. For example OpenAI and Bedrock do not support topK and the maximum tokens configuration varies by provider. 
This PR:
1. Adds a dedicated set of model parameters targeted to the specific provider API
2. Adds tooltips to each parameter referencing the actual provider documentation
3. Refactor the parameter handling in the `ChatModelFactory` to account for null values
4. Adds tests for `ChatModelFactory` verifying that the chat models are built as expected

refactor(agentic-ai): Update model parameters to be provider specific

---

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/DocumentAiCaller.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractAnalysisTask.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractTextDetectionTask.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/DocumentAiCallerTest.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java

This code does 2 things: 
- Adds logic to save all duplicate keys as a new key with a numerator. So if we have three "name" keys they will be returned as "name" "name 2" and "name 3" then the space will be substituted with whatever the delimiter is.
- Handles checkboxes and maps their values to "true" or "false"
Additionally i added this fix:
- Fixes the code to use both text-extraction and document-analysis for textract
closes https://github.com/camunda/connectors/issues/4765

fix(idp-extraction-connector): added handling of duplicate keys and checkboxes on structured extraction

---

connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/AiAgentFunction.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyGroup.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedTemplateGenerator.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/ElementTemplate.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/InboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/inbound/MyConnectorExecutable.java
element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorFunction.java
element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilder.java

Adds support to configure a default `resultVariable` and/or `resultExpression` via `@ElementTemplate` for both inbound and outbound connectors & configures a default result variable on the Agentic AI connector.
Related discussion: https://camunda.slack.com/archives/C02JLRNQQ05/p1746616997970169
closes #4729
related to https://github.com/camunda/team-connectors/issues/1049

feat(element-template,agentic-ai): Add support to configure a default result variable & result expression

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/DocumentAwareMultipartEntityBuilder.java

Added NullpointerException to catch, as this is thrown for input like this:
```
{
"address" : {  //this is invalid as only string and file are allowed
"city" : "Berlin", 
"street" : "Teststr"
}
}
```
I decided to not throw a ConnectorInputExcpetion for this, as this would be a breaking change for process that currently have invalid input that leads to an `IllegalArgumentException` and therefore ignoring this part, but succeeding the process. Feel free to disagree, then I can change this.
closes https://github.com/camunda/connectors/issues/4772

fix(rest): Handle unsupported multipart/form-data parts gracefully

---

connectors/embeddings-vector-database/element-templates/embeddings-vector-database-outbound-connector.json
connectors/embeddings-vector-database/element-templates/hybrid/embeddings-vector-database-outbound-connector-hybrid.json
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/EmbeddingsVectorDBFunction.java

is only available on 8.8 but linking to 8.7
Was raised here: https://github.com/camunda/camunda-docs/pull/5728

chore(embedding-vector-db): Fix docs link

---

connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequestData.java
connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java

I flipped one of the inputs to use inclusion for allowed fields instead of exclusion.
closes https://github.com/camunda/connectors/issues/4738

fix(idp-extraction-connector): reversed logic of excluded fields, using inclusion.

---

connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfiguration.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java

The OpenAI endpoint was already present as hidden property, but as this is a common use case we should officially support configuring a custom API endpoint. This makes testing with OpenAI compatible APIs such as Ollama possible without needing to adapt the template.
closes #4776

feat(agentic-ai): make the OpenAI endpoint + custom headers configurable through properties panel

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/AdHocToolsSchemaTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/Langchain4JAiAgentTests.java

Fixes e2e tests breaking du to renamed CPT method.

test(agentic-ai): fix e2e tests breaking due to renamed CPT variable method

---

.github/workflows/CHECK_LICENSES.yml

Related to https://github.com/camunda/team-infrastructure/issues/752.
This PR introduces a new job step in `check-licenses.yml` workflow that runs only on pull requests, and checks for newly introduced license policy violations, such as those from new dependencies or updated versions:
- if license issues are found, they are listed in the logs with actionable links to the FOSSA dashboard and Confluence [page](https://confluence.camunda.com/spaces/HAN/pages/277024795/FOSSA#FOSSA-Handlelicenseissues)
- a job annotation is added for visibility, showing `License Check: X issues found. Please check the logs and resolve before merging`
- the step does not fail for pre-existing license issues in the base branch
The job waits for the FOSSA analysis to complete, which typically takes under a …

chore(fossa): check PRs for newly introduced license issues

---

connectors/agentic-ai/pom.xml
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/JsonSchemaConstants.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/Langchain4JAiFrameworkAdapter.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/configuration/AgenticAiLangchain4JFrameworkConfiguration.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementDeserializer.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementModule.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementSerializer.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/tool/ToolSpecificationConverter.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/tool/ToolSpecificationConverterImpl.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementModuleTest.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/tool/ToolSpecificationConverterTest.java
connectors/agentic-ai/src/test/resources/jsonschema/mcp-server-everything-tools-list.json
connectors/agentic-ai/src/test/resources/jsonschema/mcp-server-filesystem-tools-list.json

Moves custom parsing code to create a `JsonSchemaElement` from a JSON string and vice-versa to a Jackson de(serializer). This is not provided by L4J, so we need to do this manually for multiple use cases:
- MCP tool definitions to L4J tool definitions
- Structured output format definitions to L4J output format definitions
In addition to moving the logic to a Jackson (de-)serializer this PR:
- adds support for reusable schema blocks via `$defs` + adds tests to deserialize JSON schemas from sample MCP server definitions
- adds support to convert from a Langchain4J `ToolSpecification` to a `ToolDefinition` (our model)

refactor(agentic-ai): implement JSON schema de(-serializing) as Jackson de(-serializer)

---

connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterImpl.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterTest.java

When the model returns no text content (e.g. tool calls only) the conversion logic currently throws an error. This fix relaxes the logic and allows responses without text content (e.g. for tool calling).

fix(agentic-ai): fix chat message converter not properly handling AI responses without text content

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/CamundaClientSaaSConfiguration.java

In https://github.com/camunda/connectors/pull/4836 we switched to the new config cache path variable.
This caused our SNAPSHOT to break on SaaS because we are constructing a custom instance of Camunda client in the SaaS environment, and we didn't explicitly apply the new credentials cache path when building it.
Before that change, it worked because we provided the lower-level env var defined in the Zeebe client which took effect even though the new property was not provided.
closes #

fix(saas): credentials cache path not applied

---

.github/workflows/CHECK_LICENSES.yml

Related to https://github.com/camunda/infra-global-github-actions/pull/417 and https://github.com/camunda/team-infrastructure/issues/752.
This PR enhances the robustness of FOSSA license violation checks on PRs.
closes #

chore(fossa): compare PR scan against most recent base commit with available FOSSA scan

---

bundle/default-bundle/src/test/resources/application.properties

Update the LocalConnectorRuntime properties so that it's compliant with the new [docker setup](https://github.com/camunda/camunda-distributions/tree/main/docker-compose/versions/camunda-8.8).

other(local): update local application properties

---

bundle/default-bundle/README.md

README update explaining how to use the new `camunda-distributions` repo instead of the deprecated `camunda-platform`

other(docs): update the LocalConnectorRuntime readme

---

connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
connectors/http/http-base/src/test/resources/squid.conf

On systems that report a very large number of maximum file handles (such as Fedora), squid will try to preallocate an array for all of them.
By setting a fixed number, the container is able to start without running out of memory
See also: <https://bugs.launchpad.net/ubuntu-docker-images/+bug/1978272/comments/1\>

fix(CustomApacheHttpClientTest): Set max file descriptors in squid

---

connectors/http/http-base/pom.xml
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoder.java
connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoderTest.java
parent/pom.xml

Several things to address the plus encoding issues:
* We explicitly define the Google HTTP client as our direct dependency, instead of using it transitively
* We bump the version and **accept the recent changes in the percent encoding logic**, changing our tests
* Implication for us: If `+` is passed as part of the path via the REST connector, we will always encode it as `%2B`.
* This means that if a customer's HTTP server expects `+` to have some kind of special meaning as a delimiter, an encoded version of it will be treated as a literal character instead
* If users want to pass the plus sign unencoded, they can still check the `Skip encoding` checkbox.
* We remove a couple of irrelevant test cases (missing protocol and invalid port will yeild a runtime error anyway or will be filtered …

fix(http-base): plus encoding issues

---

parent/pom.xml

This will solve a version conflict - gRPC deps are introduced by Camunda client and GCP cloud logging dependency. The new version of netty from the Camunda client required gRPC 1.73.0, but in our project, 1.70 from the GCP deps won.
Not sure yet whether we need to backport this.
closes https://github.com/camunda/connectors/issues/4910

fix(deps): pin grpc version

---

connector-runtime/connector-runtime-application/src/main/java/io/camunda/connector/runtime/app/ConnectorRuntimeApplication.java

[Slack discussion](https://camunda.slack.com/archives/C02JLRNQQ05/p1750069574377079)
Support ticket:
https://jira.camunda.com/browse/SUPPORT-27750
This PR removes the `@ComponentScan` annotation from the `ConnectorRuntimeApplication` class to address an issue where some beans (e.g InboundConnectorRestController) become required dependencies, even when inbound connectors are not in use.
In Camunda 8.7.3, users reported that the application fails to start if the Operate client is disabled — even though inbound connectors are not active. The error pointed to the `InboundConnectorRestController` bean, which was being picked up due to a `@ComponentScan` annotation [introduced in 8.7.](https://github.com/camunda/connectors/pull/4698/files)
@jonathanlukas first raised the issue and confirmed …

fix(self-managed): fix SM so that inbound polling can be disabled again

---

connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/BaseRabbitMqTest.java
connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/RabbitMqInboundStartEventTests.java
connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/RabbitMqOutboundTests.java
connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/BaseTest.java
connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/integration/RabbitMqIntegrationTest.java

I updated the RabbitMQ version to 4.1.1 and enabled a previously disabled test

chore(RabbitMQ): bump to version 4.1.1

---

.github/workflows/RELEASE.yaml
parent/pom.xml

Backport of https://github.com/camunda/connectors/pull/4889 to release/8.4.

[Backport release/8.4] ci(release): upgrade camunda-release-parent to 4.0.0 and switch to Central Portal deployment (#4889) 

---

.github/workflows/RELEASE.yaml
parent/pom.xml

Backport of https://github.com/camunda/connectors/pull/4889 to release/8.5.

[Backport release/8.5] ci(release): upgrade camunda-release-parent to 4.0.0 and switch to Central Portal deployment (#4889)

---

.github/workflows/RELEASE.yaml
parent/pom.xml

Backport of https://github.com/camunda/connectors/pull/4889 to release/8.6.

[Backport release/8.6] ci(release): upgrade camunda-release-parent to 4.0.0 and switch to Central Portal deployment (#4889)

---

.github/workflows/RELEASE.yaml
parent/pom.xml

Backport of https://github.com/camunda/connectors/pull/4889 to release/8.7.

[Backport release/8.7] ci(release): upgrade camunda-release-parent to 4.0.0 and switch to Central Portal deployment (#4889)

---

.github/workflows/RELEASE.yaml
parent/pom.xml

Backport of https://github.com/camunda/connectors/pull/4889 to release/8.8.

[Backport release/8.8] ci(release): upgrade camunda-release-parent to 4.0.0 and switch to Central Portal deployment (#4889)

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentToolCallingTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentUserPromptDocumentsTests.java

Temporarily disable flaky e2e tests
See https://github.com/camunda/connectors/issues/4950

test(agentic-ai): temporarily disable flaky e2e tests involving documents

---

parent/pom.xml

Undoing setting the deployment name manually as it did not work.
closes #

chore(deployment): Undo setting name manually

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentMemoryStorageTests.java

Temporarily disable flaky e2e tests involving camunda document conversation storage.
See https://github.com/camunda/connectors/issues/4950

test(agentic-ai): temporarily disable flaky e2e tests involving document conversation memory storage

---

connectors/agentic-ai/element-templates/agenticai-mcp-client-outbound-connector.json
connectors/agentic-ai/element-templates/agenticai-mcp-remote-client-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-mcp-client-outbound-connector-hybrid.json
connectors/agentic-ai/element-templates/hybrid/agenticai-mcp-remote-client-outbound-connector-hybrid.json
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpClientFunction.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpRemoteClientFunction.java

Rename MCP clients from alpha to experimental.
follow up to #4822

refactor(agentic-ai): rename alpha to experimental in MCP connectors

---

connector-sdk/document/src/main/java/io/camunda/document/store/InMemoryDocumentStore.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/BaseLangchain4JAiAgentTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentMemoryStorageTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentToolCallingTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentUserPromptDocumentsTests.java

Attempts to fix the e2e tests involving document handling by using an in memory document store, similar to what we already do in `connectors-e2e-test-http`.
closes #4950

test(agentic-ai): fix flaky e2e document handling tests

---

parent/pom.xml

increase the operate client version, which supports client_assertion. 
Released just now: https://github.com/camunda-community-hub/camunda-operate-client-java/actions
closes #

fix(operate-client): Increase version

---

connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpClientFunction.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpRemoteClientFunction.java

Remove the `experimental` from the MCP client connector name to have stable name to refer to in [hybrid mode](https://docs.camunda.io/docs/next/guides/use-connectors-in-hybrid-mode/). The name is still kept in the element template.

refactor(agentic-ai): remove experimental from MCP client connector names

---

.pre-commit-config.yaml
.tool-versions
README.md
bundle/README.md
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/DefaultInboundConnectorFactory.java

As discussed in the Architecture session this PR introduces an initial implementation of a [pre-commit](https://pre-commit.com) setup.
Due to the particular nature of Maven tools being project and not file based, I had to implement some workarounds.
Usually pre-commit would detect changed files and fail on that alone, however due to us not accepting any file arguments, we have to explicitly check via exit code.

other(util): introduce pre-commit

---

connectors/agentic-ai/pom.xml
connectors/agentic-ai/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Provide Spring Configuration Metadata for configuration exposed by the `connector-agentic-ai` module for better UX when using with a custom [Spring Boot runtime](https://docs.camunda.io/docs/next/components/connectors/custom-built-connectors/connector-sdk/#spring-boot-starter-runtime).

fix(agentic-ai): properly provide Spring configuration metadata for the agentic AI module

---

connectors/google-maps-platform/element-templates/google-maps-platform-connector.json

Fix address line always null in requests.
Bug reported here: https://camunda.slack.com/archives/C02JLRNQQ05/p1750873921679819

fix(google-maps): Fix address line null in validate address

---

renovate.json

Try use the hardcoded path instead of the `{{ sourceUrl }}` template string to circumvent the problems with changelog url
ask-infra-question: https://camunda.slack.com/archives/C5AHF1D8T/p1751383162159839

ci(renovate): update renovate.json

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorUtil.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/config/ConnectorConfigurationOverrides.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/ConnectorUtilTest.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorBeanDefinitionProcessor.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessor.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/InboundConnectorBeanDefinitionProcessorTest.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessorTest.java

Adds support to override type and timeout (outbound) for connectors registered as Spring beans.
1. Refactors the override logic into a `ConnectorConfigurationOverrides` class handling the lookup from a property source (which is still `System.getEnv()` for non-spring connectors).
- As part of this, the Optional handling in ConnectorUtil was simplified.
2. Reuses the configuration overrides for connectors registered as Spring beans in `InboundConnectorBeanDefinitionProcessor` and `OutboundConnectorAnnotationProcessor`, relying on the Spring `Environment` as property source.
3. Adds missing tests for existing logic + new tests for the Spring approach.
closes #4874

feat(runtime): Add env variable override support to connectors registered as Spring beans

---

.github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml

Fix for https://jira.camunda.com/browse/SEC-1490

other(security): fix potential security breach in our GHA

---

.github/workflows/DEPLOY_8.5_SNAPSHOTS.yaml

Add a new deploy snapshot job for 8.5-SNAPSHOT
https://github.com/camunda/connectors/issues/4978

ci(snapshot): update snapshot name to 8.5-SNAPSHOT

---

connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
connectors/agentic-ai/pom.xml
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfiguration.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java

Support Azure OpenAI models in the Agentic-AI connector. 
Two authentication mechanisms are supported:
1. API key authentication
2. [Client secret credentials](https://learn.microsoft.com/en-us/java/api/com.azure.identity.clientsecretcredentialbuilder?view=azure-java-stable) authentication
When using client secret credentials, it is mandatory to specify _Client ID_, _Client secret_, and _Tenant ID_. The _Authority host_ parameter is optional and can be used to specify a custom OAuth2 token endpoint. This can cover the use case mentioned in [this thread](https://camunda.slack.com/archives/C08BHU6JQJG/p1749644316436459).
The documentation PR will follow.
closes #4815

feat(agentic-ai): add support for Azure OpenAI models

---

bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/DataImportConfiguration.java
bundle/default-bundle/src/test/resources/data-import/QA Review Process.bpmn
connector-runtime/connector-runtime-spring/pom.xml
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientImpl.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/EmptyConfiguration.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientTest.java

The backend part has been implemented https://github.com/camunda/camunda/pull/33160.
Now we need to update Connectors to use the new filter: isLatestVersion.
closes https://github.com/camunda/connectors/issues/5047

feat(inbound): Fetch only the latest process definitions

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConnectorRuntimeApplication.java
connector-runtime/connector-runtime-application/src/main/java/io/camunda/connector/runtime/app/ConnectorRuntimeApplication.java
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/app/TestConnectorRuntimeApplication.java
connectors-e2e-test/connectors-e2e-test-base/src/main/java/io/camunda/connector/e2e/app/TestConnectorRuntimeApplication.java

Spring Boot auto-configures an ElasticSearch client going to the default URL (localhost:9200) + a health check as soon as the ES library is available on the classpath. This excludes the autoconfiguration, leading to no ES beans and no health indicator for ES being produces out of the box.
closes #5118

fix(vector-db,runtime): exclude Elasticsearch auto configuration as it auto-configures a RestClient + health check

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/AiAgentTestFixtures.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/BaseAiAgentTest.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/BaseLangchain4JAiAgentTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentElementTemplateRegressionTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentFeedbackLoopTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentLimitsTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentMcpIntegrationTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentToolCallingTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentUserPromptDocumentsTests.java

With https://github.com/camunda/camunda/pull/35105 and https://github.com/camunda/camunda/pull/35171 implemented we can remove a bit of manual variable handling from e2e tests.

test(agentic-ai): simplify e2e test setup with newly added CPT methods

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorFactory.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/DefaultInboundConnectorFactory.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorFactory.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/DefaultOutboundConnectorFactory.java
connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorDiscoveryTest.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessor.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessorTest.java

This reverts commit 04f67524e01449a60457d89d8c687bbdce75c6bd.
This approach is incompatible with #4980
closes #

refactor(connector-runtime): revert refactor outbound connector registration (#5124)

---

connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/GoogleVertexAiProviderConfiguration.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfigurationTest.java
parent/pom.xml

The latest L4J release,1.2.0, supports other Google authentication methods than the only supported method of application default credentials. We can now support service account credentials.
closes #5095

feat(agentic-ai): support service account credentials for VertexAI

---

connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/AiAgentFunction.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/AgentInitializerImpl.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/AgentExecutionContext.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/OutboundConnectorAgentExecutionContext.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/autoconfigure/AgenticAiConnectorsAutoConfiguration.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/agent/AgentInitializerTest.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/OutboundConnectorAgentExecutionContextTest.java

As a follow-up to #5130, this moves the outbound connector specific tool definition loading to the `OutboundConnectorAgentExecutionContext`, so there is no specific context handling left in the agent initializer. This will enable better decoupling of the core framework from different entry points (the outbound connector being one of them).
based on #5130 
part of #5129
closes #5165

refactor(agentic-ai): Move implementation specific tool resolution to outbound connector execution context

---

.github/workflows/ADD_TO_PROJECT.yml

closes https://github.com/camunda/team-connectors/issues/1084

chore(github): Automatically add bugs to the quality board

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java

Log the exception in ConnectorJobHandler when an error occurs. Previously, we were logging the exception's message only.
Here's an example of the new log:
```
Exception while completing job: JobForLog[key=2251799813982047, customHeaders={elementTemplateId=io.camunda.connectors.HttpJson.v2, elementTemplateVersion=11, retryBackoff=PT0S}, tenantId=<default>, bpmnProcessId=Process_1wh3upd, type=io.camunda:http-json:1, processDefinitionKey=2251799813980804, processDefinitionVersion=1, processInstanceKey=2251799813982035], message: An error occurred while executing the request, or the connection was aborted
```
closes https://github.com/camunda/connectors/issues/5117

other(logging): log the exception when an error occurs

---

parent/pom.xml

Downgrade spring zeebe as 8.5.19 is not compatible.
See [this](https://camunda.slack.com/archives/C02JLRNQQ05/p1754305698036009) discussion.

other(pom): downgrade spring zeebe due to an incompatibility

---

renovate.json

Context (internal discussion): https://camunda.slack.com/archives/C02JLRNQQ05/p1754305698036009
Spring-zeebe 8.5.19+ is incompatible with Connectors 8.5, therefore we should stick with 8.5.18 until 8.5 is EOL (October 2025). This rule can be removed after that along with the whole 8.5 branch in this config.
closes #

chore(deps): block further spring-zeebe version bumps for 8.5

---

connectors/embeddings-vector-database/element-templates/embeddings-vector-database-outbound-connector.json
connectors/embeddings-vector-database/element-templates/hybrid/embeddings-vector-database-outbound-connector-hybrid.json
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/embeddingmodel/DefaultEmbeddingModelFactory.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/embeddingstore/AzureVectorStoreFactory.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/embeddingstore/DefaultEmbeddingStoreFactory.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/AzureOpenAiEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/BedrockEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/GoogleVertexAiEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/OpenAiEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/AmazonManagedOpenSearchVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/AzureAiSearchVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/AzureCosmosDbNoSqlVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/ElasticSearchVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/OpenSearchVectorStore.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/embeddingmodel/DefaultEmbeddingModelFactoryTest.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/embeddingstore/DefaultEmbeddingStoreFactoryTest.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/fixture/EmbeddingModelProviderFixture.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/fixture/EmbeddingsVectorStoreFixture.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/model/embedding/models/GoogleVertexAiEmbeddingModelProviderTest.java

When the sealed interface implementations have a flat structure we can easily run into duplicate ID errors when the element template is generated as multiple implementations could have the same field names. One approach to avoid the errors is to customize the IDs or use different field names.
A more elegant approach is to introduce one level of hierarchy by adding the fields to an inner record and having a reference to this inner record in the main record. We should make sure the name of this field is unique in all the implementations of the sealed interface. We use this approach in the Agentic AI connector.

refactor(vector-db): better structure element template configuration

---

connectors/embeddings-vector-database/element-templates/embeddings-vector-database-outbound-connector.json
connectors/embeddings-vector-database/element-templates/hybrid/embeddings-vector-database-outbound-connector-hybrid.json
connectors/embeddings-vector-database/element-templates/versioned/embeddings-vector-database-outbound-connector-1.json
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/EmbeddingsVectorDBFunction.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/embeddingstore/DefaultEmbeddingStoreFactory.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/AzureOpenAiEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/BedrockEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/GoogleVertexAiEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/models/OpenAiEmbeddingModelProvider.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/splitter/DocumentSplitterRecursive.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/splitter/NoopDocumentSplitter.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/AmazonManagedOpenSearchVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/AzureAiSearchVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/AzureAuthentication.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/AzureCosmosDbNoSqlVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/ElasticSearchVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/ElasticsearchVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/EmbeddingsVectorStore.java
connectors/embeddings-vector-database/src/main/java/io/camunda/connector/model/embedding/vector/store/OpenSearchVectorStore.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/embeddingstore/DefaultEmbeddingStoreFactoryTest.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/fixture/EmbeddingsVectorDBRequestFixture.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/fixture/EmbeddingsVectorStoreFixture.java

To make this connector consistent with other connectors we should use camel case IDs for sealed interface implementations. 
Also, I rename `ElasticSearch` to `Elasticsearch` everywhere.
Finally I bump the connector version to 2, the version 1 being the one before the merge of [this PR](https://github.com/camunda/connectors/pull/5202).

refactor(vector-db): use camel case IDs

---

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
connectors/http/polling/element-templates/http-polling-boundary-catch-event-connector.json
connectors/http/polling/element-templates/http-polling-connector.json
connectors/http/polling/pom.xml
connectors/http/polling/src/main/java/io/camunda/connector/http/polling/HttpPollingConnector.java

IntermediateThrowEvent was missing and feel was not available for URL
I could not find other differences beyond the group renaming, new features in authentication, endpoint configurations, timeouts, activation, correlation, and deduplication.

fix(polling-connectors): IntermediateThrowEvent was missing and feel was not available for URL

---

renovate.json

fixed for real now
plus: experimental change to enable dockerfile dependency automerge, will test if it works
closes https://github.com/camunda/connectors/issues/5225
related https://github.com/camunda/connectors/issues/5227

fix(deps): renovate config fix

---

connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/JobWorkerAgentRequestHandler.java

Fixes NPE raised when the `Boolean` value is null.
Note: I did not add a dedicated test for this now as we don't have a setup ready where this can easily be added, but might add it in a follow-up.

fix(agentic-ai): fix NPE when agent context flag is null

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientImpl.java

Make process definition search page size configurable for 8.8
closes #5229
PR for 8.7 is here: https://github.com/camunda/connectors/pull/5241

chore(inbound-importer): Make process definition search page size configurable

---

connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientTest.java

Found another failing test that's only visible in the nightly runs. Not sure how the error was introduced, but the page limit is set to 0 as `@Value` inside the `SearchQueryClientImpl` does not have any effect during manual object creation.
closes #

test(runtime): fix search query client test

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java
connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientImpl.java
connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientTest.java

Follow-up for https://github.com/camunda/connectors/pull/5264#issuecomment-3206293967
closes #

fix(runtime): move Value to the configuration

---

.github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml

This pull request makes a small update to the pull request name validation regex in the `.github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml` workflow. The change improves the accuracy of the conventional commit format check by refining how the optional scope is matched in the regex.
Previous pattern examples: https://regex101.com/r/EJ12Nk/1
New pattern examples: https://regex101.com/r/MHuXbC/2

fix(ci): update regexp for pull_request name check

---

bundle/default-bundle/src/test/resources/application.properties

a duplicate camunda.client.prefer-rest-over-grpc was present in application.properties file
This was introduced [here](https://github.com/camunda/connectors/pull/5269/files)

fix(application.properties): a duplicate camunda.client.prefer-rest-over-grpc was present in application.properties file

---

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/ActivityLogTag.java
connectors/http/polling/src/main/java/io/camunda/connector/http/polling/HttpPollingConnector.java

- Add a meaningful message to automatic activity logs that are triggered on health status updates (otherwise they appear empty in the console)
- Only add those activity logs when the status change is new (otherwise they are logged all the time for some connectors)
- Change polling connector name to the format used in other connectors.
closes #

fix(runtime): add message to health status update activity logs

---

.github/workflows/RUN_UNIQUET.yml
connector-templates.json
element-template-generator/npm/src/build_element_template_array_json_files.sh
ignore-templates.json
uniquet/src/main/java/io/camunda/connector/uniquet/command/UniquetCommand.java
uniquet/src/main/java/io/camunda/connector/uniquet/core/ConnectorsFinder.java
uniquet/src/main/java/io/camunda/connector/uniquet/core/IndexWriter.java
uniquet/src/test/java/io/camunda/connector/uniquet/core/ConnectorsFinderTest.java
uniquet/src/test/java/io/camunda/connector/uniquet/core/IndexWriterTest.java
uniquet/src/test/resources/ignore-templates.json

Removed idp connector from npm package and uniquET.
closes #5313

fix(et): Remove idp base connectors from publishing

---

connectors/embeddings-vector-database/src/main/java/io/camunda/connector/embeddingstore/AzureVectorStoreFactory.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/embeddingstore/DefaultEmbeddingStoreFactoryTest.java
parent/pom.xml

Bump the version of `langchain4j` to `1.4.0` and adapt the code.
In the new version of `langchain4j` there has been `[some work](https://github.com/langchain4j/langchain4j/pull/3463)` on `AzureCosmosDbNoSqlEmbeddingStore` in order to expand its functionality. Now a `CosmosClient` is created inside the constructor, and so there is no need to pass an in instance of `CosmosClient` to the builder. The downside of this is that we cannot call the `close()` method on the instance of `CosmosClient` in order to release the resources.

chore(deps): bump langchain4j to 1.4.0

---

connectors/embeddings-vector-database/src/main/java/io/camunda/connector/embeddingstore/AzureVectorStoreFactory.java
connectors/embeddings-vector-database/src/test/java/io/camunda/connector/embeddingstore/DefaultEmbeddingStoreFactoryTest.java
parent/pom.xml

This reverts commit 56745f0c64c7685aba7ae39fba1d7c1f7ac025b1.
There is a [bug](https://github.com/langchain4j/langchain4j/issues/3634) in L4J when we retrieve embeddings. We cannot use the new version of L4J until the bug is fixed.

fix: revert "deps(vector-db): bump langchain4j to 1.4.0 (#5330)"

---

connectors/agentic-ai/element-templates/agenticai-aiagent-job-worker.json
connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-job-worker-hybrid.json
connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/OpenAiCompatibleProviderConfiguration.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/ProviderConfiguration.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java

We currently have the OpenAI configuration including support for a custom endpoint + custom parameters, but it makes the configuration a bit cumbersome as:
- custom endpoint/parameters are not needed when using OpenAI
- API key is required, but might not be needed when using an OpenAI compatible endpoint (for example Ollama for local testing)
- by looking at the model selection, it might not be obvious that we support OpenAI compatible APIs
In this PR we create a dedicated config entry "OpenAI Compatible", exposing the following configuration options:
- API Endpoint (required)
- API Key (optional)
- HTTP Headers (optional)
On the model configuration, it exposes the same properties as we currently expose for OpenAI, plus a "Custom parameters" property accepting a `Map<String, Object>` of …

feat(agentic-ai): add an OpenAI compatible provider

---

.github/workflows/ENFORCE_QA_APPROVAL.yml

PR changes succeeded [here](https://github.com/camunda/connectors/actions/runs/17543923710)
I think we need to force-merge this, as we can use `pull_request` instead of `pull_request_target` to fix this, but there is nothing similar for `pull_request_review`. Who has permissions to do this?

chore(ci): Fix QA workflow

---

bundle/default-bundle/src/test/resources/application-local.properties

Fixing a issue with the local setup. Do we also need to make this change in the application.properties file? I am not sure if the port also changed in general.

chore(local-setup): Fix rest address

---

bundle/camunda-saas-bundle/pom.xml
bundle/default-bundle/pom.xml
connector-runtime/connector-runtime-application/pom.xml

Stop publishing executable bundles to maven central
related to https://github.com/camunda/connectors/issues/5328

other(build): stop publishing bundle jars to central

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/jobworker/BaseL4JAiAgentJobWorkerTest.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/outboundconnector/BaseL4JAiAgentConnectorTest.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors-mcp.bpmn
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors.bpmn
connectors/agentic-ai/examples/ai-agent-chat-mcp/ai-agent-chat-with-mcp.bpmn
connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-with-tools.bpmn
connectors/agentic-ai/examples/fraud-detection/fraud-detection-process.bpmn

Define a `toolCallResult` local variable within the ad-hoc sub-process to avoid variable being handled in process scope and interfering with individual results. This is needed to address how the multi-instance is handled in combination with the new inner instance starting from 8.8.0-alpha8. 
- Updates examples to define an empty `toolCallResult` variable
- Updates e2e tests to cover testing parallel tool calls of the same tool
Initially reported as core regression in https://github.com/camunda/camunda/issues/37866, but it turns out this was accidentally working until now (see @remcowesterhoud's comments on the issue). The proper fix is to treat the tool call result as local variable.
Slack conversation: https://camunda.slack.com/archives/C08BFEFMYP4/p1757489049960369

fix(agentic-ai): fix service task based examples to define toolCallResult as local variable

---

connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/PromptConfiguration.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/request/PromptConfigurationTest.java

Makes the user prompt text mandatory by validating it on the request object. While there may be more detailed checks (e.g. only validate it based on history/when it is really needed (e.g. first interaction, follow-up interactions), this should catch most misconfiguration cases early.
closes #5393

fix(agentic-ai): Make user prompt mandatory

---

.github/workflows/DEPLOY_8.7_SNAPSHOTS.yaml
.github/workflows/helm-git-refs.json

changing helm chart dir name for correct version in helm-git-refs.json from in `release/8.7`
`camunda-platform-alpha` > `camunda-platform-8.7`
see [slack](https://camunda.slack.com/archives/C05K4TAEPDW/p1757505356756499)
closes #

fix: helm chart version branch release/8.7

---

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java
bundle/camunda-saas-bundle/src/main/resources/application.properties

This pull request introduces a minor update to the allowed roles for authentication in the inbound instances security configuration. The change adds `supportagent` to the list of allowed roles, enabling users with this role to access the relevant functionality.
Authentication and authorization:
* Updated the `allowedRoles` property in `InboundInstancesSecurityConfiguration` to include the `supportagent` role.
* Modified the `application.properties` configuration file to add `supportagent` to the `camunda.connector.auth.allowed.roles` property.

other(debug): Add support agents to the allowed users for manage and run

---

connectors/agentic-ai/AI_AGENT.md
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterImpl.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/AgentResponse.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterTest.java

Reduces to the metadata stored from a LLM response to only include ID and token usage. This avoids bloat on the stored conversation (see linked issue for an example).
closes #5425

fix(agentic-ai): filter chat response metadata stored as part of conversation

---

connector-commons/connector-utils/pom.xml
connector-commons/connector-utils/src/main/java/io/camunda/connector/util/reflection/ReflectionUtil.java
connector-commons/pom.xml
connector-runtime/connector-runtime-core/pom.xml
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorConfigurationUtil.java
connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/operation/ConnectorOperations.java
element-template-generator/core/pom.xml
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedDocsGenerator.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedTemplateGenerator.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/OperationBasedConnectorUtil.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplateGenerationContextUtil.java
element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java
parent/pom.xml

This pull request introduces a new `connector-utils` module to centralize and share utility code, specifically reflection utilities, across multiple connector-related projects. The main changes involve moving the `ReflectionUtil` class and its usages from the SDK/core module to the new `connector-utils` module, and updating dependencies and imports throughout the codebase to use this new module.
**Module and Dependency Updates:**
* Added the new `connector-utils` Maven module, including its own `pom.xml` and necessary dependencies such as Jackson and JUnit, and registered it in the parent and commons project files. [[1]](diffhunk://#diff-6a944e89c21b936f5d178265f0d5fa3532e4069415547609d637b33e36e2748fR1-R50) [[2]](diffhunk://#diff-95c89c0e6afb14c222d0a152f86426606eedf5cf8008476512fe67af31a …

chore(refactoring): Extract ReflectionUtil into dedicated module

---

.github/workflows/CREATE_RELEASE_BRANCH.yml
renovate.json

Rename the next release branch to `alpha` - and simplify the renovate config accordingly.
closes https://github.com/camunda/connectors/issues/5409

chore(ci): rename next release branch to alpha; simplify renovate config

---

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/jobworker/L4JAiAgentJobWorkerResponseHandlingTests.java
connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/outboundconnector/L4JAiAgentConnectorResponseHandlingTests.java
connectors/agentic-ai/AI_AGENT.md

Follow up to #5434 to fix missed e2e tests.
closes #5434

fix(agentic-ai): adapt e2e tests for updated response handling (not explicitely setting TEXT)

---

.github/workflows/DEPLOY_8.5_SNAPSHOTS.yaml
.github/workflows/helm-git-refs.json

changing helm chart dir name for correct version in helm-git-refs.json from in `release/8.5`
`camunda-platform-alpha` > `camunda-platform-8.5`
see [slack](https://camunda.slack.com/archives/C05K4TAEPDW/p1757505356756499)
closes #

fix: helm chart version branch release/8.5

---

.github/workflows/NIGHTLY_E2E.yml

This pull request makes a small update to the artifact naming convention in the nightly E2E workflow. The change ensures that the uploaded artifact name includes the branch name, which helps distinguish reports from different branches.
* The `name` field for the uploaded artifact in `.github/workflows/NIGHTLY_E2E.yml` now includes the branch name using `${{ matrix.branch }}`

ci(nightly): fix the uploaded test result names

---

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
connector-runtime/spring-boot-starter-camunda-connectors/pom.xml
connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTest.java
connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java

This bug was reported: https://github.com/camunda/connectors/issues/5355
I investigated it and figured out it only happens in 8.6 as it was already fixed with this PR, but the backport to 8.6 failed:
https://github.com/camunda/connectors/pull/3518
So I just backported this PR to 8.6 and removed document releated switch-case-case.
closes #5355

fix(webhook): Fix webhook and possible http client nullpointer exception

---

.github/workflows/INTEGRATION_TEST.yml

There are noisy alerts lately due to these failing helm chart integration tests. These are not expected to pass on main, since main of connectors (and camunda core) is referring to 8.9 builds and the helm chart is only on 8.8 at the moment.
This PR adds a conditional disabling the helm integration tests on main.
closes #

fix: disable helm integration tests for main because we do not have a 8.9 helm chart yet

---

connectors/agentic-ai/pom.xml
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/a2a/client/A2AClientRequestHandlerImpl.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/a2a/client/A2aClientFunction.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/a2a/client/A2aClientRequestHandler.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/a2a/client/configuration/A2aClientConfiguration.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/a2a/client/model/result/A2aAgentCardResult.java
connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/autoconfigure/AgenticAiConnectorsAutoConfiguration.java
connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/a2a/client/A2AClientRequestHandlerImplTest.java

Implement the Fetch Agent Card operation using the [A2A Java SDK](https://github.com/a2aproject/a2a-java). Use the server URL and the optional custom agent card location from the input configuration.
closes #5499

feat(agentic-ai): Implement fetch agent card operation
