README.md
Adjust links from SDK runtime to Spring Zeebe
=> docs: adjust references to Connector runtime

runtime/Dockerfile, runtime/README.md
Fixes https://github.com/camunda-community-hub/spring-zeebe/issues/263
=> Bump spring zeebe to latest version

bundle/Dockerfile, bundle/README.md
=> chore(deps): update Connector Runtime to 0.3.1

runtime/Dockerfile
Hot fix for connector duplicate bug
=> Bump to Spring Zeebe 8.1.6

bundle/Dockerfile, bundle/README.md
=> chore(deps): bump Runtime to `0.3.2`

.github/workflows/RELEASE.yaml
=> gha: bump GHA version

README.md, bundle/README.md
=> docs: update readme

bundle/mvn/pom.xml
=> deps: bump runtime to `8.1.10`

connectors/http-json/src/main/java/io/camunda/connector/http/HttpJsonFunction.java
Update for bearer token sent with quotes - rest connector
=> fix: update for bearer token sent with quotes - rest connector

connectors/github/README.md, connectors/github/element-templates/github-webhook.json
Moved content from https://github.com/camunda/connector-github to fit in MonoRepo structure
=> feat(github): Added Github webhook element-template

connectors/google-drive/element-templates/google-drive-connector.json, connectors/kafka/element-templates/kafka-connector.json, connectors/sns/element-templates/aws-sns-connector.json, connectors/sqs/element-templates/aws-sqs-connector.json
fix(templates): add optional flags for additional properties
closes #120
=> fix(templates): add optional flags for additional properties

connectors/http-json/README.md, connectors/http-json/element-templates/http-json-connector.json
Simplify authentication types
#137
=> feat: rest connector - simplify authentication types

connectors/github/element-templates/github-webhook-connector.json, connectors/webhook-connector/element-templates/webhook-connector.json
Related to https://github.com/camunda/team-connectors/issues/275
=> chore(webhook, element template): rename labels in inbound webhook

connectors/github/LICENSE.txt, connectors/webhook-connector/LICENSE.txt
=> docs(license): added missing license files

connectors/microsoft-teams/pom.xml, connectors/microsoft-teams/src/main/java/io/camunda/connector/model/request/channel/SendMessageToChannel.java, connectors/microsoft-teams/src/main/java/io/camunda/connector/model/request/chat/SendMessageInChat.java
Fix for encrypted emoji in chat message and channel message
closes #170
=> fix: encrypted emoji in chat message and channel message

connector-archetype-internal/pom.xml
fix(archetype): remove xml descriptor
=> fix(archetype): remove xml descriptor

bundle/README.md, pom.xml
=> deps: bump SDK to 0.5.0

connectors/github/element-templates/github-webhook-connector.json, connectors/webhook-connector/element-templates/webhook-connector.json
docs(inbound): added doc references to inbound templates
Refers:
- https://github.com/camunda/team-connectors/issues/275
=> docs(inbound): added doc references to inbound templates

connectors/uipath/LICENSE.txt, connectors/uipath/README.md, connectors/uipath/element-templates/uipath-custom-template.json
=> uipath: add new version for custom template

connectors/uipath/element-templates/uipath-connector.json
fix: cosmetic CX changes to UIPath template
=> fix: cosmetic CX changes to UIPath template

.github/workflows/RELEASE.yaml
=> fix(ci): fix invalid settings.xml config

connectors/uipath/element-templates/uipath-connector.json
chore(uipath): fix UIPath item ID fetch
=> chore(uipath): fix UIPath item ID fetch

connectors/http-json/element-templates/http-json-connector.json
Align URL pattern with backend
=> fix(http,template): align URL pattern with backend

connectors/microsoft-teams/element-templates/microsoft-teams-connector.json
fix(msteams): add FEEL properties to inputs
=> fix(msteams): add FEEL properties to inputs

pom.xml
deps(spring-zeebe): bump to 8.1.16
=> deps(spring-zeebe): bump to 8.1.16

pom.xml
deps(bump): Bump SDK to 0.6.0-alpha4
=> deps(bump): Bump SDK to 0.6.0-alpha4

connectors/blue-prism/LICENSE.txt, connectors/blue-prism/README.md, connectors/blue-prism/element-templates/blue-prism-connector.json
chore(blue prism): introduce connector
closes #280
=> chore(blue prism): introduce connector

connectors/sendgrid/src/main/java/io/camunda/connector/sendgrid/SendGridTemplate.java, connectors/sendgrid/src/test/resources/requests/send-mail-by-template-success-cases.json, connectors/sendgrid/src/test/resources/requests/send-mail-with-content-success-cases.json
fix(sendgrid): fix issue with array persistance
Ref: https://camunda.slack.com/archives/C02JLRNQQ05/p1676474912796959
=> fix(sendgrid): fix issue with array persistance

.github/workflows/DEPLOY.yaml, .github/workflows/RELEASE.yaml
Disables Provenance attestation for docker build.
related to #326
=> fix(docker): disable provenance attestation for images

connectors/power-automate/LICENSE.txt, connectors/power-automate/README.md, connectors/power-automate/element-templates/power-automate-connector.json
Added the power-automate element template with the license file.
https://github.com/camunda/product-hub/issues/768
closes #
=> feat: add Power Automate connector template

pom.xml
Bumps Connector SDK version to 0.7.0.
=> chore: bump SDK to 0.7.0

bundle/README.md, connectors/http-json/README.md
Minor updates to the bundle docs:
- Added new connectors to the bundle description
- Added references to template-only connectors in http-json readme
=> chore(docs): update docs for 0.17.0 release

bundle/mvn/default-bundle/pom.xml, pom.xml
Includes the fixes for:
- Metrics https://github.com/camunda-community-hub/spring-zeebe/issues/296
- Inconsistent behavior for disabled webhook https://github.com/camunda-community-hub/spring-zeebe/issues/370
=> chore(deps): bump spring zeebe to 8.2.0-alpha2

connectors/operate/LICENSE.txt, connectors/operate/README.md, connectors/operate/element-templates/operate-connector.json
=> Camunda Operate Connector

connectors/github-outbound/LICENSE.txt, connectors/github-outbound/README.md, connectors/github-outbound/element-templates/github-connector.json
GitHub outbound connector
Personal access token: ~~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~~ Revoked. Ask for it :) 
Owner: camunda-test
Repository name: test
=> feat: add github outbound connector

connectors/sqs/element-templates/aws-sqs-connector.json, connectors/sqs/src/main/java/io/camunda/connector/SqsConnectorFunction.java, connectors/sqs/src/main/java/io/camunda/connector/model/QueueRequestData.java, connectors/sqs/src/main/java/io/camunda/connector/model/QueueType.java, connectors/sqs/src/test/java/io/camunda/connector/SqsConnectorFunctionParametrizedTest.java, connectors/sqs/src/test/resources/requests/fail-test-cases.json, connectors/sqs/src/test/resources/requests/success-test-cases.json
Add support for FIFO related properties by introducing a type which defaults to standard queue in case of missing property.
closes camunda/team-connectors/issues/368
https://user-images.githubusercontent.com/1607241/230035567-2b1d2bd2-4130-4522-a7a0-8fbde641015e.mov
=> 368 sqs connector fifo support

pom.xml
deps(sdk): update to latest SDK 0.8.0-alpha2
=> deps(sdk): update to latest SDK 0.8.0-alpha2

pom.xml
deps: update SDK and runtime to latest
=> deps: update SDK and runtime to latest

pom.xml
deps(spring-zeebe): bump runtime to 8.2.0-alpha5
=> deps(spring-zeebe): bump runtime to 8.2.0-alpha5

connectors/sqs/element-templates/aws-sqs-connector.json
Add and bump sqs connector version
closes https://github.com/camunda/team-connectors/issues/368
=> fix(docs): Add and bump sqs connector version

connectors/asana/LICENSE.txt, connectors/asana/README.md, connectors/asana/element-templates/asana-connector.json
chore(asana): introduce Asana protocol connector
known issues: URL-based (get task by ID, delete task) - not evaluated by the element template; create project - body not evaluated
=> chore(asana): introduce Asana protocol connector

connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/RabbitMqFunctionTest.java, pom.xml
deps: bump to 0.8.0 SDK and 8.2.0 Runtime
=> deps: bump to 0.8.0 SDK and 8.2.0 Runtime

.github/workflows/RELEASE-FOCAL.yaml, bundle/mvn/default-bundle/Dockerfile-focal
Ref: https://github.com/camunda/connectors-bundle/issues/442
=> chore(experimental,focal image): introducing focal statement as per support case

pom.xml
Includes a fix for https://github.com/camunda/connector-sdk/issues/429
related to https://github.com/camunda/team-connectors/issues/381
=> chore(deps): bump sdk to 0.8.1

bundle/README.md
chore(connectors): updated readme for docker bundles
=> chore(connectors): updated readme for docker bundles

spring-boot-starter-camunda-connectors/README.md
Adjust the example dependency to the Connector Runtime to the new module.
n/a
=> docs: adjust example dependencies in README

pom.xml
=> chore(deps): bump sdk to 0.9.0-alpha1

pom.xml
=> chore(deps): bump sdk to 0.9.0

connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json
Kafka element template for inbound intermediate event
https://github.com/camunda/team-connectors/issues/352
=> feat: add Kafka inbound intermediate element template

connectors/connectors-common-library/src/main/java/io/camunda/connector/common/model/CommonResult.java
=> chore: Fix toString implementation

bundle/default-bundle/src/main/resources/application.properties
fix(default bundle): returned to port 8080
=> fix(default bundle): returned to port 8080

connectors/google-drive/element-templates/google-drive-connector.json
Fix Google Drive connector template text style in order to be similar with Google Sheets connector template
#589 
closes #
=> Fix text style

connectors/google-sheets/LICENSE.txt, connectors/google-sheets/README.md, connectors/google-sheets/connector.yml, connectors/google-sheets/pom.xml, connectors/google-sheets/src/main/java/io/camunda/connector/gsheets/GoogleSheetsFunction.java, connectors/google-sheets/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction, connectors/pom.xml, pom.xml
Set up new module for Google Sheets connector
[](https://github.com/camunda/product-hub/issues/1157)
closes #
=> Set up the module for Google Sheets Connector

connectors/google-sheets/element-templates/google-sheets-connector.json
Add new template for Google Sheets connector
https://github.com/camunda/connectors-bundle/assets/131355515/264510f8-68ce-4c98-80d0-8cb12e35cd3d
#555 
closes #
=> add google sheets connector template

spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/ActiveInboundConnector.java, spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/ActiveInboundConnectorQuery.java, spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java, spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorRestController.java, spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorProperties.java, spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManagerTest.java
Provide health status as part of the active inbound connector response.
Relates to camunda/connector-sdk/issues/462
=> feat(health): Report inbound connector health

connectors/connectors-common-library/src/main/java/io/camunda/connector/common/services/HTTPProxyService.java
Hides the exception data on proxy function authentication error. The error message is visible in Operate, and the message potentially contains info about the internals of the SaaS platform.
closes https://github.com/camunda/team-connectors/issues/414
=> fix: hide http proxy auth error behind a generic exception

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java, connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java
Report Kafka inbound connector health.
relates to #621
=> feat(health): Report inbound health for Kafka & RabbitMQ

connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java, connectors/sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java, spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java, spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorRestController.java, spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManagerTest.java
=> feat(health): Report failed inbound connector activations as DOWN

connectors/sns/element-templates/aws-sns-inbound-intermediate.json
feat(sns): intermediate catch event
=> feat(sns): intermediate catch event

connectors/google/google-sheets/README.md, connectors/google/google-sheets/element-templates/google-sheets-connector.json, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/impl/CreateRowOperation.java, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/impl/CreateWorksheetOperation.java, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/impl/DeleteWorksheetOperation.java, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/impl/GetRowByIndexOperation.java, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/impl/GetWorksheetDataOperation.java
Add relevant links to the documentation
closes #421
=> chore: add links to the documentation

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/ActiveInboundConnectorResponse.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorRestController.java
=> feat(inbound): Report the process version via the inbound connector API

connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json, connectors/kafka/element-templates/kafka-inbound-connector.json
=> feat(kafka inbound): fix documentation links

connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/model/impl/AwsBaseConfiguration.java, connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/model/impl/AwsBaseRequest.java, connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/LambdaConnectorFunction.java, connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/model/FunctionRequestData.java, connectors/aws/aws-lambda/src/test/resources/requests/lambda-connector-fail-test-case.json, connectors/aws/aws-lambda/src/test/resources/requests/lambda-connector-success-test-case.json
Fix how AWS region is resolved in a backwards compatible way.
closes #733
=> fix(aws-lambda): Fix how AWS region is resolved

connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/model/FunctionRequestData.java
=> fix(secret): Add missing secret annotation.

connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/model/FunctionRequestData.java
Reverts camunda/connectors-bundle#736
=> Revert "fix(secret): Add missing secret annotation."

connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/model/FunctionRequestData.java
=> 733 missing secret annotation spotless

connectors/webhook/element-templates/webhook-connector-intermediate.json, connectors/webhook/element-templates/webhook-connector-start-event.json, connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java, connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java, connectors/webhook/src/main/java/io/camunda/connector/inbound/signature/HMACSignatureValidator.java, connectors/webhook/src/main/java/io/camunda/connector/inbound/utils/HttpMethods.java, connectors/webhook/src/test/java/io/camunda/connector/inbound/HttpWebhookExecutableTest.java
Added HTTP method to properties
closes #610
=> feat(webhook): added HTTP method to properties

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImportConfiguration.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java, connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspectorUtilTests.java, connector-runtime/connector-runtime-spring/src/test/resources/bpmn/multi-webhook-collaboration.bpmn, connector-runtime/connector-runtime-spring/src/test/resources/bpmn/multi-webhook-start-collaboration.bpmn, connector-runtime/connector-runtime-spring/src/test/resources/bpmn/single-webhook-collaboration.bpmn, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java
=> fix(inbound): Support multiple start events for collaboration diagrams.

connectors/kafka/pom.xml, pom.xml
=> fix(deps): Fix snappy CVE dependency by upgrading dependency.

connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java, connectors/slack/src/test/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutableTest.java
feat(slack,inbound): slash command support
=> feat(slack,inbound): slash command support

bundle/camunda-saas-bundle/Dockerfile, bundle/default-bundle/Dockerfile
closes camunda/team-connectors/issues/430
=> fix(deps): Use recommended docker base images.

connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java, connectors/slack/src/main/java/io/camunda/connector/slack/inbound/model/SlackWebhookProcessingResult.java, connectors/slack/src/test/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutableTest.java
fix(slack,inbound): fix slash command response
=> fix(slack,inbound): fix slash command response

bundle/camunda-saas-bundle/Dockerfile, bundle/default-bundle/Dockerfile
closes camunda/team-connectors/issues/430
=> fix(deps): Use alpine docker base images.

connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java
fix(slack,inbound): return explicit data from slack
=> fix(slack,inbound): return explicit data from slack

.github/workflows/DEPLOY.yaml, bundle/camunda-saas-bundle/Dockerfile, bundle/default-bundle/Dockerfile, bundle/default-bundle/start.sh
closes https://github.com/camunda/team-connectors/issues/430
=> Revert docker image updates as alpine failes to start.

connectors/slack/element-templates/slack-inbound-intermediate.json, connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java, connectors/slack/src/test/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutableTest.java
fix(slack,inbound): corrected return type for command
=> fix(slack,inbound): corrected return type for command

connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector.json
=> chore(event-bridge): reworked descriptions

bundle/README.md
- Will update versions here: https://hub.docker.com/r/camunda/connectors-bundle
- Also adds several missing connectors
=> chore: refresh docker readme connector list

connectors/aws/aws-sns/element-templates/aws-sns-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
Temporary fix for support request until 0.21.0 release.
Rollback nonce at: https://github.com/camunda/connectors-bundle/issues/849
Modeler PR: https://github.com/camunda/web-modeler/pull/5323
=> fix(sns): fixes SNS regression

connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveService.java, connectors/google/google-drive/src/test/resources/requests/file-success-test-cases.json
=> fix(gdrive): fix regression

connectors/twilio/element-templates/twilio-webhook-intermediate-connector.json
=> fix(twilio): fix hidden name

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java, pom.xml
=> Bump rc sdk

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java
=> fix: split secret errors and json errors in the connector context

connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/ObjectMapperSupplier.java, connectors/aws/aws-dynamodb/src/test/java/io/camunda/connector/aws/dynamodb/operation/item/DeleteItemOperationTest.java, connectors/aws/aws-dynamodb/src/test/java/io/camunda/connector/aws/dynamodb/operation/item/GetItemOperationTest.java
fix(sns,sqs): fix json serialization
Regression test passed on SM
=> fix(sns,sqs): fix json serialization

pom.xml
=> chore: bump SDK to 0.11.0

bundle/README.md
=> Bump versions in dockerfile readme

connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
=> fix(sqs):backported region

connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/model/AwsLambdaResult.java, connectors/aws/aws-lambda/src/test/java/io/camunda/connector/awslambda/BaseTest.java, connectors/aws/aws-lambda/src/test/java/io/camunda/connector/awslambda/model/AwsLambdaResultTest.java
fix(lambda): fixes correct JSON parsing of the payload
=> fix(lambda): fixes correct JSON parsing of the payload

pom.xml
=> Bump SDK to 0.11.1 patch

connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
fix(sqs):removed nonse from SQS connector
=> fix(sqs):removed nonse from SQS connector

pom.xml
=> Bump SDK to 0.11.2

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
Kafka inbound connector was only able to activate the subscription for limited amount of connector instances, due to the usage of CompletableFuture which uses ForkJoinPool, which has a limitation of how many threads it can run parallelly. [Documentation](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html) says "[...] parallelism level; by default, equal to the number of available processors"
This solution uses ExecutorService instead of ForkJoinPool to eliminate the limitations of threads.
https://github.com/camunda/connectors-bundle/issues/845
closes #
https://github.com/camunda/connectors-bundle/issues/845
=> fix: use ExecutorService instead of default ForkJoinPool

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java, connectors/slack/src/main/java/io/camunda/connector/slack/inbound/model/SlackWebhookProcessingResult.java
chore(sdk): removed unnecessary API usage
Fixes build from https://github.com/camunda/connector-sdk/pull/507
=> chore(sdk): removed unnecessary API usage

connectors/webhook/element-templates/webhook-connector-intermediate.json, connectors/webhook/element-templates/webhook-connector-start-event.json
To mirror the changes from the[ PR in web-modeler.](https://github.com/camunda/web-modeler/pull/5422)
=> chore: add documentation links to webhook connector templates

connectors/whatsapp/LICENSE.txt, connectors/whatsapp/README.md, connectors/whatsapp/element-templates/whatsapp-connector.json, connectors/whatsapp/element-templates/whatsapp-webhook-connector.json, connectors/whatsapp/element-templates/whatsapp-webhook-intermediate-connector.json
feat(whatsapp): introduced whatsapp connector
=> feat(whatsapp): introduced whatsapp connector

connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
chore: made controller tests more explicit
=> chore: made controller tests more explicit

connectors/whatsapp/element-templates/whatsapp-webhook-connector.json, connectors/whatsapp/element-templates/whatsapp-webhook-intermediate-connector.json
feat(whatsapp): temporary turn off validation
=> feat(whatsapp): temporary turn off validation

connector-sdk/core/src/main/java/io/camunda/connector/api/annotation/Secret.java
This will fix the CI pipeline.
=> fix: remove broken javadoc link

connector-runtime/connector-runtime-application/src/main/resources/application.properties, connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/ConnectorsObjectMapperSupplier.java
=> chore(config): Increase number of job worker threads

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorFactory.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/config/ConnectorConfiguration.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/config/InboundConnectorConfiguration.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/DefaultInboundConnectorFactory.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/DefaultOutboundConnectorFactory.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorDiscovery.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorDiscoveryTest.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorAnnotationProcessor.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessor.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/app/TestSpringBasedInboundConnector.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/app/TestSpringBasedOutboundConnector.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/SpringBasedInboundConnectorTest.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/outbound/SpringBasedOutboundConnectorTest.java
=> feat(spring): Support spring bean based connectors

.github/workflows/RELEASE.yaml
Fix "set next snapshot version" step of the release pipeline after the project structure adjustment.
=> fix(build): next snapshot version step

bundle/camunda-saas-bundle/pom.xml, bundle/default-bundle/pom.xml, bundle/pom.xml, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java, connector-sdk/core/pom.xml, connector-sdk/jackson-datatype-feel/pom.xml, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java, connector-sdk/test/pom.xml, connector-sdk/validation/pom.xml, parent/pom.xml, pom.xml, secret-providers/gcp-secret-provider/pom.xml
closes camunda/team-connectors/issues/470
=> feat(conversion): Convert correlation key always to string

parent/pom.xml, pom.xml
=> rollback module adjustment

connectors/aws/aws-sns/connector.yml, connectors/aws/aws-sns/element-templates/aws-sns-connector.json, connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/outbound/SnsConnectorFunction.java, connectors/aws/aws-sqs/connector.yml, connectors/aws/aws-sqs/element-templates/aws-sqs-connector.json, connectors/aws/aws-sqs/src/main/java/io/camunda/connector/outbound/SqsConnectorFunction.java
fix(sqs,sns): removes nonce field
=> fix(sqs,sns): removes nonce field

connectors/aws/aws-sns/element-templates/aws-sns-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-connector.json
feat(sns,sqs): bump base version of templates
=> feat(sns,sqs): bump base version of templates

connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/ObjectMapperSerializationTest.java
=> fix: jackson initialization order

connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java, connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java
=> fix: nested scala maps

connectors/connectors-common-library/src/main/java/io/camunda/connector/common/services/HTTPProxyService.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/common/model/RabbitMqMessage.java
=> fix: remove scala module from REST and RabbitMQ connectors

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunction.java
=> fix: remove scala module from Kafka connector

connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/ObjectMapperSupplier.java
fix: AWS scala maps serialization
=> fix: AWS scala maps serialization

connectors/microsoft-teams/src/main/java/io/camunda/connector/suppliers/ObjectMapperSupplier.java, connectors/microsoft-teams/src/test/java/io/camunda/connector/model/request/chat/GetChatTest.java
fix: MS Teams scala maps serialization
=> fix: MS Teams scala maps serialization

connector-sdk/element-template-generator/pom.xml, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/annotation/ElementTemplate.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/annotation/TemplateProperty.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/annotation/TemplateSubType.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/ElementTemplateGenerator.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/OutboundElementTemplateGenerator.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/util/ReflectionUtil.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/util/TemplatePropertiesUtil.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/util/TemplatePropertyAnnotationUtil.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/BooleanProperty.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/DropdownProperty.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/ElementTemplateBase.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/HiddenProperty.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplate.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplateBuilder.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/Property.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyBuilder.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/PropertyGroup.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/StringProperty.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/TextProperty.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/OutboundTemplateGeneratorTest.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/example/MyConnectorFunction.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/example/MyConnectorInput.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/util/TemplatePropertiesUtilTest.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/dsl/OutboundElementTemplateSerializationTest.java, connector-sdk/element-template-generator/src/test/resources/test-element-template-simplified.json, connector-sdk/element-template-generator/src/test/resources/test-element-template.json
Element template generator implementation.
See tests for usage examples.
closes https://github.com/camunda/team-connectors/issues/443
=> feat: Annotation-based template generator

.github/workflows/CODEQL.yml
Set up CodeQL Github code analyzer for security scans.
No related issue.
closes #
=> feat: add analyze job (github codeql)

connector-sdk/element-template-generator-maven-plugin/README.md, connector-sdk/element-template-generator-maven-plugin/pom.xml, connector-sdk/element-template-generator-maven-plugin/src/main/java/io/camunda/connector/generator/ElementTemplateGeneratorMojo.java, connectors/pom.xml, pom.xml
Maven plugin that includes template generation into the build lifecycle.
related to https://github.com/camunda/team-connectors/issues/482
=> Template generator Maven plugin

connector-sdk/element-template-generator/README.md, connector-sdk/element-template-generator/pom.xml, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/processor/FieldProcessor.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/processor/JakartaValidationFieldProcessor.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/processor/TemplatePropertyFieldProcessor.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/core/util/TemplatePropertiesUtil.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/OutboundTemplateGeneratorTest.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/example/MyConnectorInput.java
Support generating validation constraints based on Jakarta Bean Validation API.
Also some new documentation has been added, clarifying how the generator works and what rules are applied by default.
closes https://github.com/camunda/team-connectors/issues/490
=> feat(generator): support validation annotations

.github/workflows/RELEASE.yaml, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelDeserializer.java, connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelDeserializerTest.java, connectors/kafka/element-templates/avro/kafka-connector.json, connectors/kafka/element-templates/avro/kafka-inbound-connector-intermediate.json, connectors/kafka/element-templates/avro/kafka-inbound-connector.json, connectors/kafka/pom.xml, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorProperties.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/model/Avro.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunction.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/model/KafkaConnectorRequest.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/model/KafkaMessage.java, connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java, connectors/kafka/src/test/java/io/camunda/connector/kafka/integration/KafkaIntegrationTest.java, connectors/kafka/src/test/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunctionTest.java, connectors/kafka/src/test/resources/example-avro-schema.json, connectors/kafka/src/test/resources/requests/success-test-cases.json
relates to #camunda/team-connectors/issues/436
=> feat(avro): Experimental Avro support

parent/pom.xml
=> chore(spring-zeebe): Use 8.3.0-alpha7 of spring-zeebe.

parent/pom.xml
fix(zeebe): set desired Zeebe version explicitly
=> fix(zeebe): set desired Zeebe version explicitly

bundle/default-bundle/README.md, bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/LocalConnectorRuntime.java, connectors/README.md
=> chore(package): Fix the package name of the local connector runtime

bundle/default-bundle/README.md, bundle/default-bundle/src/test/java/io/camunda/coonnector/runtime/app/LocalConnectorRuntime.java, connectors/README.md
Reverts camunda/connectors#1167
=> Revert "chore(package): Fix the package name of the local connector runtime"

bundle/default-bundle/README.md, bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/LocalConnectorRuntime.java, connectors/README.md
=> 1166 fix the package name of the localconnectorruntime

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/Keywords.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandlerTest.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java, connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspectorUtilTests.java, connector-runtime/connector-runtime-spring/src/test/resources/bpmn/multi-webhook-start-message.bpmn, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/correlation/MessageStartEventCorrelationPoint.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/correlation/ProcessCorrelationPoint.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/result/CorrelatedMessageStart.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/result/MessageStartCorrelationResult.java, connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-message-start.json, connectors/aws/aws-sns/element-templates/aws-sns-inbound-message-start.json, connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json, connectors/github/element-templates/github-webhook-connector-message-start.json, connectors/kafka/element-templates/kafka-connector-message-start.json, connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-message-start.json, connectors/slack/element-templates/slack-inbound-message-start.json, connectors/webhook/element-templates/webhook-connector-start-message.json
feat: add message start event support
Note: other connectors will be supplied later after I complete with testing at least Kafka, and SQS.
=> feat: add message start event support

connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
Element Template uses same descriptions as Outbound Connector, even though another operation is performed.
=> fix(element-template): Adjust Description for Inbound Operations

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandlerTest.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java, connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspectorUtilTests.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/correlation/MessageStartEventCorrelationPoint.java
feat(message start events): add correlation key support
=> feat(message start events): add correlation key support

connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-message-start.json, connectors/aws/aws-sns/element-templates/aws-sns-inbound-message-start.json, connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json, connectors/github/element-templates/github-webhook-connector-message-start.json, connectors/kafka/element-templates/kafka-connector-message-start.json, connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-message-start.json, connectors/slack/element-templates/slack-inbound-message-start.json, connectors/webhook/element-templates/webhook-connector-start-message.json
feat(message start event): add correlation variables
=> feat(message start event): add correlation variables

connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/model/KafkaTopic.java
=> feat(kafka): Support FEEL expressions for topic properties

.github/workflows/CREATE_RELEASE_BRANCH.yml, .github/workflows/RELEASE.yaml
Release workflow debugging, possibly not the last PR
=> Fix release workflows

.github/workflows/CREATE_RELEASE_BRANCH.yml, .github/workflows/RELEASE.yaml
More release workflow adjustments
=> Release workflow adjustments

parent/pom.xml
=> chore(deps): Upgrade to latest spring-zeebe release candidate

.github/workflows/RELEASE.yaml
=> build: fix docker images not being pushed

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java
chore(correlation): fixed correct message ID fetching
Was throwing NPE for boundary events.
=> chore(correlation): fixed correct message ID fetching

connectors/http/polling/element-templates/http-polling-connector-boundary.json
Added http-polling boundary connector template
=> chore(http-polling): add http-polling boundary connector template

.github/workflows/CREATE_RELEASE_BRANCH.yml
=> build: push release branch before creating a PR

.github/workflows/CREATE_RELEASE_BRANCH.yml
Fix: push branch using the create-pull-request action instead of manually.
=> build: create release branch workflow fix

.github/workflows/TEST_FEATURE_BRANCH.yml
Adds a new trigger event to support [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
related to https://github.com/camunda/team-connectors/issues/453
=> build: configure merge queue for main

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
=> 1270 add tenant information to common log statements

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/BpmnError.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/JobBuilder.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/ErrorResponse.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelConnectorFunctionProvider.java, connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java
=> chore(bpmn): Support BPMN error variables

connector-sdk/element-template-generator-http/pom.xml, connector-sdk/element-template-generator-http/src/main/java/io/camunda/connector/generator/http/HttpOperation.java, connector-sdk/element-template-generator-http/src/main/java/io/camunda/connector/generator/http/HttpOperationBuilder.java, connector-sdk/element-template-generator-http/src/main/java/io/camunda/connector/generator/http/HttpOutboundElementTemplateBuilder.java, connector-sdk/element-template-generator-http/src/main/java/io/camunda/connector/generator/http/HttpPathFeelBuilder.java, connector-sdk/element-template-generator-http/src/main/java/io/camunda/connector/generator/http/HttpServerData.java, connector-sdk/element-template-generator-http/src/test/java/io/camunda/connector/generator/http/HttpOutboundElementTemplateBuilderTest.java, connector-sdk/element-template-generator-http/src/test/java/io/camunda/connector/generator/http/HttpPathFeelBuilderTest.java, connector-sdk/element-template-generator-http/src/test/resources/http-outbound-test-element-template.json, connector-sdk/element-template-generator/pom.xml, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplate.java, connector-sdk/element-template-generator/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplateBuilder.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/OutboundTemplateGeneratorTest.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/example/DuplicatePropertyConnectorInput.java, connector-sdk/element-template-generator/src/test/java/io/camunda/connector/generator/core/example/MyConnectorFunction.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/Authentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/BasicAuthentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/BearerAuthentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/CustomAuthentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/OAuthAuthentication.java, parent/pom.xml, pom.xml
First iteration of the new template generator SDK layer for building HTTP connector templates.
related to https://github.com/camunda/team-connectors/issues/524
=> [WIP] feat(generator): HTTP element template SDK

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/webhook/VerifiableWebhook.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/webhook/WebhookConnectorExecutable.java, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializer.java, connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java, connectors/slack/element-templates/slack-inbound-message-start.json, connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java, connectors/slack/src/main/java/io/camunda/connector/slack/inbound/model/SlackWebhookProperties.java, connectors/slack/src/test/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutableTest.java
feat(sdk): adding verification expression
=> feat(sdk): adding verification expression

connectors/slack/element-templates/slack-inbound-intermediate.json, connectors/slack/element-templates/slack-inbound-start-event.json
feat(slack): added missing verification expression
=> feat(slack): added missing verification expression

connectors/slack/element-templates/slack-inbound-intermediate.json, connectors/slack/element-templates/slack-inbound-message-start.json, connectors/slack/element-templates/slack-inbound-start-event.json
chore(slack): bump slack versions
=> chore(slack): bump slack versions

connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-boundary.json, connectors/slack/element-templates/slack-inbound-boundary.json, connectors/twilio/element-templates/twilio-webhook-boundary-connector.json, connectors/twilio/element-templates/twilio-webhook-message-start-connector.json
fix(connectors): add missing connectors
=> fix(connectors): add missing connectors

connectors/github/element-templates/github-connector.json
=> fix(github): Fix issue comment creation

.github/workflows/RELEASE.yaml
Add element-template-cli step to prevent the release pipeline from failing.
closes #
=> build: add element-template-cli step to the release pipeline

connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-boundary.json, connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-intermediate.json, connectors/aws/aws-sns/element-templates/aws-sns-inbound-boundary.json, connectors/aws/aws-sns/element-templates/aws-sns-inbound-intermediate.json, connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json, connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json, connectors/github/element-templates/github-webhook-connector-boundary.json, connectors/github/element-templates/github-webhook-connector-intermediate.json, connectors/kafka/element-templates/kafka-inbound-connector-boundary.json, connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json, connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-boundary.json, connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-intermediate.json, connectors/slack/element-templates/slack-inbound-boundary.json, connectors/slack/element-templates/slack-inbound-intermediate.json, connectors/twilio/element-templates/twilio-webhook-boundary-connector.json, connectors/twilio/element-templates/twilio-webhook-intermediate-connector.json, connectors/webhook/element-templates/webhook-connector-boundary.json, connectors/webhook/element-templates/webhook-connector-intermediate.json
feat(indempotency): added message ID to boundary and intermediate connectors
=> feat(indempotency): added message ID to boundary and intermediate connectors

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/webhook/VerifiableWebhook.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/webhook/WebhookConnectorExecutable.java, connectors/slack/src/main/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutable.java, connectors/slack/src/test/java/io/camunda/connector/slack/inbound/SlackInboundWebhookExecutableTest.java, connectors/webhook/element-templates/webhook-connector-boundary.json, connectors/webhook/element-templates/webhook-connector-intermediate.json, connectors/webhook/element-templates/webhook-connector-start-event.json, connectors/webhook/element-templates/webhook-connector-start-message.json, connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java, connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java, connectors/webhook/src/main/java/io/camunda/connector/inbound/utils/HttpWebhookUtil.java, connectors/webhook/src/test/java/io/camunda/connector/inbound/HttpWebhookExecutableTest.java
feat(webhook): add verification expression support
=> feat(webhook): add verification expression support

.github/workflows/BACKPORT_PR.yml
Fixed the trigger condition for GH action.
=> build: fix backport action trigger

element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/ConGen.java, element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/Generate.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/api/GeneratorConfiguration.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/BpmnType.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplate.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/OutboundElementTemplateBuilder.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGenerator.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/ElementTemplate.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/ConfigurationUtil.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/BaseTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/OutboundElementTemplateSerializationTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/OutboundElementTypeSupportTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/MyConnectorFunction.java, element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilder.java, element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilderTest.java, element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ElementTemplateGeneratorMojo.java, element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
Support generating multiple element templates for different element types in one run.
related to https://github.com/camunda/team-connectors/issues/547
=> feat(generator)!: Template generation for multiple element types

connectors/microsoft/LICENSE.txt, connectors/microsoft/README.md, connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json
feat(msft,o365): added mail connector
=> feat(msft,o365): added mail connector

connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json, connectors/webhook/element-templates/webhook-connector-boundary.json, connectors/webhook/element-templates/webhook-connector-intermediate.json, connectors/webhook/element-templates/webhook-connector-start-event.json, connectors/webhook/element-templates/webhook-connector-start-message.json
=> Several fixes pre-release

connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/AbstractFeelDeserializer.java
A hotfix for broken FEEL context aware deserialization.
related to https://github.com/camunda/connectors/issues/1552
=> fix(jackson): broken feel context aware deserialization

.github/workflows/RELEASE.yaml, .github/workflows/scripts/prev_tag.sh
Smart previous tag selector script for the release process. It will allow us to always generate the correct changelog.
closes #1554
=> ci: smart tag selector for release workflow

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/ConnectorError.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/FailJob.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/Incident.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/JobError.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ErrorExpressionJobContext.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/JobBuilder.java, connector-sdk/feel-wrapper/pom.xml, connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelConnectorFunctionProvider.java, connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java, connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelDeserializer.java, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializer.java, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelSupplierDeserializer.java
Currently, the error expression can only handle the creation of `bpmnError`. This PR enables creation of `incident`.
closes #1444 
closes #1383
=> Create incident from error expression

bundle/default-bundle/Dockerfile, connector-runtime/connector-runtime-application/Dockerfile, connector-runtime/connector-runtime-application/start.sh
fix(bundle,docker): fix comment
=> fix(bundle,docker): fix comment

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorReportingContext.java
=> Fix javadocs

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorReportingContext.java
=> Fix javadocs health reporting again

.github/workflows/DEPLOY_SNAPSHOTS.yaml, .github/workflows/RELEASE.yaml, .github/workflows/TEST_FEATURE_BRANCH.yml, bundle/camunda-saas-bundle/Dockerfile, bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSOperateClientFactory.java, bundle/camunda-saas-bundle/src/main/resources/application.properties, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/SecurityConfigurationTest.java, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/TestSpringContextStartup.java, bundle/default-bundle/Dockerfile, connector-runtime/connector-runtime-application/Dockerfile, connector-runtime/spring-boot-starter-camunda-connectors/src/test/resources/application.properties, connectors/aws/aws-dynamodb/pom.xml, connectors/google/google-sheets/pom.xml, parent/pom.xml
- Configuration changes to support the new Operate client & Spring Zeebe
- Migrate to Java 21
closes #
=> Support new Operate client / Migrate to Java 21

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSOperateClientFactory.java
Fix property resolution error in SaaS
=> Fix operate client auth

parent/pom.xml
=> Upgrade spring-zeebe to 8.4.0-alpha2-rc5

.ci/preview-environments/charts/c8sm/values.yaml, .github/workflows/PREVIEW-ENV-DEPLOY.yml, .github/workflows/PREVIEW-ENV-TEARDOWN.yml
Related to https://github.com/camunda/connectors/pull/1617 and https://github.com/camunda/team-infrastructure/issues/510
This PR to:
- fix typos in the name (and branch) of the workflow `PREVIEW-ENV-DEPLOY.yml`
- use the `web-modeler-ee/modeler-webapp` Docker image (remove old workaround)
=> chore(preview-env): Final adjustments

parent/pom.xml
=> chore(deps): Update to spring-zeebe 8.4.0-rc1

parent/pom.xml
=> chore(deps): Update to spring-zeebe 8.3.4.7

renovate.json
Enable renovate for our release/8.4 branch, since we will no longer rebase it onto main.
=> chore: renovate.json to cover release/8.4

parent/pom.xml
deps(spring-zeebe): bump Spring Zeebe to 8.4.0-rc3
Might fail until dependency is actually published to artifactory.
=> deps(spring-zeebe): bump Spring Zeebe to 8.4.0-rc3

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connectors-e2e-test/connectors-e2e-test-base/pom.xml, connectors/webhook/pom.xml, parent/pom.xml
Updated spring-boot version, but that is not compatible with the wiremock dependency we used, so I had to switch to standalone wiremock.
https://github.com/camunda/connectors/issues/1835
closes #
=> feat(dependency): upgrade spring-boot version to 3.2.2

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-sdk/test/pom.xml, connectors-e2e-test/connectors-e2e-test-base/pom.xml, connectors/webhook/pom.xml, parent/pom.xml
* feat(dependency): upgrade spring-boot version to 3.2.2
* fix(rest): provide more specific mapping info for /inbound/{context} endpoint
* feat(dependency): add missing apache commons-io dependency
(cherry picked from commit 209e64cc9929d4843029d68d916ed0546cd77956)
closes #
=> feat(dependency): upgrade spring-boot version to 3.2.2 (#1836)

.github/workflows/RELEASE.yaml
* build(release): update versions in release branches
(cherry picked from commit ecc537ebed1a607cf4892d6d89c58157df512ea7)
=> build(release): add a step to update version in the release branch (#1935)

connectors/slack/element-templates/slack-outbound-connector-hybrid.json, connectors/slack/element-templates/slack-outbound-connector.json, connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ChatPostMessageData.java, connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ConversationsCreateData.java, connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ConversationsInviteData.java
chore(slack): polish generated content
=> chore(slack): polish generated content

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java, parent/pom.xml
=> chore(spring-zeebe): Upgrade to spring zeebe 8.4.2-rc1

connectors/webhook/pom.xml, parent/pom.xml
* chore(dependency): specify commons-compress and nimbus-jose-jwt version
* fix: add missing commons-codec dependency
(cherry picked from commit 81369e034d630dbae513c5a79387ae35721f0f4e)
=> Fix CWE 770 and CWE 835 (#2029)

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java, parent/pom.xml
chore(spring-zeebe): update to relevant dep
=> chore(spring-zeebe): update to relevant dep

parent/pom.xml, renovate.json
chore(renovate): add rule excluding snapshot
=> chore(renovate): add rule excluding snapshot

connectors/github/element-templates/github-connector.json
closes #2022, closes #2024, closes #2025
=> feat(github): create reference, create pull request, list collaborators

bundle/camunda-saas-bundle/src/main/resources/application.properties, connector-runtime/connector-runtime-spring/pom.xml, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretApiClient.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretProvider.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/EnvironmentSecretProvider.java, connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/secret/ConsoleSecretProviderTest.java, connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/secret/EnvironmentSecretProviderTest.java, connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ConnectorProperties.java, connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/EnvironmentSecretProviderTest.java
https://github.com/camunda/team-connectors/issues/663
=> feat(hybrid secrets): Access SaaS cluster connector secrets

parent/pom.xml
deps(spring-zeebe): bump version
=> deps(spring-zeebe): bump version

parent/pom.xml
deps(spring-zeebe): bump Spring Zeebe to 8.3.6
=> deps(spring-zeebe): bump Spring Zeebe to 8.3.6

parent/pom.xml
deps(spring-zeebe): bump Spring Zeebe to 8.5.0-alpha2
=> deps(spring-zeebe): bump Spring Zeebe to 8.5.0-alpha2

connectors/google/google-base/src/main/java/io/camunda/google/model/Authentication.java, connectors/google/google-drive/element-templates/google-drive-outbound-connector.json, connectors/google/google-drive/element-templates/hybrid/google-drive-outbound-connector-hybrid.json, connectors/google/google-drive/pom.xml, connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/Resource.java, connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/Template.java, connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/Variables.java, connectors/google/google-sheets/element-templates/google-sheets-outbound-connector.json, connectors/google/google-sheets/element-templates/hybrid/google-sheets-outbound-connector-hybrid.json, connectors/google/google-sheets/pom.xml, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/GoogleSheetsFunction.java, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/model/request/input/DeleteColumn.java
Fix google connectors - post-QA
=> Fix google connectors

connectors-e2e-test/connectors-e2e-test-soap/src/test/java/io/camunda/connector/e2e/soap/SoapConnectorBaseTest.java, connectors/soap/element-templates/hybrid/soap-outbound-connector-hybrid.json, connectors/soap/element-templates/soap-outbound-connector.json, connectors/soap/pom.xml, connectors/soap/src/main/java/io/camunda/connectors/soap/SoapConnector.java, connectors/soap/src/main/java/io/camunda/connectors/soap/SoapConnectorInput.java
chore(soap): update SOAP connector to the latest generator
=> chore(soap): update SOAP connector to the latest generator

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java, connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java, connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java, connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java
fix(feel): fixed timestamp serialization
=> fix(feel): fixed timestamp serialization

connectors/http/graphql/element-templates/graphql-outbound-connector.json, connectors/http/graphql/src/main/java/io/camunda/connector/http/graphql/GraphQLFunction.java, connectors/http/graphql/src/test/java/io/camunda/connector/http/graphql/GraphQLFunctionSecretsTest.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/BasicAuthentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/BearerAuthentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/NoAuthentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/auth/OAuthAuthentication.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/AuthenticationService.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpRequestMapper.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/services/HttpRequestMapperTest.java, connectors/http/rest/element-templates/http-json-connector.json, connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json, connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java, connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionSecretsTest.java
chore(rest): added validation to OAuth token URL
=> chore(rest): added validation to OAuth token URL

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java, connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
- Removed the unescaping logic
- Improved logging
- Added new test case
https://github.com/camunda/connectors/issues/2239
closes https://github.com/camunda/connectors/issues/2239
=> fix(kafka): fix kafka deserialization

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java, connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
Manual backport of https://github.com/camunda/connectors/pull/2240
https://github.com/camunda/connectors/issues/2239
closes #
=> fix(kafka): fix kafka deserialization (#2240)

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpInteractionService.java
fix(rest): more meaningful error message on invalid host
=> fix(rest): more meaningful error message on invalid host

connectors/webhook/element-templates/webhook-connector-boundary.json, connectors/webhook/element-templates/webhook-connector-intermediate.json, connectors/webhook/element-templates/webhook-connector-start-event.json, connectors/webhook/element-templates/webhook-connector-start-message.json, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
Found in https://github.com/camunda/connectors/pull/2279#discussion_r1547546047
=> fix(generator): FEEL mode = disabled not applied in some cases

connectors/aws/aws-sns/element-templates/aws-sns-inbound-boundary.json, connectors/aws/aws-sns/element-templates/aws-sns-inbound-intermediate.json, connectors/aws/aws-sns/element-templates/aws-sns-inbound-message-start.json, connectors/aws/aws-sns/element-templates/aws-sns-inbound-start-event.json, connectors/aws/aws-sns/pom.xml, connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/inbound/SnsWebhookExecutable.java, connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/inbound/model/SnsWebhookConnectorProperties.java, connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/inbound/model/SnsWebhookProcessingResult.java, connectors/aws/aws-sns/src/test/java/io/camunda/connector/sns/inbound/SnsWebhookExecutableTest.java
chore(sns): migrate to element template generator
=> chore(sns): migrate to element template generator

connectors/gitlab/element-templates/gitlab-connector.json
Implements https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository and https://docs.gitlab.com/ee/api/repository_files.html#update-existing-file-in-repository for the GitLab connector
closes #2298, closes #2299
=> feat(gitlab): get and update repository files

connectors/jdbc/element-templates/hybrid/jdbc-outbound-connector-hybrid.json, connectors/jdbc/element-templates/jdbc-outbound-connector.json
chore(jdbc): regenerated updates
=> chore(jdbc): regenerated updates

element-template-generator/congen-cli/README.md, element-template-generator/openapi-parser/README.md, element-template-generator/postman-collections-parser/README.md
Update usage examples of `congen`
=> docs(congen): update examples

connectors/webhook/element-templates/webhook-connector-boundary.json, connectors/webhook/element-templates/webhook-connector-intermediate.json, connectors/webhook/element-templates/webhook-connector-start-event.json, connectors/webhook/element-templates/webhook-connector-start-message.json
chore(webhook): regenerated webhook
=> chore(webhook): regenerated webhook

bundle/default-bundle/src/test/resources/application.properties, connector-runtime/connector-runtime-application/src/main/resources/application.properties
chore(spring): simplify application properties
=> chore(spring): simplify application properties

connectors/hugging-face/element-templates/hugging-face-connector.json, connectors/microsoft/azure-open-ai/element-templates/azure-open-ai-connector.json
chore(azure,openai): add doc ref to connector
=> chore(azure,openai): add doc ref to connector

bundle/default-bundle/src/test/resources/application.properties, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/PublishMessageCommandDummy.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java, connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/InboundConnectorsAutoConfiguration.java, parent/pom.xml
=> Backport 2351 to release/8.5

connectors/aws/aws-sns/element-templates/hybrid/aws-sns-inbound-boundary-hybrid.json, connectors/aws/aws-sns/element-templates/hybrid/aws-sns-inbound-intermediate-hybrid.json, connectors/aws/aws-sns/element-templates/hybrid/aws-sns-inbound-message-start-hybrid.json, connectors/rabbitmq/element-templates/hybrid/rabbitmq-inbound-connector-boundary-hybrid.json, connectors/rabbitmq/element-templates/hybrid/rabbitmq-inbound-connector-intermediate-hybrid.json, connectors/rabbitmq/element-templates/hybrid/rabbitmq-inbound-connector-message-start-hybrid.json, connectors/slack/element-templates/hybrid/slack-inbound-boundary-hybrid.json, connectors/slack/element-templates/hybrid/slack-inbound-intermediate-hybrid.json, connectors/slack/element-templates/hybrid/slack-inbound-message-start-hybrid.json, connectors/webhook/element-templates/hybrid/webhook-connector-boundary-hybrid.json, connectors/webhook/element-templates/hybrid/webhook-connector-intermediate-hybrid.json, connectors/webhook/element-templates/hybrid/webhook-connector-start-event-hybrid.json, connectors/webhook/element-templates/hybrid/webhook-connector-start-message-hybrid.json
chore(hybrids): regenerated hybrids
=> chore(hybrids): regenerated hybrids

parent/pom.xml
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
(cherry picked from commit 5bd96f57ce974af3b218b038975546b5af735516)
closes #
=> fix(deps): update version.spring-zeebe to v8.5.2 (#2255)

parent/pom.xml
Backport PR - automatic backport failed
closes #
=> fix(deps): upgrade spring-zeebe to 8.5.3

connectors/jdbc/pom.xml, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/SupportedDatabase.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionHelper.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionStringHelper.java
Manual backport from https://github.com/camunda/connectors/pull/2502
=> feat(jdbc): Remove MySQL ConnectorJ and use MariaDb instead

connectors/jdbc/pom.xml, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/SupportedDatabase.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionHelper.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelper.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionStringHelper.java, connectors/jdbc/src/test/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelperTest.java
Addressing compilation issues from https://github.com/camunda/connectors/pull/2506
Accidentally merged it before pipelines were finished.
=> fix(jdbc): Address issues with manual backport of "MySQL ConnectorJ and use MariaDb instead"

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
closes https://github.com/camunda/team-connectors/issues/768
=> fix(inbound): Dont fail health check of importer due to import error

bundle/default-bundle/pom.xml, bundle/pom.xml, connectors/jdbc/element-templates/hybrid/jdbc-outbound-connector-hybrid.json, connectors/jdbc/element-templates/jdbc-outbound-connector.json, connectors/jdbc/pom.xml, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/SupportedDatabase.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/connection/AuthProperties.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/connection/DetailedConnection.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/connection/UriConnection.java, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionStringHelper.java, connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/IntegrationBaseTest.java, connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/IntegrationTestConfig.java, connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/JdbiJdbcClientIntegrationTest.java, connectors/pom.xml
- Add support for MariaDB
- Fix password encoding issue
- Add the jdbc connector to the bundle
- Fix and reworked integration tests to run a MariaDB container
closes https://github.com/camunda/team-connectors/issues/740
closes https://github.com/camunda/team-connectors/issues/773
=> feat(jdbc): Add MariaDB support 

connectors/jdbc/element-templates/hybrid/jdbc-outbound-connector-hybrid.json, connectors/jdbc/element-templates/jdbc-outbound-connector.json, connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/JdbcRequest.java
I forgot to add MariaDB in the element template dropdown :)
closes https://github.com/camunda/team-connectors/issues/773
=> feat(jdbc): Add MariaDB to the databases dropdown

README.md, connector-sdk/core/README.md, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/webhook/WebhookResult.java
This PR updates the documentation examples after merging #2134 
Also, it fixes the broken javadoc that prevents snapshot deployment from the main branch
=> docs: update correlation examples

.github/workflows/INTEGRATION_TEST.yml, .github/workflows/helm-git-refs.json
=> Helm integration tests for release branches (#2612)

.github/workflows/RELEASE.yaml
See https://github.com/camunda/connectors/pull/2651
=> ci: rollback target commitish change in the release workflow

.github/workflows/RELEASE.yaml
(cherry picked from commit 567bb40e8aeec0d3ef41ba62a0ee1f48d1060029)
Backport #2674 to release/8.6
=> ci: rollback target commitish change in the release workflow (#2674)

element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/ConGen.java
This PR will change the default value to match the enum (this was forgotten during the refactoring where this enum was introduced)
=> fix(congen): change default element type to match enum

.github/workflows/scripts/prev_tag-test.sh, .github/workflows/scripts/prev_tag.sh
- Add support for alpha minor releases (-alphaX.Y) 
closes https://github.com/camunda/team-connectors/issues/796
=> chore(release): Handle minor Alpha versions when releasing

connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/ObjectMapperSerializationTest.java, parent/pom.xml
Bump spring-zeebe to 8.4.6
https://github.com/camunda/connectors/issues/2648
=> fix(deps): Bump spring-zeebe to 8.4.6

parent/pom.xml
Fix for [CVE-2024-29025](https://www.cve.org/CVERecord?id=CVE-2024-29025)
=> fix: update azure-identity version

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java, connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java, connectors-e2e-test/connectors-e2e-test-automation-anywhere/src/test/java/io/camunda/connector/e2e/BaseAutomationAnywhereTest.java, connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java, connectors-e2e-test/connectors-e2e-test-kafka/src/test/java/io/camunda/connector/e2e/BaseKafkaTest.java
Backport #2038 to release/8.5
related: https://github.com/camunda/team-connectors/issues/647
=> fix(importer): prevent OOM by filtering out older process versions eerly on

parent/pom.xml
relates to https://github.com/camunda/connectors/issues/2023
=> deps(feel-engine): Upgrade FEEL engine to 1.18.0-alpha1

.github/workflows/helm-git-refs.json
Helm charts version was not updated.
Discussion [here](https://camunda.slack.com/archives/C03UR0V2R2M/p1718961348597649?thread_ts=1718961070.655519&cid=C03UR0V2R2M).
=> fix(helm): Fix Helm integration tests

connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json, connectors/slack/element-templates/slack-outbound-connector.json, connectors/slack/src/main/java/io/camunda/connector/slack/outbound/SlackFunction.java
=> feature 653 update version for slack outbound connector fromn 3 to 4

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/auth/OAuthAuthentication.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/authentication/OAuthServiceTest.java, connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpServiceTest.java, connectors/http/rest/src/test/resources/requests/success-test-cases-oauth.json
- Fix default timeout issue 
- Fix issue with empty scopes when using OAuth 
closes https://github.com/camunda/team-connectors/issues/824
=> fix(rest): Fix Timeout default value and OAuth empty scopes issues

parent/pom.xml
https://github.com/camunda/connectors/pull/2739
closes #
=> chore(deps): update azure-identity dependency version

connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/GoogleSheetOperation.java, connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/impl/CreateWorksheetOperation.java, connectors/google/google-sheets/src/test/java/io/camunda/connector/gsheets/operation/impl/CreateWorksheetOperationTest.java
This PR adds a useful response to the "add worksheet" operation
This will require an adjustment to the documentation.
closes #2796 
PS: Can this be backported?
=> Google Sheets Connector: Adding a worksheet will return the properties of the worksheet

connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/integration/RabbitMqIntegrationTest.java
A check was added to be sure, the unicode escaping is respected 
An integration test was added to test that unicode are escaped properly
#2730
=> other(rabbitMQ): add integration test for rabbitMQ to verify message integrity

connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/OffsetUpdateRequiredListener.java, connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
Backport of: https://github.com/camunda/connectors/pull/2852
https://github.com/camunda/connectors/issues/2846
=> fix(kafka): Handle consumerGroup properly + update the offset override part

bundle/camunda-saas-bundle/Dockerfile, bundle/default-bundle/Dockerfile, connector-runtime/connector-runtime-application/Dockerfile
Backport https://github.com/camunda/connectors/pull/2981
=> [Backport release/8.3] fix(dockerfile): replace addgroup with groupadd in Dockerfile

connectors/aws/aws-bedrock/element-templates/aws-bedrock-outbound-connector.json, connectors/aws/aws-bedrock/element-templates/hybrid/aws-bedrock-outbound-connector-hybrid.json, connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/model/ConverseData.java, connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/model/InvokeModelData.java
Small fixes related to https://github.com/camunda/team-connectors/issues/869 
@slolatte  has tested the new connector and has given her feedback. this is the PR correcting thoses issues
https://github.com/camunda/team-connectors/issues/869
=> fix(aws-bedrock): small fixes on the element templates

connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json, connectors/slack/element-templates/slack-outbound-connector.json, connectors/slack/src/main/java/io/camunda/connector/slack/outbound/SlackFunction.java
Increase the version of the element template.
https://github.com/camunda/connectors/issues/2695
=> fix(slack) increase the version of the element template

renovate.json
=> chore(renovate): Support github action automerges

connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java, connectors/soap/element-templates/hybrid/soap-outbound-connector-hybrid.json, connectors/soap/element-templates/soap-outbound-connector.json
Quick fix concerning a backport issue
=> fix(tests): backport issue

element-template-generator/maven-plugin/README.md
Describe how to trigger the element template generation.
closes https://github.com/camunda/team-connectors/issues/661
=> docs(element-template-generator): Describe how to trigger the generation

element-template-generator/postman-collections-parser/README.md, element-template-generator/postman-collections-parser/src/main/java/io/camunda/connector/generator/postman/utils/PostmanOperationUtil.java
Modified the postman-collection-parser to support generating template by providing operation ids.
closes #3160
=> feat(element-template-generator): generate template from postman collection by operation ids

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/CODEQL.yml, .github/workflows/PULL_REQUEST_MILESTONE_VALID.yml
- Update the PR Template to inform that we need either a Milestone or the `no milestone` label now
- Create the PR check
=> other(GHA): Add a check ensuring a PR has a milestone or the NO MILESTONE label

parent/pom.xml
Patch bump to fix [CVE-2024-34750](https://www.cve.org/CVERecord?id=CVE-2024-34750) on the release/8.5 branch
None - part of Security Officer duties
=> fix(deps): update spring boot to v3.3.3

parent/pom.xml
Manual backport of https://github.com/camunda/connectors/pull/3287
related https://github.com/camunda/team-connectors/issues/919
=> deps(spring-boot): upgrade to 3.3.4 (#3287)

parent/pom.xml
Manual backport of https://github.com/camunda/connectors/pull/3287
related https://github.com/camunda/team-connectors/issues/919
=> chore(deps): upgrade spring-boot to 3.3.4

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
Backport of https://github.com/camunda/connectors/pull/3288
=> Backport 3288 to release/8.3

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
Backport of https://github.com/camunda/connectors/pull/3288
=> chore(backport): Backport 3288

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
Backport of https://github.com/camunda/connectors/pull/3288
=> chore(inbound): Set the readiness to True when starting (#3288)

connectors/soap/pom.xml
Manual backport of https://github.com/camunda/connectors/pull/3287
related https://github.com/camunda/team-connectors/issues/919
=> chore(deps): upgrade spring boot to 3.3.4

parent/pom.xml
Reverts camunda/connectors#3059
=> Revert "fix(deps): update version.spring-zeebe (release/8.5)"

connectors/http/rest/README.md
Spotless expects this table formatting
None
=> other(readme): fix connector-http-json spotless

connectors/kafka/element-templates/hybrid/kafka-inbound-connector-boundary-hybrid.json, connectors/kafka/element-templates/hybrid/kafka-inbound-connector-intermediate-hybrid.json, connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-message-hybrid.json, connectors/kafka/element-templates/hybrid/kafka-outbound-connector-hybrid.json, connectors/kafka/element-templates/kafka-inbound-connector-boundary.json, connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json, connectors/kafka/element-templates/kafka-inbound-connector-start-message.json, connectors/kafka/element-templates/kafka-outbound-connector.json, connectors/kafka/src/main/java/io/camunda/connector/kafka/model/schema/AvroInlineSchemaStrategy.java
Fix the bindings for Avro Schema 
https://github.com/camunda/team-connectors/issues/646
=> chore(kafka): Fix bindings for Avro schema

.github/workflows/RELEASE.yaml
Backport of #3356 to `release/8.5`.
=> ci(release): prevent deleting commits (#3356)

.github/workflows/RELEASE.yaml
Manual backport of #3380 to `release/8.3`.
=> ci(release): force push release tag

bundle/camunda-saas-bundle/pom.xml, connectors-e2e-test/connectors-e2e-test-base/pom.xml, connectors/kafka/pom.xml
Backport of #3399 to `release/8.6`.
=> [Backport release/8.6] other(cve): Fix 2 Critical CVEs

.gitignore, bundle/camunda-saas-bundle/pom.xml, connectors/pom.xml, parent/pom.xml
Fix [CVE-2024-7254](https://www.cve.org/CVERecord?id=CVE-2024-7254)
=> other(cve): Fix CVE-2024-7254

.gitignore, connectors/pom.xml, parent/pom.xml
Backport of #3408 to `release/8.4`.
=> [Backport release/8.4] other(cve): Fix CVE-2024-7254

.gitignore, bundle/camunda-saas-bundle/pom.xml, connectors/pom.xml, parent/pom.xml
Backport of #3408 to `release/8.6`.
=> [Backport release/8.6] other(cve): Fix CVE-2024-7254

connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java, connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java, connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java
Backport of #3415 to `release/8.6`.
=> [Backport release/8.6] fix(sqs): fail fast when queue does not exist

connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java, connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java, connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java
Backport #3415 to release/8.5
#3415
=> fix(sqs): fail fast when queue does not exist (#3415)

.github/workflows/CREATE_RELEASE_BRANCH.yml
- title and labels to pass new Connectors CI checks
- instructions on how to get CI checks to start
related https://github.com/camunda/team-connectors/issues/943
=> ci(create-release-branch): update PR details

.ci/preview-environments/charts/c8sm/Chart.yaml
=> chore(preview-environment): Update Chart.yaml

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundConnectorRestController.java
Backport of #3510 to `release/8.6`.
=> [Backport release/8.6] chore(logs): Add an endpoint to publish inbound logs

connector-runtime/connector-runtime-application/src/main/resources/application.properties
Backport of #3515 to `release/8.6`.
=> [Backport release/8.6] fix(prometheus): Re-add prometheus default config

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-runtime/spring-boot-starter-camunda-connectors/pom.xml, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
=> fix(webhook): Fix webhook and possible http client nullpointer exception

bundle/camunda-saas-bundle/src/main/resources/application.properties
=> chore(loggers): Enable log level actuator endpoint

connectors/email/element-templates/email-inbound-connector-boundary.json, connectors/email/element-templates/email-inbound-connector-intermediate.json, connectors/email/element-templates/email-message-start-event-connector.json, connectors/email/element-templates/hybrid/email-inbound-connector-boundary-hybrid.json, connectors/email/element-templates/hybrid/email-inbound-connector-intermediate-hybrid.json, connectors/email/element-templates/hybrid/hybrid-email-message-start-event-connector-hybrid.json, connectors/email/pom.xml, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/JakartaEmailListener.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/models/Email.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/models/EmailAttachment.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/models/EmailBody.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/models/Header.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java, connectors/email/src/main/java/io/camunda/connector/email/inbound/EmailConnectorExecutable.java, connectors/email/src/main/java/io/camunda/connector/email/inbound/model/EmailInboundConnectorProperties.java, connectors/email/src/main/java/io/camunda/connector/email/inbound/model/EmailListenerConfig.java, connectors/email/src/main/java/io/camunda/connector/email/inbound/model/HandlingStrategy.java, connectors/email/src/main/java/io/camunda/connector/email/inbound/model/PollAll.java, connectors/email/src/main/java/io/camunda/connector/email/inbound/model/PollUnseen.java, connectors/email/src/main/java/io/camunda/connector/email/inbound/model/PollingConfig.java, connectors/email/src/main/java/io/camunda/connector/email/outbound/EmailConnectorFunction.java, connectors/email/src/main/java/io/camunda/connector/email/response/ReadEmailResponse.java, connectors/email/src/main/resources/META-INF/services/io.camunda.connector.api.inbound.InboundConnectorExecutable, connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/JakartaExecutorTest.java, connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/JakartaUtilsTest.java, connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/PollingManagerTest.java, connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/TestImapMessage.java
Backport of #3438 to `release/8.6`.
=> [Backport release/8.6] feat(inbound-email-connector): create a new inbound email connector

.github/workflows/RUN_UNIQUET.yml, element-template-generator/uniquet/pom.xml, element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/core/ElementTemplateIterator.java, element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/core/GitCrawler.java, element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/dto/Engine.java, element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/dto/OutputElementTemplate.java, element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/dto/VersionValue.java, element-template-generator/uniquet/src/test/java/io/camunda/connector/core/GitCrawlerTest.java, element-template-generator/uniquet/src/test/resources/fakepom.xml
I have added a proposition of adding the runtime inside the ET
closes https://github.com/camunda/team-connectors/issues/945
=> chore(uniquet): add uniquet job to add the single ET file

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/LlmModel.java, parent/pom.xml
Updated the prompt for `Llama` LLM.
closes https://github.com/camunda/connectors/issues/3641
=> feat(idp-extraction-connector): update prompt for llama llm

.github/workflows/RUN_UNIQUET.yml
=> others(uniquet): patch: Update RUN_UNIQUET.yml

.github/workflows/RUN_UNIQUET.yml
=> others(uniquet): Update RUN_UNIQUET.yml

.github/workflows/PREVIEW-ENV-DEPLOY.yml
Change the deploy preview job timeout since the tests are being way longer than they used to be.
=> chore(deploy-preview): Update PREVIEW-ENV-DEPLOY.yml

element-template-generator/uniquet/README.md, element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/core/GitCrawler.java
Few modifications were made to bring sorting and pretty print feature to the connectors-file.json
closes #https://github.com/camunda/connectors/issues/3699
=> feat(uniquet): bring sorting and pretty print feature

connector-runtime/spring-boot-starter-camunda-connectors/pom.xml, connectors/email/element-templates/email-outbound-connector.json, connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java, connectors/email/src/main/java/io/camunda/connector/email/outbound/EmailConnectorFunction.java, connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/ContentType.java, connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java, connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/JakartaExecutorTest.java, parent/pom.xml
cherry-pick the feature for the mail connector to send out html templates
closes [#SUPPORT-24840](https://jira.camunda.com/browse/SUPPORT-24840)
=> chore (mail-outbound-connector): cherry pick from main mail template connector feature

parent/pom.xml
=> chore(deps): bump zeebe version

connector-sdk/core/pom.xml, connectors-e2e-test/connectors-e2e-test-automation-anywhere/pom.xml, connectors-e2e-test/connectors-e2e-test-aws/pom.xml, connectors-e2e-test/connectors-e2e-test-easy-post/pom.xml, connectors-e2e-test/connectors-e2e-test-http/pom.xml, connectors-e2e-test/connectors-e2e-test-kafka/pom.xml, connectors-e2e-test/connectors-e2e-test-mail/pom.xml, connectors-e2e-test/connectors-e2e-test-rabbitmq/pom.xml, connectors-e2e-test/connectors-e2e-test-soap/pom.xml
=> chore(deps): bump snapshot dependencies

connector-sdk/core/pom.xml, connectors-e2e-test/connectors-e2e-test-automation-anywhere/pom.xml, connectors-e2e-test/connectors-e2e-test-aws/pom.xml, connectors-e2e-test/connectors-e2e-test-easy-post/pom.xml, connectors-e2e-test/connectors-e2e-test-http/pom.xml, connectors-e2e-test/connectors-e2e-test-kafka/pom.xml, connectors-e2e-test/connectors-e2e-test-mail/pom.xml, connectors-e2e-test/connectors-e2e-test-rabbitmq/pom.xml, connectors-e2e-test/connectors-e2e-test-soap/pom.xml
* chore(deps): bump snapshot dependencies
* fix enforcer
(cherry picked from commit 97b2c0f9fc3d02f6a31982b58fd23b6d5d18e986)
closes #
=> chore(deps): bump snapshot dependencies (#3759)

connectors/README.md, connectors/aws/aws-dynamodb/README.md, connectors/aws/aws-eventbridge/README.md, connectors/aws/aws-lambda/README.md, connectors/aws/aws-sns/README.md, connectors/aws/aws-sqs/README.md, connectors/google/google-drive/README.md, connectors/http/graphql/README.md, connectors/http/rest/README.md, connectors/http/rest/README.peb, connectors/jdbc/README.md, connectors/kafka/README.md, connectors/microsoft-teams/README.md, connectors/rabbitmq/README.md, connectors/sendgrid/README.md, connectors/slack/README.md
Fix broken links
See [this discussion](https://camunda.slack.com/archives/C02JLRNQQ05/p1733781945497719)
=> docs(readme): Fix all the broken documentation links

renovate.json
Automerge minor helm chart updates
=> chore(renovate): Add automerge for minor helm updates

connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java, connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java, connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java, connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/JacksonModuleDocumentDeserializer.java, connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/JacksonModuleDocumentSerializer.java, connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/serializer/DocumentSerializer.java, connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/DocumentDeserializationTest.java, connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/DocumentSerializationTest.java, connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java, connector-sdk/test/src/main/java/io/camunda/connector/test/outbound/OutboundConnectorContextBuilder.java
Hacking session on document handling
closes #
=> refactor(document-handling): Hacking session split document modules

element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/BpmnType.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplateGenerationContextUtil.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/ElementTypeSupportTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorFunction.java
To use message send connector, it is useful to include send tasks for connectors as well.
closes #
=> feat(element-template-generator): allow send tasks using connectors

element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/BpmnType.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplateGenerationContextUtil.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/ElementTypeSupportTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorFunction.java
Backport of #3827 to `release/8.6`.
=> [Backport release/8.6] feat(element-template-generator): allow send tasks using connectors

connector-runtime/spring-boot-starter-camunda-connectors/pom.xml, connectors/http/rest/README.md
Done during hacking session to make developper experience better while creating new connectors
closes #
=> fix(connector-runtime): add exclusion of spring-core creating dependencies incompatibility

parent/pom.xml
=> proposal: move to 8.5.16 of spring zeebe

bundle/camunda-saas-bundle/src/main/resources/application.properties, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/TestSpringContextStartup.java
Fix the SaaS config to use the new config format.
=> fix(config): apply new configuration in saas yaml file

bundle/camunda-saas-bundle/src/main/resources/application.properties, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/TestSpringContextStartup.java
Backport of #3854 to `release/8.7`.
=> [Backport release/8.7] fix(config): apply new configuration in saas yaml file

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConfiguration.java
This PR will update the cluster ID reference in the SaaS configuration.
closes #
=> fix(config): update saas clusterid reference

.github/workflows/TEST_FEATURE_BRANCH.yml
We cannot merge PR coming from forked repository as tests never gets executed even after being approved
closes #
=> chore(github-action): tests should be executed on fork when approved by the team

.github/workflows/ENFORCE_QA_APPROVAL.yml, .github/workflows/TEST_FEATURE_BRANCH.yml
Change the `pull_request` event into `pull_request_event`
closes #
=> chore(github-action): change pull_request event into pull_request_target

connector-sdk/document/src/main/java/io/camunda/document/reference/CamundaDocumentReferenceImpl.java, connector-sdk/document/src/main/java/io/camunda/document/reference/DocumentReference.java, connector-sdk/document/src/main/java/io/camunda/document/store/CamundaDocumentStoreImpl.java, connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/DocumentReferenceModel.java
=> fix(document-handling): Backport getting a document by reference

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/utils/AwsS3Util.java
Backport of #3869 to `release/8.7`.
=> [Backport release/8.7] fix(idp-extraction-connector): remove double download in idp connector

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSOperateClientFactory.java, bundle/camunda-saas-bundle/src/main/resources/application.properties
- Fix the different variables to contact Zeebe/Operate
=> other(properties): Fix application properties

.github/workflows/BACKPORT_PR.yml
Use our GitHub App ID for backports
=> chore(gh-action): Use GH app for backports

.github/workflows/BACKPORT_PR.yml
=> fix(backport): Use GH app for backports using the right secret path

connectors/soap/element-templates/hybrid/soap-outbound-connector-hybrid.json, connectors/soap/element-templates/soap-outbound-connector.json
Revert accidental element template changes from #3950 
closes #
=> fix: revert accidental element template changes

parent/pom.xml
After creating [a fix](https://github.com/camunda-community-hub/spring-zeebe/pull/1047), the release version has to be adjusted.
resolves a part of https://github.com/camunda/camunda-platform-helm/issues/2357
closes #
=> fix(deps): spring zeebe 8.5.17

connectors/webhook/element-templates/hybrid/webhook-connector-boundary-hybrid.json, connectors/webhook/element-templates/hybrid/webhook-connector-intermediate-hybrid.json, connectors/webhook/element-templates/hybrid/webhook-connector-start-event-hybrid.json, connectors/webhook/element-templates/hybrid/webhook-connector-start-message-hybrid.json, connectors/webhook/element-templates/webhook-connector-boundary.json, connectors/webhook/element-templates/webhook-connector-intermediate.json, connectors/webhook/element-templates/webhook-connector-start-event.json, connectors/webhook/element-templates/webhook-connector-start-message.json, connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java
=> docs(webhook): change webhook doc link 

connectors/sendgrid/src/test/java/io/camunda/connector/sendgrid/SendGridRequestTest.java
Fix broken formatting which causes actions on main to fail.
=> fix(sendgrid-connector): Fix formatting

connectors/email/pom.xml
Remove unused dependency that ended up in the final jar.
=> fix(email-connector): Remove unused dependency

bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/CorsConfiguration.java
Fix the missing license header
=> fix(license): Fix missing license file

.github/workflows/RELEASE.yaml, .github/workflows/helm-git-refs.json
=> 991 separate maven release and docker pushbuild in ci 8.8

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/ProxyHandler.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
=> chore(licence-header): Add missing licence header

.github/workflows/RELEASE.yaml
=> other(CI): separate maven release job and docker build and push fix

bundle/default-bundle/src/main/resources/application.properties, bundle/default-bundle/src/test/resources/application.properties
This PR will introduce uniform config properties in the right format for our 8.7 images.
closes #
=> fix(properties): correct properties for 8.7 docker images

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/ProxyHandler.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
Fixed the (sometimes) failing tests on main
=> chore(tests): Fix race condition in ProxyHandler tests

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/InboundConnectorContext.java, connector-sdk/core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java, connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java, connector-sdk/test/src/main/java/io/camunda/connector/test/outbound/OutboundConnectorContextBuilder.java, connectors/aws/aws-bedrock/element-templates/aws-bedrock-outbound-connector.json, connectors/aws/aws-bedrock/element-templates/hybrid/aws-bedrock-outbound-connector-hybrid.json, connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/BedrockConnectorFunction.java, connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/S3ConnectorFunction.java, connectors/box/src/main/java/io/camunda/connector/box/BoxOperations.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java, connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java, connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/mapper/DocumentMapper.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/ExecutionEnvironment.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/HttpService.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/document/FileResponseHandler.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/TestDocumentFactory.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionResponseTransformer.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java
Backport of https://github.com/camunda/connectors/pull/4049
https://github.com/camunda/team-connectors/issues/1015
=> Backport 8.7 1015 rest connector cant upload documents in saas

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
Missing spotless:apply from a Fork PR
=> other(lint): apply spotless

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java
- Add some CORS configuration for `/inbound-instances` and `/tenants`
- Allow all methods
=> other(cors): Add CORS configuration for the /inbound-instances endpoint

connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json, connectors/slack/element-templates/slack-outbound-connector.json
Just slack template version increase.
closes #
=> feat(slack): increase template versions

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
=> fix(rest): add support for lists for Parts in a multipart request

parent/pom.xml
For maven release goal
closes #
=> fix(version): bump version camunda for release

.github/workflows/DEPLOY_SNAPSHOTS.yaml
=> fix(ci): typo in a workflow

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSOperateClientFactory.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretApiClient.java, parent/pom.xml
This is the resolution for https://github.com/camunda-community-hub/camunda-operate-client-java/issues/186
closes #
=> fix(deps): operate client 8.6.5

.github/workflows/BUILD_FEATURE_BRANCH.yaml, .github/workflows/DEPLOY_8.7_SNAPSHOTS.yaml, .github/workflows/DEPLOY_SNAPSHOTS.yaml, .github/workflows/RELEASE.yaml, .github/workflows/TEST_FEATURE_BRANCH.yml, parent/pom.xml
=> fix(ci): nexus mirror

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java, bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/OrganizationIdAndRolesValidator.java, bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java, bundle/camunda-saas-bundle/src/main/resources/application.properties, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/InboundInstancesSecurityConfigurationTest.java, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/security/OrganizationIdAndRolesValidatorTest.java, bundle/camunda-saas-bundle/src/test/resources/application.properties, bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/CorsConfiguration.java, bundle/default-bundle/src/test/resources/application-docker-core.properties, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundConnectorRestController.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundInstancesRestController.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/exception/DataNotFoundException.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/exception/GlobalExceptionHandler.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/ConnectorDataMapper.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/operate/OperateClientConfiguration.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundEndpointTest.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundInstancesRestControllerTest.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/Activity.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/Health.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java
=> Backport 4144 to release/8.7

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java, bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/CorsConfiguration.java, bundle/default-bundle/src/test/resources/application-local.properties, renovate.json
- Fix CORS configuration for subpaths of `/inbound-instances`. 
- Rename some propreties
=> chore(cors): fix cors config for /inbound-instances subpaths

LICENSE.txt
This is to create a LICENSE file and uses the LICENSE.txt content already found in other camunda projects.
Required as part of this conversation: https://camunda.slack.com/archives/C02JLRNQQ05/p1741274555123489
=> chore(license): create LICENSE.txt file

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java, bundle/camunda-saas-bundle/src/main/resources/application.properties, bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/CorsConfiguration.java, bundle/default-bundle/src/test/resources/application-docker-core.properties, renovate.json
Backport of https://github.com/camunda/connectors/pull/4203
=> Backport 4203 to release/8.7

.github/workflows/PREVIEW-ENV-DEPLOY.yml
Update preview environment deployment workflow with new troubleshooting capabilities
- https://github.com/camunda/team-infrastructure/issues/792
- https://github.com/camunda/team-infrastructure/issues/521
=> chore(ci): update preview environment deployment with new troubleshooting capabilities

bundle/camunda-saas-bundle/pom.xml, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/CreateCommandDummy.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/PublishMessageCommandDummy.java, connector-runtime/spring-boot-starter-camunda-connectors/pom.xml, parent/pom.xml
This PR moves connectors 8.6 to use a 8.6 zeebe client
closes #
=> chore: move to zeebe 8.6

bundle/camunda-saas-bundle/Dockerfile, bundle/default-bundle/Dockerfile, connector-runtime/connector-runtime-application/Dockerfile
Upgrade all packages in our docker images to latest versions
closes https://github.com/camunda/team-connectors/issues/1023
=> fix(build): upgrade packages in docker images

element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyBinding.java, element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpAuthentication.java, element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java, element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilderTest.java, element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/BodyUtil.java, element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/ParameterUtil.java, element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/SecurityUtil.java, element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/PublicSpecsTest.java, element-template-generator/openapi-parser/src/test/resources/publicSpecs/paycom.yaml, element-template-generator/openapi-parser/src/test/resources/publicSpecs/paypalcheckout.yaml, element-template-generator/openapi-parser/src/test/resources/publicSpecs/peachpay.yaml, element-template-generator/openapi-parser/src/test/resources/publicSpecs/stripe.yaml
| OpenAPI Spec        | Import Status | Issue Description | New Import Status                                                                                                                                                                                        | Fixes                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                           | …
=> feat(element-template-generator): Improve openAPI handling

connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/DocumentAwareMultipartEntityBuilder.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionFilePart.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/utils/DocumentHelperTest.java, connectors/http/rest/element-templates/http-json-connector.json, connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json, connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java, connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpJsonFunctionTest.java, parent/pom.xml
Backport https://github.com/camunda/connectors/pull/4194
Backport https://github.com/camunda/connectors/pull/4380
=> Backport 4380 to release/8.7

renovate.json
=> fix(renovate): Update renovate.json

renovate.json
=> fix(renovate): Use the right regex format

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/InvalidBackOffDurationException.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorExceptionHandler.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/secret/SecretUtil.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/JobHandlerContextTest.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/jobhandling/SpringConnectorJobHandler.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/outbound/ConnectorJobHandlerTests.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/outbound/JobBuilder.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/utils/TestSecretProvider.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/utils/TestValidation.java, connector-sdk/validation/src/main/java/io/camunda/connector/validation/impl/DefaultValidationProvider.java, connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/TextractConnectorFunctionTest.java, connectors/http/rest/element-templates/http-json-connector.json, connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json, connectors/soap/element-templates/hybrid/soap-outbound-connector-hybrid.json, connectors/soap/element-templates/soap-outbound-connector.json
Backport of the feature to hide secret in the log
closes #
=> Backport 4307 to release/8.7

renovate.json
https://docs.renovatebot.com/string-pattern-matching/#glob-matching
closes #
=> chore(renovate.json): Use glob matching

renovate.json
Remove a newly introduced property
closes #
=> chore(renovate): Update renovate.json

renovate.json
=> chore(renovate.json): Remove snapshot filter

connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json
Bump version after changes in #4393
=> chore(office-365): bump element template version

connectors/soap/element-templates/hybrid/soap-outbound-connector-hybrid.json, connectors/soap/element-templates/soap-outbound-connector.json
=> others(soap-et): new soap ET into main

connectors/email/src/main/java/io/camunda/connector/email/config/ImapConfig.java
Add @FEEL to the inbound connector `imapPort` property
=> fix(inbound-connector): add  to the imap port used in the inbound connector

connectors-e2e-test/connectors-e2e-test-base/pom.xml, parent/pom.xml
This PR moves the 8.4 version to the latest patch.
closes #
=> chore: move to 8.4.17 spring zeebe

parent/pom.xml
This PR moves the zeebe client to 8.5.16
closes #
=> Move to zeebe client 8.5.16

renovate.json
=> chore(renovate): Renovate disable major minor camunda updates

renovate.json
=> chore(renovate): Fix io.camunda matching

.github/workflows/RELEASE.yaml
=> chore(gh-action): Increase release worker

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientImpl.java
=> chore(fix-main): fix main after names changes

connectors/aws/aws-bedrock/pom.xml
closes [SEC-1332](https://jira.camunda.com/browse/SEC-1332)
=> chore(dependency): Upgrade commons-io dependency

parent/pom.xml
=> chore: move camunda libraries to 8.7

parent/pom.xml
Remove unavailable camunda-java dependency
closes #4583
=> chore(dependency): Remove camunda-java dependency

connectors/kafka/pom.xml, connectors/webhook/pom.xml, parent/pom.xml
Added the rule and fixed the errors.
closes #4582
=> chore(plugins): Add requirePluginVersions rule

connectors-e2e-test/connectors-e2e-test-aws/connectors-e2e-test-aws-base/src/test/java/io/camunda/connector/e2e/BaseAwsTest.java, connectors-e2e-test/connectors-e2e-test-kafka/src/test/java/io/camunda/connector/e2e/BaseKafkaTest.java, connectors-e2e-test/connectors-e2e-test-kafka/src/test/java/io/camunda/connector/e2e/InboundKafkaTests.java, connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/BaseRabbitMqTest.java
=> chore(integration-test): fix integration tests

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestExceptionZeebeTests.java
Zeebe error code are mapped properly
closes https://github.com/camunda/connectors/issues/4625
=> fix(webhook): Error coming from zeebe are now managed properly

connectors/kafka/pom.xml
https://jira.camunda.com/browse/SEC-1324
=> chore(dependency): Upgrade classgraph dependency to fix CVE

connectors/hugging-face/element-templates/hugging-face-connector.json
for reference: https://camunda.slack.com/archives/C07TDMJUG4R/p1745843190497299
closes #
=> chore(hugging-face): bring the runtime to 8.5 instead of 8.6 for version 2

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConnectorRuntimeApplication.java, bundle/default-bundle/pom.xml, bundle/pom.xml, connector-runtime/connector-runtime-application/src/main/java/io/camunda/connector/runtime/app/ConnectorRuntimeApplication.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/operate/OperateClientAdapterConfiguration.java, connectors-e2e-test/connectors-e2e-test-message/pom.xml, connectors-e2e-test/connectors-e2e-test-message/src/test/java/io/camunda/connector/e2e/MessageTests.java, connectors-e2e-test/pom.xml, connectors/camunda-message/README.md, connectors/camunda-message/element-templates/hybrid/hybrid-send-message-connector-intermediate-throw-event-hybrid.json, connectors/camunda-message/element-templates/hybrid/hybrid-send-message-connector-message-end-event-hybrid.json, connectors/camunda-message/element-templates/hybrid/hybrid-send-message-connector-send-task-hybrid.json, connectors/camunda-message/element-templates/send-message-connector-intermediate-throw-event.json, connectors/camunda-message/element-templates/send-message-connector-message-end-event.json, connectors/camunda-message/element-templates/send-message-connector-send-task.json, connectors/camunda-message/pom.xml, connectors/camunda-message/src/main/java/io/camunda/connector/message/SendMessageConnectorFunction.java, connectors/camunda-message/src/main/java/io/camunda/connector/message/SendMessageRequest.java, connectors/camunda-message/src/main/java/io/camunda/connector/runtime/app/ZeebeClientContext.java, connectors/camunda-message/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction, connectors/camunda-message/src/main/resources/send.svg, connectors/camunda-message/src/test/resources/correlate-message-process.bpmn, connectors/camunda-message/src/test/resources/correlation-failed-process.bpmn, connectors/camunda-message/src/test/resources/receive-message-process.bpmn, connectors/camunda-message/src/test/resources/send-message-connector-test-process.bpmn, connectors/pom.xml
Backport of #4199 to release/8.7
closes #
=> Backport Message outbound connector (#4199) to release/8.7

connectors-e2e-test/connectors-e2e-test-message/src/test/java/io/camunda/connector/e2e/MessageTests.java
=> other(e2e): fix end tests

connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-initial-request.form, connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-user-feedback.form, connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-with-tools.bpmn
No code changes - only updating the provided examples with document handling support.
related to #4683
=> docs(agentic-ai): add document handling to AI agent chat with tools example

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/AiAgentTests.java
Changes in https://github.com/camunda/camunda/pull/31674 break the current variable test setup. Uses the get variable API now if the search response is truncated instead of the removed `getFullValue()` accessor.
https://github.com/camunda/camunda/pull/31674
=> test(agentic-ai): update agentic AI e2e test to account for search variable API changes

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/AiAgentTests.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/feel/FeelInputParamExtractionException.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/feel/FeelInputParamExtractor.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CachingAdHocToolsSchemaResolver.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolver.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/schema/DefaultAdHocToolSchemaGenerator.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/schema/SchemaGenerationException.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/DefaultAiAgentRequestHandler.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/AgentContext.java, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/AgentMetrics.java, connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/feel/FeelInputParamExtractorTest.java, connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CachingAdHocToolsSchemaResolverTest.java, connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolverTest.java, connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/schema/DefaultAdHocToolSchemaGeneratorTest.java, connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/AgentContextTest.java, connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/AgentMetricsTest.java
* Improves error handling and exception messages when the tools schema configuration is wrong or fromAi is used in a wrong way
* Better error handling when the agent context is not set up properly (e.g. an agent receives tool results, but according to its context never requested tool calls)
* Uses `ConnectorException` with an error code where applicable.
based on #4719 
related to #4683
=> refactor(agentic-ai): improve error handling & exception messages

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java
=> others(email): Fix email connector pr

connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java, connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/PollingManagerTest.java, connectors/email/src/test/java/io/camunda/connector/email/integration/InboundEmailTest.java
=> others(backport) backport email fix to 8.7

connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector-8.8.0-alpha4.json, connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-8.8.0-alpha4-hybrid.json
Adds alpha4 compatbile AI Agent templates with the updated icon.
=> other(agentic-ai): track 8.8.0-alpha4 compatible templates with new icon

CODEOWNERS
Add rules for AI & IDP collaborators
=> chore(CODEOWNERS): Add rules for AI & IDP collaborators

.github/workflows/ADD_TO_PROJECT.yml
=> chore(issues): route new issues to AI team boards based on label.

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/state/ProcessStateStoreImpl.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/CorrelationRequest.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/LogTag.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/LogTag.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java, connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutableLifecycleTest.java, connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java
This PR is the result of our review of inbound connectors' activity logs. This is the first part, covering improvements for:
- RabbitMQ
- Kafka
- Webhook
We will do a second round next week.
related #4773
=> chore(inbound): Review activity logs, part 1

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/state/ProcessStateStoreImpl.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java, connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/CorrelationRequest.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java, connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/LogTag.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/LogTag.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java, connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java, connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutableLifecycleTest.java, connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java
Backport of #4780 to 8.7
closes #
=> [Backport to 8.7] chore(inbound): refine activity logs

bundle/camunda-saas-bundle/Dockerfile, bundle/default-bundle/Dockerfile, connector-runtime/connector-runtime-application/Dockerfile
Fix the environment variable for camunda client cache path.
relates to #4819
=> fix(camunda-client): Fix config path env variable

bundle/camunda-saas-bundle/Dockerfile, bundle/default-bundle/Dockerfile, connector-runtime/connector-runtime-application/Dockerfile
=> fix(client-config): Fix client credentials auth cache path env

.github/workflows/RUN_UNIQUET.yml, element-template-generator/uniquet/src/main/java/io/camunda/connector/uniquet/core/ConnectorsFinder.java
Modify the job creating the new element template single file
=> chore(uniquet): Uniquet job modification after refactor

bundle/default-bundle/src/test/resources/application.properties, connector-sdk/document/pom.xml, connector-sdk/document/src/main/java/io/camunda/intrinsic/functions/GetJsonFunction.java, connector-sdk/document/src/main/java/io/camunda/intrinsic/functions/GetJsonFunctionTest.java, connector-sdk/document/src/main/resources/META-INF/services/io.camunda.intrinsic.IntrinsicFunctionProvider, connector-sdk/document/src/test/java/io/camunda/intrinsic/functions/GetJsonFunctionTest.java
-  Add a new `getJson` intrinsic function
- if no path is provided, the whole document is returned as JSON and can be manipulated using feel
- otherwise, only the selected part will be returned
=> feat(intrinsic-function): Adding new intrinsic function for retrieving JSON data

bundle/default-bundle/src/test/resources/application.properties, connector-sdk/document/pom.xml, connector-sdk/document/src/main/java/io/camunda/intrinsic/functions/GetJsonFunction.java, connector-sdk/document/src/main/resources/META-INF/services/io.camunda.intrinsic.IntrinsicFunctionProvider, connector-sdk/document/src/test/java/io/camunda/intrinsic/functions/GetJsonFunctionTest.java
Backport of https://github.com/camunda/connectors/pull/4818
=> Backport 4818 to release/8.7

bundle/pom.xml, connectors/http/http-base/pom.xml, connectors/idp-extraction/pom.xml, connectors/pom.xml, parent/pom.xml
This was initially done to resolve a CVE, they updated the version so we do not have to do it anymore
closes #
=> chore(dependencies-removal): remove protobuf dependency

connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentToolCallingTests.java, connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentUserPromptDocumentsTests.java
Covered in unit tests, so we can reduce  some of the tests.
=> test(agentic-ai): reduce e2e document test cases

parent/pom.xml
=> chore(zeebe-version): increase zeebe version

bundle/camunda-saas-bundle/README.md, bundle/camunda-saas-bundle/src/main/resources/application.properties, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/InboundInstancesSecurityConfigurationTest.java, bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java, bundle/default-bundle/README.md, bundle/default-bundle/src/main/resources/application.properties, bundle/default-bundle/src/test/resources/application.properties, connector-runtime/README.md, connector-runtime/connector-runtime-application/README.md, connector-runtime/connector-runtime-application/src/main/resources/application.properties, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java, connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java, connector-runtime/spring-boot-starter-camunda-connectors/src/main/resources/application.properties, connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/WebhookActivatedDocumentTests.java, connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/WebhookNotActivatedDocumentTests.java, connectors-e2e-test/connectors-e2e-test-message/src/test/java/io/camunda/connector/e2e/MessageTests.java, connectors/slack/src/test/resources/application.properties
This PR fixes the client config to use the latest set of properties
closes #
=> feat(bundle): use latest config property

bundle/camunda-saas-bundle/pom.xml, bundle/default-bundle/pom.xml, bundle/pom.xml, connector-runtime/connector-runtime-application/pom.xml, connector-runtime/connector-runtime-spring/pom.xml, connector-runtime/spring-boot-starter-camunda-connectors/pom.xml, connector-sdk/feel-wrapper/pom.xml, connector-sdk/jackson-datatype-feel/pom.xml, connectors-e2e-test/connectors-e2e-test-automation-anywhere/pom.xml, connectors-e2e-test/connectors-e2e-test-aws/connectors-e2e-test-aws-event-bridge/pom.xml, connectors-e2e-test/connectors-e2e-test-base/pom.xml, connectors-e2e-test/connectors-e2e-test-easy-post/pom.xml, connectors-e2e-test/connectors-e2e-test-http/pom.xml, connectors-e2e-test/connectors-e2e-test-kafka/pom.xml, connectors-e2e-test/connectors-e2e-test-rabbitmq/pom.xml, connectors-e2e-test/connectors-e2e-test-soap/pom.xml
(cherry picked from commit 70fb21aa6e64e18590ceb6adb7193f46dbf05de1)
closes #
=> chore(pom): add missing <name> tags based on artifactId value (#4952)

parent/pom.xml
=> chore(deployment): Fix deployment name on central

parent/pom.xml
=> chore(deps): use zeebe client 8.6.20

parent/pom.xml
Update to the newest zeebe client
=> chore(zeebe-version): Increase version

.github/workflows/DEPLOY_8.6_SNAPSHOTS.yaml
=> ci(snapshot): add specific deploy job name

connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
(cherry picked from commit a54a7aa1d23c1362848e80b21482cdc52f082d2d)
closes #
=> fix(google-maps): Fix address line null in validate address (#4977)

connectors/operate/element-templates/operate-connector.json, connectors/operate/element-templates/versioned/operate-connector-4.json
[See discussion here: https://github.com/camunda/camunda-docs/pull/6073](https://github.com/camunda/camunda-docs/pull/6073#discussion_r2194566883)
Blocked by: https://github.com/camunda/camunda-docs/pull/6073
closes #
=> fix(docs-link): Adjust link

connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json, connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json, connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java
See https://camunda.slack.com/archives/C08BHU6JQJG/p1752518783713219
=> docs(agentic-ai): Update AI Agent connector template agent context helper text

connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/CreateCommandDummy.java
=> chore(tests): Fix failing main

connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveClient.java, connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/GoogleDriveClientTest.java
Backport of https://github.com/camunda/connectors/pull/5049 to release/8.5
=> feat(gdrive): Add support for GDrive shared folders and drives

connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/CreateCommandDummy.java
=> fix(DummyCommand): Implement terminateAfterElement

connector-sdk/core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorProvider.java
=> other(javadoc): Fix javadoc link

connectors/http/rest/README.md, connectors/microsoft/azure-blobstorage/element-templates/azure-blobstorage-outbound-connector.json, connectors/microsoft/azure-blobstorage/element-templates/hybrid/azure-blobstorage-outbound-connector-hybrid.json, connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/BlobStorageConnectorFunction.java, connectors/operate/element-templates/operate-connector.json
=> docs(links): fix documentation links

parent/pom.xml
=> chore(deps): bump spring zeebe to 8.5.21

parent/pom.xml
Bump camunda lib to 8.8.0-alpha7
=> deps(camunda): bump camunda client to 8.8.0-alpha7

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/CamundaClientSaaSConfiguration.java
Fix main after changes made by core team
=> fix(main): fix main after changes made by core team

connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java, connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractTextDetectionTask.java, connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java
backport pr of https://github.com/camunda/connectors/pull/5212
backports https://github.com/camunda/connectors/issues/5211
=> fix(idp-extraction-connector): backporting issue 5211 to 8.7

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/operation/ConnectorOperations.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/operation/OperationInvoker.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/operation/OutboundConnectorOperationFunction.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/operation/ParameterDescriptor.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/AnnotatedOperationConnector.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/AnnotatedOperationTests.java, connector-sdk/core/src/main/java/io/camunda/connector/api/annotation/Header.java, connector-sdk/core/src/main/java/io/camunda/connector/api/reflection/ReflectionUtil.java, connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializer.java, connectors/csv/element-templates/csv-outbound-connector.json, connectors/csv/element-templates/hybrid/csv-outbound-connector-hybrid.json, connectors/csv/element-templates/versioned/csv-outbound-connector-0.json, connectors/csv/src/main/java/io/camunda/connector/csv/CsvConnector.java, connectors/csv/src/main/java/io/camunda/connector/csv/CsvUtils.java, connectors/csv/src/main/java/io/camunda/connector/csv/model/ReadCsvResult.java, connectors/csv/src/test/java/io/camunda/connector/csv/CsvConnectorTests.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/OperationBasedConnectorUtil.java, element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java, element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/OperationAnnotatedConnector.java, element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ElementTemplateGeneratorMojo.java
=> feat(sdk): Add @Header binding support

connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTest.java
=> test(spring): failing tests after refactoring

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
=> chore(client): Fix return type of error

connector-runtime/connector-runtime-spring/pom.xml, connector-runtime/spring-boot-starter-camunda-connectors/pom.xml, connectors-e2e-test/connectors-e2e-test-base/pom.xml, connectors/agentic-ai/pom.xml, parent/pom.xml
=> chore(deps): Rename camunda artifact id

bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/AuthPropertiesNotPresentCondition.java, connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ProcessDefinitionImportHealthIndicator.java, connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ZeebeHealthIndicator.java
- Replace error logs with warnings when SaaS auth type condition is checked
- Add logging to health checks for easier debugging
closes #
=> other(logging): replace error logs with debug for saas auth type

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
(cherry picked from commit d27dca7)
=> fix(logging): log job completion at INFO level (#5356)

connector-commons/http-client/src/test/java/io/camunda/connector/http/client/client/apache/CustomApacheHttpClientTest.java, connector-runtime/connector-runtime-core/pom.xml, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/document/DocumentCreationException.java, connectors/http/http-base/src/main/java/io/camunda/connector/http/base/document/FileResponseHandler.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java, connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Backport of https://github.com/camunda/connectors/pull/5396
=> Backport 5396 to release/8.7

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/BpmnError.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/error/JobError.java, connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java, connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java, connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelConnectorFunctionProvider.java, connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java
closes https://github.com/camunda/connectors/issues/4667
=> chore(feel-function): Harmonize variables name with Camunda core

.github/workflows/DEPLOY_8.8_SNAPSHOTS.yaml, .github/workflows/ENFORCE_QA_APPROVAL.yml
As the connector medic, I was [pinged](https://camunda.slack.com/archives/C08MRKHJ0CD/p1758032921281189?thread_ts=1758031906.906299&cid=C08MRKHJ0CD) as we were not creating a `8.8-SNAPSHOT` version, this PR fixes this issue.
closes #
=> chore(release): commit to create an 8.8 snapshot

connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorExceptionHandler.java, connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/outbound/ConnectorJobHandlerTests.java
This pull request improves error handling in the outbound connector job execution flow, specifically when secret fetching fails. The main change ensures that if secrets cannot be fetched (for example, due to a network error), the system obfuscates the original error message to prevent accidental exposure of sensitive information. Additionally, new tests have been added to verify this behavior.
**Error handling improvements:**
* Updated `OutboundConnectorExceptionHandler.java` to catch exceptions during secret fetching and return a generic error message, wrapping the original exception to avoid leaking secrets.
**Testing enhancements:**
* Added a new test `shouldHideExceptionMessageWhenSecretsObfuscationFails` to verify that error messages are properly hidden when secret fetching fails. …
=> Handle secerts obsfucation errors

connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/job/OutboundConnectorExceptionHandler.java, connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/outbound/job/SpringConnectorJobHandlerTest.java
This pull request improves error handling in the outbound connector job handler by ensuring that sensitive information is not leaked if secret fetching fails. It introduces logic to obscure error messages when secrets cannot be fetched and adds comprehensive tests for this scenario.
Error handling improvements:
* Updated `OutboundConnectorExceptionHandler` to catch exceptions during secret fetching, log the issue, and return a generic error message that does not expose sensitive information if secret retrieval fails.
Testing enhancements:
* Added a new test `shouldHideExceptionMessageWhenSecretsObfuscationFails` in `SpringConnectorJobHandlerTest` to verify that error messages are properly obscured when secret fetching fails.
https://github.com/camunda/connectors/issues/5388
=> fix(secrets): Handle secrets obfuscation errors properly
